### ISSUE TITLE
Composer: Use conflict and suggest properties

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#10]
As mentioned in https://github.com/sonata-project/SonataClassificationBundle/pull/183, we should use the `suggest` [property](https://getcomposer.org/doc/04-schema.md#suggest) in the way it has been designed.

Some bundles use them as a normal `required` property, instead of leaving a message for this. The version information should be moved to the `conflicts` property.

Some bundles that I found so far:
- [x] SonataBlockBundle
- [x] SonataClassificationBundle
- [x] SonataDashboardBundle
- [x] SonataExporter
- [ ] SonataMediaBundle
- [x] SonataNewsBundle
- [ ] SonataNotificationBundle
- [x] SonataPageBundle
- [x] SonataSeoBundle
- [ ] SonataUserBundle

**Comment by VincentLanglet** [comment]
I opened a PR for the three repository
