### ISSUE TITLE
Fix PHP 8.0 build for dev-kit

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#1024]
@OskarStark :  09:19
@jordisala1991  what is needed to get PHP 8 tests green on dev-kit?

@jordisala1991   09:20
https://github.com/sonata-project/dev-kit/runs/1128236483
the config platform should be done before composer install (as it is)
the composer require phpunit should be done after (removing --no-update) (edited) 
(and with that, we would be able to see what is failing on test, probably) (edited) 

@OskarStark :  09:21
Could you find some time to check it?

@jordisala1991   09:22
the different between the rest of the sonata bundles is using install vs update on composer
probably not anytime soon
when I got time for open source, first I would like to finish some PRs on the adminbundle

@OskarStark :  09:22
Ok :+1:

**Comment by VincentLanglet** [comment]
Test / PHP 8.0 (pull_request) is fixed for the dev-kit repository.

And there is https://github.com/sonata-project/dev-kit/issues/1207 for others
