### ISSUE TITLE
Set repository topics via GithubApi...

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#1026]
... based on `keywords` in `composer.json`.

@VincentLanglet did the main work and I extracted a separate command which is currently inactive but generates the following output:
https://gist.github.com/OskarStark/330839576097bb82219b7eceebbc3c7e

I would propose to use the keywords + some additional logic like:
* Add `php` to all of our bundles
* Add `bundle` and `symfony-bundle` to alle which ends with `-bundle`
* Add `sonata` and `sonata-project` to all of our bundles

We could also add the used services from the configuration as topics...

**Comment by VincentLanglet** [comment]
> * Add `bundle` and `symfony-bundle` to alle which ends with `-bundle`

`bundle` seems enough to me.

But a `symfony` keyword can be added too.

**Comment by greg0ire** [comment]
Note: `sonata-exporter` contains a bundle part too

**Comment by greg0ire** [comment]
Note: `sonata-exporter` contains a bundle part too

**Comment by core23** [comment]
>     * Add `sonata` and `sonata-project` to all of our bundles

`sonata-project` sound's confusing. I would expect a project that is based on sonata.

> `bundle` seems enough to me.

AFAIK symfony recommends `symfony`, `bundle`and `symfony-bundle` for a symfony bundle.

**Comment by greg0ire** [comment]
> AFAIK symfony recommends symfony, bundleand symfony-bundle for a symfony bundle.

Do they? Why?

**Comment by VincentLanglet** [comment]
After some discuss here: https://github.com/sonata-project/SonataAdminBundle/pull/6395#pullrequestreview-492012838

I think
- `php` should not be added. Everything is `php` related when it can be downloaded with `composer`. `php` should only be use for something like a parser or a linter.
- `symfony` and `bundle` should definitely be used, since it's the most used keywords. I'm not convinced by `symfony-bundle` which does seems to be a duplicate (and is not used a lot).
- `sonata` should be used. `sonata-project` seems redundant to me and less clear.

**Comment by OskarStark** [comment]
> Note: sonata-exporter contains a bundle part too 

in this case we kann add it as a keyword to `composer.json`

**Comment by OskarStark** [comment]
![Bildschirmfoto 2020-09-20 um 10 29 49](https://user-images.githubusercontent.com/995707/93707108-3c7a4400-fb2c-11ea-9c95-8dd005af99d3.png)

Symfony uses `php` and `bundle` + `symfony-bundle`, so I am for adding `symfony-bundle`, `bundle` and `php`

**Comment by OskarStark** [comment]
This is the current result:
https://gist.github.com/OskarStark/c93a0f273e714043f84164a38f180c01

**Comment by VincentLanglet** [comment]
> Symfony uses `php` and `bundle` + `symfony-bundle`, so I am for adding `symfony-bundle`, `bundle` and `php`

It makes sense to add `php` on github. Not on packagist.
Maybe we should modify dev-kit to automatically add `php` ? @OskarStark
