### ISSUE TITLE
Make long lines forbidden, even for signatures

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#103]
I can see that all of you abide by the "no long lines" rule pretty well now, and this is great. However, there is still some resistance (from @Soullivaneuh :wink:  ) for signatures, be it class signatures or method signatures, because

1. It makes people notice that the class /signature does too many / has too may arguments
2. We should be consistent with existing code
3. Habits ?

My answers : 

1. Sometimes, if your class / function name is very long, and so are the name of your arguments, parent class, or interfaces you implement, you might end up with a very long line, but there is nothing wrong with the signature, so it would be a false positive. On the other hand, if you use multiline syntax, you see easily and exactly how many of them you have, and have a better feeling of whether there is a problem with the number of arguments or not. @Soullivaneuh : remember that Magento code you showed me? You can see the problem even better with multiline IMO.
2. Being consistent with code is writing bad code, we should absolutely not do that. Instead we should edict recommendations about new code, and **gradually** change existing code when we can / want  (sadly, there is no fixer for long lines, it is a hard problem to fix)
3. If you don't like that, think hard. Is it not because you don't have the habit, and don't like having your habits changed? Try multiline signatures for a while, and see if that does not change your mind, and be careful, because most of the time, if you don't like something "just because", it is a habit problem
4. Multiline makes it way easier to navigate in the arguments list.
5. This rule is not just about "normal code", or even code, it's about text. Humans like [short lines](http://baymard.com/blog/line-length-readability).
6. Exceptions make it harder to validate things
7. Last, but not least, linting tools will show distracting warning for this and mark the file as invalid, and make it harder to see other problems reported by, say, `phpmd`

Please vote :+1: to apply the rule without any exception, and :-1: if you're a dirty heretic.

**Comment by Soullivaneuh** [comment]
> and :-1: if you're a dirty heretic.

Well, this is not a vote if you start trolling people that disagree with you.

> Sometimes, if your class / function name is very long, and so are the name of your arguments, parent class, or interfaces you implement, you might end up with a very long line, but there is nothing wrong with the signature, so it would be a false positive.

Those case are **very rare** and no, I don't think this is bad to have this one-lined, even this is on more than 120 characters. On the same way, if you have a very long line with just two class name, there is maybe a problem with that too.

> Being consistent with code is writing bad code, we should absolutely not do that. Instead we should edict recommendations about new code, and gradually change existing code when we can / want (sadly, there is no fixer for long lines, it is a hard problem to fix)

Yes, but who says this is bad code? You. :wink: 

> If you don't like that, think hard. Is it not because you don't have the habit, and don't like having your habits changed? Try multiline signatures for a while, and see if that does not change your mind, and be careful, because most of the time, if you don't like something "just because", it is a habit problem

For my case, it's not a habit problem as I already said to you.

I see one line signature much clearer than multi-line, that's all.

> Exceptions make it harder to validate things

My point of you does include exceptions. The rules is simple. 120 chars max, but not for signature.

It would be an exception if I ask to line-break on some signatures, but not for others.

So I still :-1: for this, on I'm not a dirty heretic.

**Comment by greg0ire** [comment]
> Yes, but who says this is bad code? You. :wink: 

More than bad code, I say this is actually bad text. Just like http://stopwritingramblingcommitmessages.com/

> For my case, it's not a habit problem as I already said to you.

Why? Are you using multiline class / method signatures in your code ?

> So I still :-1: for this, on I'm not a dirty heretic.

Of course you're not, it's just a joke ;)

**Comment by Soullivaneuh** [comment]
> Why? Are you using multiline class / method signatures in your code ?

As far I'm against this, of course not. :-)

But this do not prove I'm against "because" of habit.

**Comment by greg0ire** [comment]
> But this do not prove I'm against "because" of habit.

Yes but this does :

> I see one line signature much clearer than multi-line, that's all.

I was like you for one day after I started using them. Just like when I started using PSR-2

**Comment by Soullivaneuh** [comment]
> Just like when I started using PSR-2

When I saw, PSR-2, I just enjoyed it. Multi-line signature, it's a no for me.

**Comment by greg0ire** [comment]
> When I saw, PSR-2, I just enjoyed it. Multi-line signature, it's a no for me.

Ok… @sonata-project/contributors , please vote so that we can get out of this dead end.

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors Please note that this vote is about class and method signature **only**, not the rest.

Just a PSR-2 reminder about that:

> There MUST NOT be a hard limit on line length

No hard limit, just soft. This means we will not line-break, for example, a `trigger_error` string for 4 characters left is this can be done on a smart way.

BTW, if method/class signature line-break if finally accepted, this rule must be apply for this too.

**Comment by greg0ire** [comment]
> No hard limit, just soft. This means we will not line-break, for example, a trigger_error string for 4 characters left is this can be done on a smart way.

I think PSR-2 talks about 80 and 120 precisely because of that : if you have 121 chars in your string, linebreak it to 80 chars will make it look worth it.

**Comment by greg0ire** [comment]
Related : http://stackoverflow.com/questions/14962667/what-is-a-line-length-soft-limit-and-how-do-i-interpret-this-in-the-psr-2-conv#18495354

**Comment by greg0ire** [comment]
Added a new point at the bottom of the list.

**Comment by Soullivaneuh** [comment]
> I think PSR-2 talks about 80 and 120 precisely because of that : if you have 121 chars in your string, linebreak it to 80 chars will make it look worth it.

This does not say that AFAIK:

>  the **soft** limit MUST be 120 characters; lines SHOULD be 80 characters or less.

> Related : http://stackoverflow.com/questions/14962667/what-is-a-line-length-soft-limit-and-how-do-i-interpret-this-in-the-psr-2-conv#18495354

First of all, this is a SO answer without source. And:

> 120+: Lint tools, IDEs, etc. MUST show a warning (but never an error!) since the line might be ugly/unreadable/...

Must show a warning, maybe. But it should not be considered as invalid. This is also why we will not set up tools for line length, this will be just cumbersome.

**Comment by greg0ire** [comment]
> Must show a warning, maybe. But it should not be considered as invalid. This is also why we will not set up tools for line length, this will be just cumbersome.

Yes but the warning is visual clutter, distracting us from real problems.

More to the point, is this acceptable, regardless of the number of arguments ? : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/ChoiceList/ModelChoiceList.php#L98

**Comment by Soullivaneuh** [comment]
> More to the point, is this acceptable, regardless of the number of arguments ? : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/ChoiceList/ModelChoiceList.php#L98

Honestly? For me, yes.

BTW, Symfony apply the same rules I'm defending. Example:
https://github.com/symfony/symfony/blob/fc32e6a7943c93c9f1470b28db6dcaf959bf7e19/src/Symfony/Bridge/Doctrine/Form/ChoiceList/EntityChoiceList.php#L114

And as we follow Symfony coding standard, I think we must do the same.

**Comment by greg0ire** [comment]
> BTW, Symfony apply the same rule I'm defending. Example:

O_o indeed

They also make 500 chars signatures (!) : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/SimpleFormAuthenticationListener.php#L58

Seriously… is there no limit ?

**Comment by Soullivaneuh** [comment]
In this case it's quite weird to have so many arguments.

But yes, Symfony does not line break any class/method signature ever.

Agree or not agree, we must follow it IMHO. Be sure if Symfony was doing line breaking, I would follow it too.

**Comment by greg0ire** [comment]
> Be sure if Symfony was doing line breaking, I would follow it too.

Well I know what is left for me to do :P

**Comment by greg0ire** [comment]
Trying to change symfony's mind right now : https://github.com/symfony/symfony/issues/18890#issuecomment-221866462

**Comment by Soullivaneuh** [comment]
@greg0ire As you want. Waiting that, we will keep single line signature.

**Comment by greg0ire** [comment]
Well they're not changing it so long signatures it is, I guess…
