### ISSUE TITLE
SonataCi should remove "review required" label after merge

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#112]
What do you think?

**Comment by core23** [comment]
It should remove all labels except:
- minor
- major
- patch
- bug
- critical
- docs

**Comment by OskarStark** [comment]
Yes

Am Sonntag, 29. Mai 2016 schrieb Christian Gripp :

**Comment by Soullivaneuh** [comment]
Quite related to #97.

**Comment by jordisala1991** [comment]
Review required is no longer there after : https://github.com/sonata-project/dev-kit/pull/288

Closing.
