### ISSUE TITLE
Dispatch: Do PR only on stable first, then on master

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#115]
The goal is to reduce the Travis load when the Dispatcher is running.

Most of the case, PR on stable and master branch are the same.

The proposed logic:

1. Check if some diff should be applied on stable branch
2. If yes, make a PR
3. Check if a PR is present for stable branch
4. If not, check if the stable branch is fully merged on master
5. If not and diff are present, make a PR against master

**Comment by greg0ire** [comment]
To be checked, but 5. might actually be : "make a PR against master, GH will not accept it if the diff is empty"

**Comment by Soullivaneuh** [comment]
> To be checked, but 5. might actually be : "make a PR against master, GH will not accept it if the diff is empty"

We already have an internal check: https://github.com/sonata-project/dev-kit/blob/a278d772e20a4a3400ea66d149fcd3a1af9b2ff4/src/Console/Command/DispatchCommand.php#L234

No need to push a dev-kit branch for nothing. ;-)

**Comment by greg0ire** [comment]
Oh. Great!
