### ISSUE TITLE
Set more settings on the repositories

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#1165]
I would like to disable `Packages` (and `Environments`) via API, but cannot find the settings in the API doc:

![CleanShot 2020-10-06 at 10 00 37](https://user-images.githubusercontent.com/995707/95176427-27a0e000-07bd-11eb-89a0-3e1c220ea5eb.png)

![CleanShot 2020-10-06 at 10 01 04](https://user-images.githubusercontent.com/995707/95176433-2a9bd080-07bd-11eb-83a7-eb260c929f01.png)

**Comment by VincentLanglet** [comment]
I did it manually
