### ISSUE TITLE
Use another kind of comment for dropping support of packages

### ISSUE THREAD

**Issue by franmomu** [sonata-project/dev-kit#1181]
Right now we use `NEXT_MAJOR` for everything. IMO we should use another kind of comment when it is related to dropping support for packages because this can be done in a minor version.

Related: https://github.com/sonata-project/SonataMediaBundle/pull/1814#discussion_r492047513 and https://github.com/sonata-project/SonataAdminBundle/pull/6465/files#r505919696

It would be nice to include the composer package name (`symfony/config`, `friendsofsymfony/rest-bundle`, etc) to be easy to find. 

And about what kind of comment, I have no idea, I've been thinking... but I couldn't come up with something I like.

**Comment by VincentLanglet** [comment]
> And about what kind of comment, I have no idea, I've been thinking... but I couldn't come up with something I like.

`TODO` ?

**Comment by phansys** [comment]
`DEPENDENCIES`? `MAINTENANCE`?

**Comment by greg0ire** [comment]
`REQUIRES_BUMP $package $version $whatNeedsToBeDone`?

**Comment by core23** [comment]
I would prefer something that speaks to the user and is not so technical releated like the `NEXT_MAJOR` comment. But I have no idea what it could be :( Maybe `TODO` as it's more common

**Comment by jordisala1991** [comment]
We are currently using TODO. Can this be closed?
