### ISSUE TITLE
Broken links on bundles documentation call to action

### ISSUE THREAD

**Issue by tambait** [sonata-project/dev-kit#1190]
Some of the [call to action links](https://sonata-project.org/bundles/timeline/3-x/doc/index.html) (_"Found a typo? Something is wrong in this documentation? Just fork and edit it!"_) on bundles documentation pages on the Sonata Project site are broken leading to 404 page.

For example,Timeline bundle links to `/3.x/Resources/doc/index.rst`, while it should be `/3.x/docs/index.rst`. 
or Cache bundle links to `/2.x/Resources/doc/index.rst` while it should be `/2.x/docs/index.rst`

However link for Doctrine PHPCR-ODM Admin is good. `https://sonata-project.org/bundles/doctrine-phpcr-admin/1-x/doc/index.html`

Not sure if there is more working links, didn't checked them all. 

Where I can fix the links and would it make sense to do it now (because of new releases etc)?

**Comment by jordisala1991** [comment]
This wont be a problem soon, docs are moving out of the website.
