### ISSUE TITLE
Analyzer bot

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#124]
The idea is to have a custom bot to analyse code and comment error parts that can not be detected by StyleCI or other linter.

For PHP, we could:
- Detect `@covers` usage.
- Detect `@test` usage.
- Detect useless comment like `Class MyClass` (thanks captain obvious).

Any idea would be welcomed.

**Comment by greg0ire** [comment]
> Detect useless comment like Class MyClass (thanks captain obvious).

What about useless phpdoc, like described here : http://mnapoli.fr/approaching-coding-style-rationally/ , or if we are going the other way, under-documented phpdoc cc @ju1ius

**Comment by Soullivaneuh** [comment]
> What about useless phpdoc

What do you mean ? AFAIK, phpdoc is mandatory on Symfony Coding Style.

**Comment by greg0ire** [comment]
> What do you mean? AFAIK, phpdoc is mandatory on Symfony Coding Style.

Oh right, and it's quite logic since it is supposed to alleviate the pain generated by using single-line method signatures :trollface:

**Comment by Soullivaneuh** [comment]
Oh, come on! :troll:

Sullivan SENECHAL
