### ISSUE TITLE
Send message to slack ci channel when a "DevKit updates" PR can't be merged

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#1252]
We have a message
```
SonataAdminBundle: Merging of 3.x into master contains conflicts. Skipped.
```
When a merge of 3.x into master can't be merged because of conflicts.

But we don't have a message when a 3.x-dev-kit into 3.x can't be automatically merged.
This could be a great improvement.

**Comment by OskarStark** [comment]
This makes sense to me 👍

**Comment by VincentLanglet** [comment]
For now we can find them here: https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3ASonataCI+archived%3Afalse
