### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#126]
Currently, HHVM is not **officially** supported by Sonata.

The Travis job is here but on failure section.

The question is: Is it worth to support HHVM?

The question is under debate in: https://github.com/symfony/symfony/issues/18922

Who is using HHVM on a project with sonata components?

:+1: for yes
:-1: for no

Note: Please use emoji reactions, not comments.

**Comment by jerson** [comment]
👍

**Comment by Soullivaneuh** [comment]
Stof proposed a PR to support higher hhvm version on Travis: https://github.com/symfony/symfony/pull/18947

And voted to keep HHVM support.

As the majority of our projects are Symfony bundles, I think we should follow Symfony decision.

This mean keep and improve HHVM support if they still support it.

**Comment by Soullivaneuh** [comment]
Final comment: https://github.com/symfony/symfony/issues/18922#issuecomment-223554314

So let's support HHVM.

I let this open waiting full support of it.

**Comment by Soullivaneuh** [comment]
6 packages does not currently work with HHVM:

* media-bundle
* timeline-bundle
* intl-bundle
* exporter
* doctrine-mongodb-admin-bundle (Because of mongo ext)

I'll update dev-kit to remove HVVM from allowed failures except for those one first.

**Comment by Soullivaneuh** [comment]
Another ref: https://docs.travis-ci.com/user/languages/php#HHVM-versions

**Comment by Soullivaneuh** [comment]
As Symfony is keeping the support and some peoples seem to use sonata under HHVM, I'll close this issue.

**Comment by Soullivaneuh** [comment]
#176
