### ISSUE TITLE
Do we need .gitattributes file?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#129]
Something like this:

```
.editorconfig    export-ignore
.gitattributes   export-ignore
.gitignore       export-ignore
CONTRIBUTING.md  export-ignore
```

Please use 👍  or 👎  to vote!

**Comment by greg0ire** [comment]
@Soullivaneuh IIRC, you told me this is specific to github… is there a way to get the same effect from a file in the .github directory ?

**Comment by OskarStark** [comment]
i will create a PR with this file as a first draft

**Comment by Soullivaneuh** [comment]
Personally :+1: and the doc path could be removed too as the documentation should be compiled and online,

But I already proposed something like that a year, and @rande declined the proposition: https://github.com/sonata-project/SonataAdminBundle/pull/3043#issuecomment-110725962

But I noticed an interesting comment of him:

> I think it is not the top priority as this need to be done on all sonata repositories ;)

With dev-kit we can do this no.

So @rande, what it your opinion for this? :-)

**Comment by greg0ire** [comment]
> IIRC, you told me this is specific to github

Looks like it is not : http://stackoverflow.com/questions/21832151/git-archive-export-ignore-ignoring-directories

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh IIRC, you told me this is specific to github… is there a way to get the same effect from a file in the .github directory ?

I think the export-ignore rule is specific to GitHub, not the `.gitattributes` file.

**Comment by greg0ire** [comment]
> I think the export-ignore rule is specific to GitHub, not the .gitattributes file.

Have you seen my link above ? Or is GH lagging again ?

> Also this will not save a lot of space, archives are zipped. So closing the issue is a good option

inodes matter too, and when searching for a file, not having tests show up would help. It will make fzf even faster so :+1:

**Comment by OskarStark** [comment]
> fzf

?

**Comment by Soullivaneuh** [comment]
> Have you seen my link above ? Or is GH lagging again ? I think it is specific to `git archive`

I saw it while writing my answer. Yes indeed. :+1:

**Comment by greg0ire** [comment]
> fzf

[fzf](https://github.com/junegunn/fzf) or any other fuzzy-matcher, indexation tool. Give this one a try though, it also integrates with the shell to replace Ctrl+R

**Comment by rande** [comment]
Actually, I learn a lot from codes (php, doc and test) when debugging projects inside vendor's folders. Removing, those files will not help people *working offline* (yes ...) or people jumping into the vendor's directory directly.

Also, this will not save that much space maybe a few KB over 50MB

**Comment by Soullivaneuh** [comment]
> Actually, I learn a lot from codes (php, doc and test) when debugging projects inside vendor's folders. Removing, those files will not help people working offline (yes ...) or people jumping into the vendor's directory directly.

@rande If they want the complete folder on some case, they can use `composer install --prefer-source`.

No tarball downloaded, so no ignored file. Export ignore is just for tarballs.

What do you think?

**Comment by rande** [comment]
Install with prefer-source can took up to 20 min, where prefer-dist is about a minute ... Also, not sure people are aware about this feature and might just think there is no documentation.

**Comment by rande** [comment]
also you should sum the size of those folders to really make sure it is worth it...

**Comment by Soullivaneuh** [comment]
> also you should sum the size of those folders to really make sure it is worth it...

Depends on projects I would say.

But there is also the @greg0ire argument: https://github.com/sonata-project/dev-kit/issues/129#issuecomment-223024154

I quite agree with him. Sometime using a fuzzy search on my IDE, I can fall on a class that looks like a real class but no, it's a fixture. Pretty frustrating. But yeah, it's a personal opinion. :wink:

**Comment by Soullivaneuh** [comment]
> and might just think there is no documentation.

About that, documentation is on rst format. This format is not nice to read.

Alternatively, we can exclude the `README.md` from export-ignore that provide a link to online documentation, or simply add a special file for it?

**Comment by rande** [comment]
Tools' constraints is out of the scope here! BTW I have open source licence for Sonata's contributors ;)

**Comment by greg0ire** [comment]
> also you should sum the size of those folders to really make sure it is worth it...

the number of files is a concern too (the number of inodes is finite)

**Comment by OskarStark** [comment]
> Tools' constraints is out of the scope here! BTW I have PHPStorem licence for Sonata's contributors ;)

sounds nice 👍 how can i get this ?
