### ISSUE TITLE
Use new syntax for GithubActions

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#1303]
### Todos

* [ ] Revert https://github.com/sonata-project/dev-kit/commit/7538e606fb9845977120b35c0da76f332196f01c and https://github.com/sonata-project/dev-kit/commit/071c6b78ca4f63d552c869bc6af7cb64edd1b91b
* [ ] Remove the usage of `set-env`

**Comment by VincentLanglet** [comment]
```
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
```
is removed, so I think we can close this.
