### ISSUE TITLE
Our GithubActions YAML Lint job succeed, but the one from FlintCI failed

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#1304]
This occurred while working on https://github.com/sonata-project/sandbox/pull/888

### Our
![CleanShot 2020-12-04 at 10 29 54](https://user-images.githubusercontent.com/995707/101146832-cb6f0680-361b-11eb-8103-7c509065dc07.png)

### FlintCI
![CleanShot 2020-12-04 at 10 30 05](https://user-images.githubusercontent.com/995707/101146849-d2961480-361b-11eb-9aa6-211d2be47501.png)

![CleanShot 2020-12-04 at 10 30 11](https://user-images.githubusercontent.com/995707/101146854-d45fd800-361b-11eb-86c8-8395c72dac68.png)

🤔

**Comment by core23** [comment]
IMHO we should drop FlintCI. I'm not sure if it is actively maintained by @soullivaneuh 

GitHub actions look like a better tool for most linting staff now.

**Comment by OskarStark** [comment]
Yes, but in this case our Job is green and does NOT report the error 🤔
