### ISSUE TITLE
Warning when running `bin/console release`

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#1354]
When I run `bin/console release` I get:
```
[WARNING] Some commands could not be registered:                                                                       
                                                                                                                        
In getClientService.php line 52:
  Class 'Redis' not found  
```

I think it's since https://github.com/sonata-project/dev-kit/pull/1133 @OskarStark 

Any way to fix this ?

**Comment by OskarStark** [comment]
So you have ext-redis installed? If not do so and try again. If this fixes the issue we need to add this to the composer.json

**Comment by VincentLanglet** [comment]
> So you have ext-redis installed? If not do so and try again. If this fixes the issue we need to add this to the composer.json

I would say that ext-redis is not installed. But what is it used for ?
I still can use the release command, I just have a warning ; can't we add a `if redis is installed` somewhere instead of requiring `ext-redis` in the composer.json ?

**Comment by OskarStark** [comment]
Its used for caching the github request internally in the github knp api client

**Comment by VincentLanglet** [comment]
> Its used for caching the github request internally in the github knp api client

So either we find a way to add the config https://github.com/sonata-project/dev-kit/blob/master/config/packages/github_api.yaml#L2-L16 only if redis is installed, either we require ext-redis indeed.

**Comment by OskarStark** [comment]
Lets require redis, you can checkout master branch and do `symfony ssh` and execute the command there
