### ISSUE TITLE
Run Static Analysis in multiple PHP versions

### ISSUE THREAD

**Issue by franmomu** [sonata-project/dev-kit#1361]
## Feature Request

Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6780/files#r561156091

After [adding support to php 8](https://github.com/sonata-project/dev-kit/pull/1355), the static analysis runs using php 8, this can cause some problems. The solution I've seen (https://github.com/doctrine/migrations/pull/1105#issuecomment-757331840) recommended is to create multiples configuration files.

**Comment by VincentLanglet** [comment]
I moved to dev-kit, since it's a general issue.

**Comment by VincentLanglet** [comment]
I think this is already hard to have all the build green for one version of PHP so this might be too hard to do.
Wdyt @jordisala1991 ?

**Comment by jordisala1991** [comment]
It is indeed hard. Probably easier for multiple php versions than for multiple symfony versions, but still hard. Is it really needed?

**Comment by VincentLanglet** [comment]
> Is it really needed?

Some method from php are returning false|string in 7 and string in 8.
So a false check is reported as useless by phpstan but still is useful for php 7.
I think it could help to detect things like this.

But indeed, same could be done for every libraries...

I would say we won't have time for this (and might not prioritize this) so it's ok to close it.
Feel free to re-open it if you disagree
