### ISSUE TITLE
Avoid superfluous parentheses (php-cs-fixer)

### ISSUE THREAD

**Issue by vladyslavstartsev** [sonata-project/dev-kit#1362]
During review in https://github.com/sonata-project/SonataAdminBundle/pull/6778#discussion_r561338984
@phansys came to idea to avoid superfluous parentheses in conditional branches.
The example of this  is
```php
if (!($collection instanceof Collection)) {
```
which should be fixed to
```php
if (!$collection instanceof Collection) {
```

**Comment by OskarStark** [comment]
Can you provide a PR against dev-kit repo? Search for .php_cs.dist.twig file

Thanks 

I am currently on a phone 📱

**Comment by vladyslavstartsev** [comment]
I haven't found the right rule here https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/index.rst

**Comment by phansys** [comment]
See [`no_unneeded_control_parentheses`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/control_structure/no_unneeded_control_parentheses.rst).

**Comment by VincentLanglet** [comment]
> See [`no_unneeded_control_parentheses`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/control_structure/no_unneeded_control_parentheses.rst).

Already provided by the Symfony ruleset.
The rules you look for is a feature-request: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4997.

So I'm closing the issue.
