### ISSUE TITLE
Sonata assets packages

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#137]
The idea of this issue is to extract the css/js logic from php repository to assets packages.

This will allow us to avoid committing vendor file like a pig. :pig_nose:

This concerns the following projects:
- https://github.com/sonata-project/SonataCoreBundle/tree/3.x/Resources/public/vendor
- https://github.com/sonata-project/SonataAdminBundle/tree/3.x/Resources/public/vendor

Maybe others?

We can extract the logic and user dependencies managers to include vendors.

We can publish those packages under npm and bower, the most used managers for assets.

Packages to be created:
- `sonata-project/core` (assets from core-bundle and dependencies)
- `sonata-project/admin` (assets from admin-bundle and dependencies)

Shall we create new repositories for that? I don't know.

~~Maybe yes because dependencies manager like npm does not has the same release logic (more restrictive).~~

-> I confused with rubygems. Have to check for npm.

Can this be done on a new minor? Yes if only we keep vendor file sync like a :pig: (Did I already say that?! :smile:) until next major.

@rande said to me this can be problematic for developer not using dependencies manager for assets.

This is true, and maybe we can find another solution for them. Any suggestion?

If this can't be possible, I still think we should stop committing vendor files like this.

After all, PHP user not using composer can't install our packages. :trollface:

If you have other ideas/suggestions, please comment! :+1:

**Comment by greg0ire** [comment]
Suggestion for dep manager less people : a git submodule? Ping @ju1ius

**Comment by Soullivaneuh** [comment]
> a git submodule?

Oh please, not that horrifying thing... x)

**Comment by greg0ire** [comment]
> Oh please, not that horrifying thing... x)

Well agreed it's horrifying, but maybe it can make an acceptable trade-off for people who can't use bower or npm… I mean, it's better than versioning deps, right ?

**Comment by Soullivaneuh** [comment]
> it's better than versioning deps, right ?

Less ugly maybe, better... :stuck_out_tongue:

**Comment by Soullivaneuh** [comment]
And gitsubmodule on what? All vendor dependencies? Do you want to re-create the `bin/vendors` for Symfony 2.0? :wink:

**Comment by greg0ire** [comment]
> And gitsubmodule on what? All vendor dependencies? Do you want to re-create the bin/vendors of Symfony 2.0? :wink:

An ugly repository with versioned deps :P

**Comment by Soullivaneuh** [comment]
More seriously, this is not acceptable.

Who is not using asset dependency manager today? I think it's time to drop ugly support IMHO.

**Comment by greg0ire** [comment]
> @rande said to me this can be problematic for developer not using dependencies manager for assets.
> This is true, and maybe we can find another solution for them. Any suggestion?

> Who is not using asset dependency manager today? I think it's time to drop ugly support IMHO.

I agree with you, but then make up your mind :trollface: do you want "another solution" or not ?

**Comment by Soullivaneuh** [comment]
> do you want "another solution" or not ?

Yes, a solution. Not moving ugly committed vendor on another GitHub repo. :stuck_out_tongue:

**Comment by greg0ire** [comment]
Also an alternative to git submodule could be a Composer package. Still very ugly, but easier to use, and people have Composer… at least I hope.

**Comment by greg0ire** [comment]
> Yes, a solution. Not moving ugly committed vendor on another GitHub repo. :stuck_out_tongue: 

Well then sorry, but I'm out of idea, I don't think there is something in between…

**Comment by Soullivaneuh** [comment]
> Also an alternative to git submodule could be a Composer package. Still very ugly, but easier to use, and people have Composer… at least I hope.

I was thinking about this one. But the problem is still the same: the vendor.

Not all asset vendor are under packagist (guess why! :stuck_out_tongue:) and if we can have all of them, we will be stuck.

**Comment by greg0ire** [comment]
> Not all asset vendor are under packagist (guess why! :stuck_out_tongue:) and if we can have all of them, we will be stuck.

I was thinking about one single ugly dependency, with vendors versioned… that way, crap would be isolated. IMO not using a package manager is not worth it, it will always lead to an ugly solution like this one.

**Comment by ju1ius** [comment]
Hi,
I find it hard to reason about vendor dependencies without talking about frontend dev/build process first.
IMO we should talk about that first and let a solution for vendors emerge.

But without thinking too much about it I can say I agree with @Soullivaneuh on this:
* git submodules are awkward to work with and are commonly rejected as a dependency management solution
* Having a separate composer package with versioned vendors is just moving the problem.

> this can be problematic for developer not using dependency managers for assets.

Given the current frontend dev landscape, this might very well be a non-issue. Anyway I think we shouldn't worry about this kind corner-case before there is an actual demand for it.

**Comment by Soullivaneuh** [comment]
Seems to already have a begining on sandbox dev: https://github.com/sonata-project/sandbox/blob/2cb7c2d5e18ed7098f0da76b335c9af9eb185002/bower.json

Have to investigate.

cc @rande

**Comment by Soullivaneuh** [comment]
Please see https://github.com/sonata-project/dev-kit/issues/398
