### ISSUE TITLE
Sandbox and Ecommerce

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#138]
Yes, I know. Those guys. :walking: 

What should we do with them?

For the sandbox, my plan is to setup 3 branches:
- `legacy`: The old and stable branch (actual `2.3`)
- `stable`: The current stable branch (actual `2.4-develop`)
- `master`: Unstable. To test next sonata packages dev-master versions.

At the end, I would like to have a Travis special job on each to run integration test with it.

The "problem" is the sandbox is requiring `ecommerce`. But what is this one?

I'll be honnest, I don't use it.

Should we tag it (https://github.com/sonata-project/ecommerce/issues/365) or use the same logic as sandbox?

Is that a bundle? Seems to be a group of bundles.

BTW, [sandbox package description](https://packagist.org/packages/sonata-project/sandbox) says:

> Sonata Project's sandbox (with ecommerce bundles)

Well this is confusing. Bundles inside the package? from ecommerce package?

Maybe should we deprecated `ecommerce` and move the bundle logic onto `sandbox` directly?

What do you think?

cc @rande (:heart:) and @sonata-project/contributors

**Comment by OskarStark** [comment]
Why do we have `develop`, `develop-deprecated` and `master` branch here?

https://github.com/sonata-project/ecommerce/branches

**Comment by greg0ire** [comment]
Looks like a monorepo that was never split :confused:

**Comment by OskarStark** [comment]
thats what i thought...

any idea how to handle it, without creating alot of separate Bundles?

**Comment by Soullivaneuh** [comment]
> any idea how to handle it, without creating alot of separate Bundles?

Yes, move all those bundle under sandox on a `Ecommerce` namespace and deprecate `ecommerce`.

Plus, `ecommerce` is requiring nearly same dependencies as sandbox (except SF full stack).

This make no sense to maintain both of them because they are quiet linked.

**Comment by rande** [comment]
The ecommerce part is a work in progress with no stable version. We are free to do what we want. 

The ecommerce part should not be deprecated as it represent a huge amount of work. I can find the time to make it work with symfony 2.8 and later if required. The ecommerce part also represents an important asset in the sonata suite and should not be lost.

**Comment by OskarStark** [comment]
> The ecommerce part also represents an important asset in the sonata suite and should not be lost.

i think thats not what we want ;-)

**Comment by Soullivaneuh** [comment]
> The ecommerce part should not be deprecated as it represent a huge amount of work.

I'm not really talking about deprecated this one but move the produced code on sandbox.

What do you think about this? Ecommerce looks like more a project than a package.

**Comment by rande** [comment]
There are in the same repository as the code has too much inter-dependencies (Quite hard to isolate code). The sandbox just include every thing ready to use. So the current layout make sense.

**Comment by Soullivaneuh** [comment]
> The sandbox just include every thing ready to use

What do you mean? Sandbox dev is including the whole ecommerce part: https://github.com/sonata-project/sandbox/blob/2cb7c2d5e18ed7098f0da76b335c9af9eb185002/composer.json#L63

**Comment by Soullivaneuh** [comment]
ping @rande

**Comment by Ximousse** [comment]
If I may add to the conversation: my team and I have successfully (and easily I'd say) used Sonata EcommerceBundle in production.
It would be strange to merge it to the SandBox which should only be an example of integration of all the Sonata bundles (config files and fixtures).

**Comment by Soullivaneuh** [comment]
> used Sonata EcommerceBundle 

SonataEcommerce, not bundle. This is a group of bundles, not one bundle.

> It would be strange to merge it to the SandBox which should only be an example of integration of all the Sonata bundles (config files and fixtures).

The problem is the ecommerce part "is" merged by requirement: https://github.com/sonata-project/dev-kit/issues/138#issuecomment-224614839

And if you take a look at both composer.json, they have a lot of common sonata requirements.

This is why I'd say that if the ecommerce is now required by the sandbox, as it's not a bundle itself, it should be directly merge onto it.

**Comment by Soullivaneuh** [comment]
@Ximousse Which branch of ecommerce did you use? Could you also give me the result of `composer show sonata-project/*` from your project?

**Comment by Ximousse** [comment]
The project is still running (10k users) but we haven't dared a composer update since january 2015.
We used "sonata-project/ecommerce" : `"sonata-project/ecommerce" : "dev-develop"`,
And the result of `composer show sonata-project/*`
```
sonata-project/admin-bundle              2.3.0               Symphony SonataAdminBundle
sonata-project/block-bundle              2.2.13              Symphony SonataBlockBundle
sonata-project/cache                     1.0.4               Cache library
sonata-project/cache-bundle              2.2.0               This bundle provides caching services
sonata-project/classification-bundle     2.2.2               Symphony SonataClassificationBundle
sonata-project/comment-bundle            dev-master 701040a  Symphony SonataCommentBundle
sonata-project/core-bundle               2.3.0               Symphony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master dba166c  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2               Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.0               Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.9               Symphony SonataEasyExtendsBundle
sonata-project/ecommerce                 dev-develop af77223 E-Commerce solution provided by Sonata
sonata-project/exporter                  1.3.4               Lightweight Exporter library
sonata-project/formatter-bundle          2.3.3               Symphony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2               Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.1               Symphony SonataIntlBundle
sonata-project/media-bundle              2.3.0               Symphony SonataMediaBundle
sonata-project/notification-bundle       2.3.0               Symphony SonataNotificationBundle
sonata-project/page-bundle               2.3.8               Symphony SonataPageBundle
sonata-project/seo-bundle                1.1.8               Symphony SonataSeoBundle
sonata-project/user-bundle               dev-master ebf6839  Symphony SonataUserBundle
```

**Comment by Soullivaneuh** [comment]
@Ximousse Ok so you are still on the legacy way.

We have to move on, this is what I propose for now:

1. Merge develop onto master
1. Remove all branch except master
1. Stabilize composer.json with legacy required bundle (e.g. remove `@dev`)
1. Make tests working
1. Integrate dev-kit
1. Release a 1.0.0 tag and a 1.x branch so user like you can rely on it for legacy project
1. Make the project compatible with new sonata bundles on master
1. Release a 2.0.0 tag and a 2.x branch. This will be the current stable, master will be for next major, as other project

With that, we will have some stabilization and I will be able to start my plan for sandbox properly.

Sounds right?

**Comment by rande** [comment]
@Ximousse can you contact me ? I would like to know the usage and feedback over this ecommerce solution

**Comment by Soullivaneuh** [comment]
After discussion with @rande, we can't merge develop onto master, too much divergences.

So I'll push a `0.0.1` tag on the actual `master` branch.

Then, the `develop` branch will become `master`, without any merge or rebase.

The rest of the process will not change.

**Comment by Soullivaneuh** [comment]
@Ximousse `develop` is now `1.x-dev`: https://packagist.org/packages/sonata-project/ecommerce#1.x-dev

A 1.0.0 tag will be pushed soon but this branch will not be maintained anymore.

**Comment by Ximousse** [comment]
Ok, thanks.

**Comment by jordisala1991** [comment]
Ecommerce was handled already, but sandbox was left behind, we start a modernization of it, and it is on this issue #391 . Closing this one because the other is more focused on the topic. Probably a better idea would be to just use the issues on Sandbox.

https://github.com/sonata-project/sandbox/issues/610
https://github.com/sonata-project/sandbox/issues/609
https://github.com/sonata-project/sandbox/issues/607
