### ISSUE TITLE
XML linter

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#139]
Set a linter for xml.

* https://github.com/sonata-project/SonataMediaBundle/pull/1043#issuecomment-224092851
* http://xmlsoft.org/xmllint.html (`apt-get install libxml2-utils`)
* https://packagist.org/packages/sclable/xml-lint

**Comment by Soullivaneuh** [comment]
I tested `sclable/xml-lint` on `media-bundle`:

```bash
sullivan@sweethome:~/projects/fork/sonata-project/SonataMediaBundle(3.x)$ xmllint .
Sclable Xml Lint version dev
progress: 
..............................       30/42  71.43%
............

42 files / 0.02 seconds done
```

It says nothing about spacing instead of linux `xmllint` command.

Maybe we can make a PR for that.

cc @OskarStark @greg0ire

**Comment by OskarStark** [comment]
> It says nothing about spacing instead of linux xmllint command.

because it is valid to have more or less whitespaces, but its the same with indention for example, it is valid, but the style isn't

**Comment by greg0ire** [comment]
> It says nothing about spacing instead of linux xmllint command.

Then we should use xmllint ?

**Comment by Soullivaneuh** [comment]
> Then we should use xmllint ?

Have to test. xmllint just output the linted xml AFAIK. I didn't see any option for "just lint".

BTW, could we install it on Travis without `apt-get` I would like to avoid `sudo` mode as possible.

**Comment by Soullivaneuh** [comment]
The tools works but did to much: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/135838346

* All blank line are removed
* Special characters for traduction are removed

The command: https://github.com/sonata-project/SonataAdminBundle/blob/498bae5818775b81c9a8a48b6f2eeb3e0d551a34/Makefile#L12-L13

If anybody has a suggestion, I'm hearing. :+1:

**Comment by Soullivaneuh** [comment]
I fixed special characters: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/135842286#L238

@sonata-project/contributors What do you think about the diff result?

**Comment by greg0ire** [comment]
It would be great not to loose the linebreaks, but I don't know how to do this properly…

**Comment by greg0ire** [comment]
This tool might do the job : http://www.kitebird.com/software/xmlformat/xmlformat.html#line-breaks-and-indentation

**Comment by Soullivaneuh** [comment]
> This tool might do the job : http://www.kitebird.com/software/xmlformat/xmlformat.html#line-breaks-and-indentation

This is to linebreak a line containing multiple tag. `xmllint` already does that. :/

**Comment by greg0ire** [comment]
> This is to linebreak a line containing multiple tag. xmllint already does that. :/

Yup. I tried to get it to linebreak the content of a tag, but no luck…

**Comment by greg0ire** [comment]
>  xmlformat never reformats element tags. In particular, it does not change whitespace betweeen attributes or which attribute values. This is true even for inline tags within line-wrapped block elements. 

:/

**Comment by Soullivaneuh** [comment]
I'll wait a bit before implement this one, but if no other solution is found I think I'll do it.

Except this issue, this tools will provide a real benefit for code standardization and reduce diff nightmare like the one that @OskarStark pointed out.

**Comment by Soullivaneuh** [comment]
BTW, `xmllint` is already installed on Travis, ready to run. Nothing to do here. :+1:

**Comment by Soullivaneuh** [comment]
Plus, `xmllint` seems to follow the W3C standard: https://www.w3.org/TR/REC-xml/

From: http://xmlsoft.org/XMLinfo.html

**Comment by OskarStark** [comment]
> @sonata-project/contributors What do you think about the diff result?

hmm, a bit weird in some cases but a big plus for consistency, but this loks weird:

```diff
-            <argument /> <!-- security.token_storage or security.context for Symfony <2.6 -->
-            <argument /> <!-- security.authorization_checker or security.context for Symfony <2.6 -->
-            <argument type="service" id="security.acl.provider" on-invalid="null" />
+            <argument/>
+            <!-- security.token_storage or security.context for Symfony <2.6 -->
+            <argument/>
+            <!-- security.authorization_checker or security.context for Symfony <2.6 -->
+            <argument type="service" id="security.acl.provider" on-invalid="null"/>
```

**Comment by Soullivaneuh** [comment]
@OskarStark Yes, this follow the line-break rule (no multiple tag on one line).

This seems to be applied on comments too.

This is not a big deal IMHO. At lest, comment could be move upside after that.

**Comment by OskarStark** [comment]
> This is not a big deal IMHO. At lest, comment could be move upside after that.

i totally agree with you!
