### ISSUE TITLE
Doc: FAQ for new version management

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#14]
As [said by Soullivaneuh](https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-213456514) we change the version management for (nearly) all projects of Sonata. This article should explain the most questions which will occur.

**What is the current stable version?**
The current stable version should be the latest tag. The current ``master`` branches will become the next major release (3.x)

**When will the 'new' stable version be released?**
Early may

**Going forward, how is versioning going to work?**
Have a look at https://github.com/sonata-project/SonataAdminBundle/issues/3053

**I am using 2.3.x. Are there BC breaks between the latest tag and the upcoming 3.x release?**
Yes, that's why we release a new major release.

**I am using 2.4@dev. Are there BC breaks between the latest master and the upcoming 3.x release?**
No, the latest ``master`` release will become the new 3.x release.

**Where are the BC breaks? (To clarify "Even if it's a new major, no BC breaking Pull Request will be merge until 3.0.0 release") Is there a clear list of the BC breaks?**
Sadly we haven't got one. We are working on a better system for that (see https://github.com/sonata-project/dev-kit/pull/1)

**Once 3.0.0 is released, will this be a stable branch? Will it be stable without BC breaks until 3.1.0 ( <4.0)?**
We will follow semver, so next BC break will be 4.0, and 4.0 will be the alias of master.

**Is there a roadmap with any suggestion of how long 3.0 is going to be the stable branch?**
No, because we are not a big company like SensioLabs or Mozilla fundation. We do not have full team working only on sonata-project. All people here are contributing in their free time (if they have some).

**I got the following composer error...**
```
sonata-project/translation-bundle dev-master requires sonata-project/admin-bundle ^2.3.0|~2.4@dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev, 2.3.x-dev].
```

We are working on every bundle to get them running with new versions. Please change your settings temporary to the following or require a stable release.
``
    "sonata-project/admin-bundle": "dev-master as 2.4.x-dev"
``

So no, it's impossible to promise a precise release date or a roadmap for this. A major could be out when it necessary. E.G. when we have a quite huge BC break modifications on master.

Please have a look at these issues as well:
- https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-213456514
- https://github.com/sonata-project/SonataAdminBundle/issues/3740

Thanks to @greg0ire and @Soullivaneuh for the short answers.

**Comment by core23** [comment]
Please have a look at this @sonata-project/contributors . Feel free to update this list, so @rande can write a short blog post.

**Comment by greg0ire** [comment]
"from them free times (if they have)" => "in their free time (if they have some)"

**Comment by Soullivaneuh** [comment]
I think it would be even beater to work on a generic FAQ for sonata projects in general, not only for this 3.x migration special case.

**Comment by core23** [comment]
We could do it afterwards, but first we should give the users some short information why they got errors when checking out the latest 2.4@dev versions.

**Comment by pachocho84** [comment]
Hello everyone, 
is sonata **media bundle** planned to be updated as well?
I cannot make it work with admin bundle 2.4 or 3.0.
Thank you!

**Comment by Soullivaneuh** [comment]
@pachocho84 Please next time open another issue on the appropriate repository.

> is sonata **media bundle** planned to be updated as well?

Yes, like all other bundles.

> I cannot make it work with admin bundle 2.4 or 3.0.

Use branch composer aliasing. See: https://github.com/sonata-project/SonataAdminBundle/issues/3731

If you still have an issue, search or open a new one about it on the **right** repository.

Regards.
