### ISSUE TITLE
New management system refactoring needed projects list

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#140]
Some project are still not integrated to dev-kit and not compatible with other bundles:
- [ ] `propel-admin-bundle`: https://github.com/sonata-project/SonataPropelAdminBundle/issues/62
- [ ] `sandbox`: #138 
- [x] `ecommerce`: #138

**Comment by jordisala1991** [comment]
Propel is not maintained anymore, and sandbox have its own issue #138 

Seems like a good idea to close this issue and continue there, feel free to reopen if it was not a great idea.
