### ISSUE TITLE
When Travis does not have test to do, Coveralls is stuck on waiting

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#141]
Example:

![image](https://cloud.githubusercontent.com/assets/1698357/15847089/76485612-2c83-11e6-9191-808a14bea782.png)

Possible tricks:
- Always run at least one test? (code coverage could decrease...)
- Push a fake code coverage (e.g. 100% because we don't care of coverage result if only the doc is changed)

**Comment by Soullivaneuh** [comment]
I opened an issue on Coveralls: https://github.com/lemurheavy/coveralls-public/issues/795

**Comment by Soullivaneuh** [comment]
This seems to be due to the `Required` rule for coveralls. If we remove it, this is okay.

Well, I think this should not be required...

**Comment by jordisala1991** [comment]
Coveralls is not required. We can close this one.
