### ISSUE TITLE
Drop support for sonata cache in favor for symfony/cache

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#1420]
Related to:
https://github.com/sonata-project/SonataCacheBundle/issues/279
https://github.com/sonata-project/cache/issues/49

#### composer why sonata-project/cache-bundle
```
sonata-project/sandbox      dev-master  requires  sonata-project/cache-bundle (^2.4)    
sonata-project/page-bundle  3.21.0      requires  sonata-project/cache-bundle (^2.4.1)  
```

#### composer why sonata-project/cache
```
sonata-project/block-bundle  3.22.0  requires  sonata-project/cache (^1.0 || ^2.0)    
sonata-project/cache-bundle  2.4.2   requires  sonata-project/cache (^1.0.3)          
sonata-project/page-bundle   3.21.0  requires  sonata-project/cache (^1.0.3 || ^2.0)  
```

In `sonata-project/block-bundle` only `Sonata\BlockBundle\Templating\Helper\BlockHelper` is using cache optionally. So it will be easy to add another cache system.

In `sonata-project/page-bundle` will be more work which should be done in some order:
- make `sonata-project/cache-bundle` opional
- add `symfony/cache` 
- deprecate `sonata/cache`

**Comment by core23** [comment]
Refs: https://github.com/sonata-project/SonataBlockBundle/issues/663

The problem is, that the sonata cache is not only a simple cache. It does some other things too.

**Comment by jordisala1991** [comment]
I think this can be closed, BlockBundle is already done, and only remains pageBundle, being tracked here: https://github.com/sonata-project/SonataPageBundle/issues/1096
