### ISSUE TITLE
Remove parameters keys from services defintions

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#149]
Something like this one: https://github.com/sonata-project/SonataPageBundle/blob/3.0.0/Resources/config/admin.xml#L6-L31

From [Symfony Best Practices](http://symfony.com/doc/current/best_practices/business-logic.html#service-no-class-parameter)

> This practice was wrongly adopted from third-party bundles. When Symfony introduced its service container, some developers used this technique to easily allow overriding services. However, overriding a service by just changing its class name is a very rare use case because, frequently, the new service has different constructor arguments.

I think `controller` and `translation_domain` parameters should be removed too. What do you think?

Removing those parameters are BC break. This have to be done on next major.

Concerned bundles list:
- [ ]

**Comment by greg0ire** [comment]
Like most of Symfony Best Practices, this is a best practice for the app bundle, not for a third-party bundle like ours, isn't it ?

**Comment by Soullivaneuh** [comment]
For most of the parts, yes, but not this one:

> This practice was wrongly adopted from third-party bundles.
> However, overriding a service by just changing its class name is a very rare use case because, frequently, the new service has different constructor arguments.

I think this is enough clear. :wink: 

BTW, I think if someone want to change the service class, he could make it with compiler passes.

Or maybe a child service?

**Comment by greg0ire** [comment]
Or defining a service with the same id

**Comment by Soullivaneuh** [comment]
> Or defining a service with the same id

We can do that?

**Comment by greg0ire** [comment]
> We can do that?

Not sure it is very well documented, or even a good practice, but yes, that's exactly how I overrode the sonata exporter in my project : 

```yml
    sonata.admin.exporter:
        class: My\Company\Admin\Export\Exporter
```
