### ISSUE TITLE
Use both phpunit/phpunit and simple-phpunit.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#1559]
See https://github.com/symfony/test-pack/pull/10
https://github.com/symfony/recipes/pull/906

Symfony still started to add phpunit/phpunit to the simple-phpunit recipe.

WDYT about adding the dependency @sonata-project/contributors ?
It will solve the need of the bootstrap file for static analysis: https://github.com/sonata-project/SonataAdminBundle/blob/master/phpstan.neon.dist#L7

**Comment by jordisala1991** [comment]
Solved
