### ISSUE TITLE
CS: modernize_types_casting fixer

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#157]
> Replaces intval, floatval, doubleval, strval, boolval functions calls with according type casting operator. (Risky fixer!)

Should investigate why this is risky before integrate it.

**Comment by ju1ius** [comment]
@Soullivaneuh What can be risky is that `intval` takes an optional `$base` parameter.
```php
(int)"0xFF" // => 0
intval("0xFF", 16) // => 255
```

**Comment by Soullivaneuh** [comment]
Then, the fixer should do nothing, should it?

Sullivan SENECHAL

**Comment by ju1ius** [comment]
I can't find the source code, do you know where it is ?

**Comment by Soullivaneuh** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/93b6694bada0fed87cf2668447f6e3b52197c074/src/Fixer/CastNotation/ModernizeTypesCastingFixer.php#L46

We don't override those function, so it's ok.

**Comment by jordisala1991** [comment]
This is part of Symfony risky and we are using it: https://github.com/sonata-project/dev-kit/blob/master/project/.php_cs.dist.twig#L20

Closing.
