### ISSUE TITLE
CS: php_unit_dedicate_assert fixer

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#158]
> PHPUnit assertions like "assertInternalType", "assertFileExists", should be used over "assertTrue". (Risky fixer!)

This is risky because those methods exist only under PHPUnit 5.x.

Add this fixer when PHPUnit 4 will not be used at all.

**Comment by ju1ius** [comment]
I don't think this kind of fixers shouldn't be used. They deeply change the semantics of the code behind a developer's back.
Remember that PHP-CS-Fixer fixes code **style** issues. It is not a linter.

**Comment by Soullivaneuh** [comment]
Improve obvious code logic is not a problem IMHO.

Sullivan SENECHAL

**Comment by jordisala1991** [comment]
Using this: https://github.com/sonata-project/dev-kit/blob/master/project/.php_cs.dist.twig#L38

Includes this fixed. Closing.
