### ISSUE TITLE
Travis: Keep use of PHPUnit 4 only

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#159]
At least, while we still have a maintained branch supporting PHP <5.6.

Why? Simply because we should not change deprecated method usage on new branch for testing right now.

Why? Simple: To avoid merge conflict nightmares between legacy and stable branch (related to #153).

What do you think?

**Comment by jordisala1991** [comment]
We are using phpunit 5 for now.

This issue is no longer relevant.
