### ISSUE TITLE
Issue with website SSL

### ISSUE THREAD

**Issue by Daniel-Yonkov** [sonata-project/dev-kit#1617]
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
```

## Subject
Cloudflare has disabled access to the documentation for the library due to SSL expiration

## Steps to reproduce
Visit [documentation page](https://sonata-project.org/)
## Expected results
To have access to the page
## Actual results
![image](https://user-images.githubusercontent.com/21025190/128633459-8b8effdb-2d58-4d94-8c2c-04af9b6b9326.png)

**Comment by core23** [comment]
We're working on this: https://github.com/sonata-project/dev-kit/issues/1613

**Comment by OskarStark** [comment]
Maybe @rande can fix this in the meantime

**Comment by rande** [comment]
this is fixed
