### ISSUE TITLE
Remove admin-bundle `master` branch

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#1622]
## Feature Request

We should remove the `master` branch as this branch pattern is outdated. 

After removing the branch, there is no more reason for a `branch-alias`.

**Comment by core23** [comment]
Done

**Comment by VincentLanglet** [comment]
What do we need to do
- For every project with a master branch, renaming the branch 2.x, 3.x, 4.x or 5.x depending on the stable branch.
- Updating the configuration on dev-kit

And that's all ? Am I missing something ? @sonata-project/contributors

**Comment by core23** [comment]
> What do we need to do
> 
> * For every project with a master branch, renaming the branch 2.x, 3.x, 4.x or 5.x depending on the stable branch.
> * Updating the configuration on dev-kit

That's all, from a technical perspective.

The only risk is that *someone* could be using the `master` branch on their local setup / `composer.json`. So we should communicate this change first.

**Comment by VincentLanglet** [comment]
Done

**Comment by VincentLanglet** [comment]
@core23 We still need to remove the branch alias in the composer.json I think

**Comment by VincentLanglet** [comment]
Done
