### ISSUE TITLE
CS: class_keyword_remove

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#166]
> Converts ::class keywords to FQCN strings.

To be added when https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1985 will be merged.

To be deployed **before** #154 and #165.

**Comment by Soullivaneuh** [comment]
@dbu I found some `::class` keywords on phpcr-admin master branch:

```bash
sullivan@sweethome:~/projects/fork/sonata-project/SonataDoctrinePhpcrAdminBundle(master)$ grep -R '::class' .
./Tests/Guesser/FilterTypeGuesserTest.php:                'field_type' => TextType::class,
./Guesser/FilterTypeGuesser.php:            'field_type' => TextType::class,
./Guesser/FilterTypeGuesser.php:            $options['field_type'] = DocumentType::class;
./Guesser/FilterTypeGuesser.php:                $options['field_type'] = BooleanType::class;
./Guesser/FilterTypeGuesser.php:                $options['field_type'] = NumberType::class;
./Guesser/FilterTypeGuesser.php:                $options['field_type'] = TextType::class;
./Guesser/TypeGuesser.php:            return new TypeGuess(TextType::class, array(), Guess::LOW_CONFIDENCE);
./Guesser/TypeGuesser.php:        return new TypeGuess(TextType::class, array(), Guess::LOW_CONFIDENCE);
./Filter/CallbackFilter.php:            'field_type' => TextType::class,
./Filter/NodeNameFilter.php:        return array(ChoiceType::class, array(
./Filter/StringFilter.php:        return array(ChoiceType::class, array(
```

This would be converted to string FQCN.

The goal is to avoid `::class` keyword mass changing on new branch supporting php 5.5+ to avoid merge conflicts nightmares, like short arrays.

This would be obviously changed to `::class` application fixer when all still maintained branches support PHP 5.5+ only. :wink:

**Comment by dbu** [comment]
i would prefer if we can leave them. we don't plan to develop any kind
of features on the old versions of the phpcr-admin anymore, only
important bugfixes. so i expect the potential for merge conflicts to be
quite small.

**Comment by Soullivaneuh** [comment]
> i would prefer if we can leave them.

Sadly, form dev-kit, it's a global configuration.

> we don't plan to develop any kind
of features on the old versions of the phpcr-admin anymore, only
important bugfixes. 

Maybe not the class name, but maybe something on the same line can be modified. :wink: 

> so i expect the potential for merge conflicts to be
quite small.

Still a potential. Maybe small for your project, but huge for projects like admin-bundle...

To be clear, I prefer the `::class` too of course. But it would avoid lot of loosing time to keep the old way until we drop branch maintaining for ones supporting PHP <5.5.

Also note I'm planning to work on a `class_keyword` fixer too that will automatically replace old FQCN by the `::class` keyword to do conversion with ease.

**Comment by dbu** [comment]
ah, ok. well, i can live with it.

appreciate the effort you put into maintaining the sonata suite!

**Comment by Soullivaneuh** [comment]
Thank @dbu! :-)

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors and other: I need your support on https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1985 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1975 to get the fixer accepted.

Otherwise, we will have to find another manual solution that would be painful for contributors.

So let's :+1: this please! :wink:

**Comment by jordisala1991** [comment]
We dont need this anymore, because both stable and master supports ::class notation.

Closing
