### ISSUE TITLE
Convention for nested template paths

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#167]
When adding a new template in a subdirectory, for example:
`admin-bundle/Resources/views/CRUD/subdir/name.html.twig`

1. Should `subdir` be lowercase or titlecase ?
2. When referencing it, which of the following forms should be used:
  1. `SonataAdminBundle:CRUD/subdir:name.html.twig`
  2. `SonataAdminBundle:CRUD:subdir/name.html.twig`

Symfony [best practice for n°1](http://symfony.com/doc/current/best_practices/templates.html#template-locations): 
> Use lowercased snake_case for directory and template names

Symfony [convention for n°2](http://symfony.com/doc/current/book/templating.html#referencing-templates-in-a-bundle):

> Symfony uses a **bundle:directory:filename** string syntax for templates that live inside a bundle.

So if we were to follow SF conventions, we should use: `CamelCasedBundle:dir/sub_dir:file_name.html.twig`.

However, sonata already uses titlecase for the first-level directory...

**Comment by greg0ire** [comment]
I would say Titlecase

**Comment by ju1ius** [comment]
@greg0ire What about n°2 ?

**Comment by greg0ire** [comment]
I vote ii

**Comment by greg0ire** [comment]
Please vote on my answers @sonata-project/contributors

**Comment by Soullivaneuh** [comment]
Can't see the issue (I am on email with my mobile), but for convention, we
should check first how Symfony does and if anything is said about that.

Sullivan SENECHAL

**Comment by ju1ius** [comment]
From the [Template locations best pratctices](http://symfony.com/doc/current/best_practices/templates.html#template-locations):

For n° 1:
> Use lowercased snake_case for directory and template names

Thing is, sonata already uses titlecase for the first-level directory...

For n°2, there doesn't seem to be a recommendation.

**Comment by ju1ius** [comment]
From [the docs](http://symfony.com/doc/current/book/templating.html#referencing-templates-in-a-bundle):
> Symfony uses a **bundle:directory:filename** string syntax for templates that live inside a bundle.

So I guess that answers to question 2: we should use `SonataAdminBundle:CRUD/subdir:name.html.twig`

**Comment by Soullivaneuh** [comment]
Same as @greg0ire Titlecase and `SonataAdminBundle:CRUD:subdir/name.html.twig`.

For the first, I would prefer `snake_case`, but I don't see any way to change without BC break nightmares.

So I don't think it will worth it.

We could change it later if we find a smooth solution.

**Comment by ju1ius** [comment]
@greg0ire @Soullivaneuh @OskarStark Turns out the convention has already been chosen... :sweat_smile: 

The [`ModelAutocompleteType`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Type/ModelAutocompleteType.php#L147) class calls its template this way: `SonataAdminBundle:Form/Type:sonata_type_model_autocomplete.html.twig`.

So `PascalCasedBundleName:PascalCased/Directory:snake_cased_filename.html.twig` it is !
