### ISSUE TITLE
Symfony 6 Support

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#1675]
### Active Bundles
- [x] [SonataAdminBundle](https://github.com/sonata-project/SonataAdminBundle/pull/7555)
- [x] [SonataDoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/699)
- [x] [SonataDoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1562)
- [x] [SonataBlockBundle](https://github.com/sonata-project/SonataBlockBundle/pull/942)
- [x] SonataSeoBundle
- [x] [SonataTranslationBundle](https://github.com/sonata-project/SonataTranslationBundle/pull/572)
- [x] [SonataClassificationBundle](https://github.com/sonata-project/SonataClassificationBundle/pull/778)
- [x] [SonataMediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/2222)
- [x] [exporter](https://github.com/sonata-project/exporter/pull/517)
- [x] [form-extensions](https://github.com/sonata-project/form-extensions/pull/258)
- [x] [twig-extensions](https://github.com/sonata-project/twig-extensions/pull/253)
- [x] [EntityAuditBundle](https://github.com/sonata-project/EntityAuditBundle/pull/439)
- [x] SonataIntlBundle
- [x] SonataUserBundle
- [x] SonataFormatterBundle

### Bundles that are used as dependencies
- [x] [SonataCacheBundle](https://github.com/sonata-project/SonataCacheBundle/pull/385)
- [x] [SonataDatagridBundle](https://github.com/sonata-project/SonataDatagridBundle/pull/367)

### Bundles that do not support SF 5
- SonataPageBundle

### Bundles with only Symfony dependencies on require-dev section
- [x] [sonata-doctrine-extensions](https://github.com/sonata-project/sonata-doctrine-extensions/pull/376)
- [x] [cache](https://github.com/sonata-project/cache/pull/251)
- [x] [GoogleAuthenticator](https://github.com/sonata-project/GoogleAuthenticator/pull/333)

# Final cleanup

The final step is cleanup composer.json and make sure all builds pass without requiring unstable dependencies

- [x] SonataAdminBundle
- [x] SonataDoctrineMongoDBAdminBundle
- [x] SonataDoctrineORMAdminBundle
- [x] SonataSeoBundle
- [x] SonataTranslationBundle
- [x] SonataClassificationBundle
- [x] SonataMediaBundle
- [x] [SonataUserBundle](https://github.com/sonata-project/SonataUserBundle/pull/1495)
- [x] SonataFormatterBundle
- [x] SonataBlockBundle
- [x] exporter
- [x] form-extensions
- [x] twig-extensions
- [x] EntityAuditBundle
- [x] SonataIntlBundle
- [x] SonataDatagridBundle

**Comment by wbloszyk** [comment]
Can you add `Support for Symfony 5` section too?

**Comment by jordisala1991** [comment]
I think there was an issue about sf 5.

**Comment by jordisala1991** [comment]
We are stuck because of panther... 

Persistence bundles require it
It does not have support: https://github.com/symfony/panther/pull/509
It cant be easily added because it requires changes on the main Symfony: https://github.com/symfony/symfony/issues/43021#issuecomment-955764741


Options:
1. We do nothing and wait (we will not be day 1 compatible with Symfony 6, which would have been a huge success, and a selling point)
2. We try to remove symfony/panther from 6.0 build until it gets fixed (not sure if it can be done)
3. We get rid of Symfony Panther (not a good idea IMO, it is useful to test with JS)

What should we do? @sonata-project/contributors

**Comment by jordisala1991** [comment]
The final step is cleanup composer.json and make sure all builds pass without requiring unstable dependencies. I have started with exporter and form-extensions, any help welcome @sonata-project/contributors

**Comment by jordisala1991** [comment]
Symfony Security Acl is blocking the update to Symfony 6 , we might take a look and help them with that, otherwise our users cant update. https://github.com/symfony/security-acl/issues/99

**Comment by VincentLanglet** [comment]
> Symfony Security Acl is blocking the update to Symfony 6 , we might take a look and help them with that, otherwise our users cant update. [symfony/security-acl#99](https://github.com/symfony/security-acl/issues/99)

Will be solved by https://github.com/symfony/security-acl/pull/100 :)

**Comment by jordisala1991** [comment]
We are still blocked by the symfony acl :(

**Comment by jordisala1991** [comment]
We are unblocked, tomorrow will try to check and fix SonataAdminBundle build.

We need to check all builds and remove the usage of unstable dependencies.

**Comment by jordisala1991** [comment]
So all bundles are cleaned up, we just need a dev-kit PR.
