### ISSUE TITLE
CS: psr4 fixer

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#169]
> Class names should match the file name. (Risky fixer!)

This may break the code if changed, except for tests.

@sonata-project/contributors Should we care? Any suggestion if yes?

**Comment by OskarStark** [comment]
it would be interesting to have a check on all bundles initially.

IMO we don't need this check on all PR's

**Comment by Soullivaneuh** [comment]
> it would be interesting to have a check on all bundles initially.

:+1: 

> IMO we don't need this check on all PR's

What do you mean?

**Comment by Soullivaneuh** [comment]
@OskarStark This is risky beacause changing namespace will broke the code because the imports would not be the same.

Once it's fixed, this fixer will be here only for a preventive way.

**Comment by jordisala1991** [comment]
This belongs to Symfony risky, and we are using it: https://github.com/sonata-project/dev-kit/blob/master/project/.php_cs.dist.twig#L20

Closing.
