### ISSUE TITLE
[question] Test utilities

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#17]
Is this the right place to submit things like general purpose assertion classes ?
For example, will the bundles be able to do this:
```php
namespace SonataAdminBundle\Tests\Foo;

use Sonata\DevKit\Tests\Assert\BarAssert;

class FooTest extends PHPUnit_Framework_TestCase {
  public function testThatFooIsBar ($foo, $bar) {
    BarAssert::assertFooEqualsBar($foo, $bar);
  }
}
```

**Comment by greg0ire** [comment]
Correct me if I'm wrong @Soullivaneuh , but I feel this is more a template than something we will require in the bundles. BTW, how do you plan to synchronize repositories with this one?
@ju1ius general purpose assertion might go in the core bundle. Or maybe in a separate package. What assertions are you thinking about exactly, if you don't mind my asking?

**Comment by ju1ius** [comment]
> What assertions are you thinking about exactly?

@greg0ire [this one](https://github.com/ju1ius/SonataAdminBundle/blob/js-refactoring/Tests/HTMLAssert.php), in order to fix [this issue](https://github.com/sonata-project/SonataAdminBundle/issues/3646).

I think it could be useful for every bundle that unit tests twig templates.

**Comment by greg0ire** [comment]
From most pragmatic to most beautiful : 

- in the core bundle
- in a separate package
- in twig itself. After all, twig should provide a way to test itself. You might want to check if it does not already.

**Comment by ju1ius** [comment]
> You might want to check if it does not already.
@greg0ire OMG! didn't even think about that!

**Comment by ju1ius** [comment]
@greg0ire After a quick search, didn't find anything. Also this kind of utilities might be too specific for twig  itself since it can output anything, not just HTML... 

I'll check the TwigBundle & Bridge, but I doubt I'll be successful

**Comment by greg0ire** [comment]
There might be [something](https://github.com/twigphp/Twig/blob/master/lib/Twig/Test/IntegrationTestCase.php), but it does not seem documented and I don't understand how to use it nor whether it would help in your case. Maybe we should start by filing an issue in Twig's issue tracker or asking a question on SO.

**Comment by ju1ius** [comment]
To me it seems that this would better belong to phpunit itself, since they already have assertions that deal with XML.

**Comment by Soullivaneuh** [comment]
The best would be to write abstract test classes that can be reused (e.g. AbstractBlockService test) with common test methods.

See example here: https://github.com/Soullivaneuh/IsoCodesValidator/blob/cab2051f70fdee0198e475a16f5318c87cd9246f/tests/Constraints/AbstractConstraintValidatorTest.php

But this should be put on the concerned project/bundle or, like @greg0ire says, on a separate package if it's a **full** generic test. But in this case, it might worth to make a PR directly on phpunit project. :stuck_out_tongue: 

> Correct me if I'm wrong @Soullivaneuh , but I feel this is more a template than something we will require in the bundles.

~~bundles~~ -> projects. But yes. :-)

> BTW, how do you plan to synchronize repositories with this one?

Not fully decided about how. I would like to try to write a console client that would use the Github API to synchronize files. And twig to generate them before.

Closing this issue as not related.
