### ISSUE TITLE
Symfony 5 Support

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#1712]
I'm tring to run as much sonata bundles as it is possible in Sonata 4 with Symfony 5.4.

This is list of required to update bundles:
Active bundles:
- [ ] SonataFormatterBundle
- [ ] SonataPageBunde
- [ ] SonataNewsBundle (I want be a maintainer for it)

Other bundles - not required:
- [ ] SonataClassificationMediaBundle (abandoned)
- [ ] SonataUserBundle - we should abandon it
- [ ] SonataTimelineBundle (abandoned)

**Comment by VincentLanglet** [comment]
I think we can close this in favor of https://github.com/sonata-project/dev-kit/issues/1715
