### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#1714]
## History
The latest notice about pager:
https://github.com/sonata-project/SonataDatagridBundle/blob/2.2.0/Pager/PagerInterface.php
https://github.com/sonata-project/SonataCoreBundle/blob/2.2.6/Model/PageableManagerInterface.php

Later `PageableManagerInterface` was moved into:
https://github.com/sonata-project/SonataDatagridBundle/blob/3.0.0/src/Pager/PageableInterface.php

In meanwhile CoreBundle was splited and `PageableManagerInterface` was aliased to doctrine-extensions.
https://github.com/sonata-project/sonata-doctrine-extensions/blob/1.x/src/Model/PageableManagerInterface.php

Now we should use `PageableInterface` and `PagerInterface` from DatagridBundle but it was abandon some times ago.

## Pager in AdminBundle
In AdminBundle we have (it was 2.0):
- `PagerInterface` 
- `abstract Pager` and `SimplyPager`
- `ProxyQueryInterface` and `ProxyQuery`

In persistance bundles we also have:
- `Pager`
- `ProxyQueryInterface` and `ProxyQuery`

## Future of feature

In some bundles like `NewsBundle`, `MediaBundle`, `ClassificationBundle` which provide manager(s) with pager (probably whole managers) we should replace Pager from DatagridBundle by something new. Usinig AdminBundle in this case will add unnesessery requirement, also copy this functionality from AdminBundle and persistants bundle to each bundle is bad idea.

IMHO we should:
- move Pagers (and structure) from AdminBundle and persistans bundle to `sonata-project/doctrine-extensions`
- add `ManagerInterface::getPager` 

pros:
- easy way to create paginator - just create manager and call `getPager` or we can even provide `SimpleManager::getPager($class, ...)`
- split functionality to correct package/bundles
- AdminBundle and persistanse bundle will be simpler

**Comment by wbloszyk** [comment]
@VincentLanglet It is possible to do it and remove (deprecate) current Pager form AdminBundle?
@sonata-project/contributors WDYT?

**Comment by jordisala1991** [comment]
Pager on Media bundle and classification is not needed.

**Comment by core23** [comment]
> * move Pagers (and structure) from AdminBundle and persistans bundle to `sonata-project/doctrine-extensions`

👍 

> * add `ManagerInterface::getPager`

👎  We should remove the `PageableInterface` and it the method to the domain specific manager interfaces (e.g. `PostManagerInterface::getPager`). Not all `ManagerInterface` instances should be pageable. Some of them are very basic and don't need this functionality.

**Comment by wbloszyk** [comment]
> Changing current system (that works for Admin and persistence) just for news bundle, I dont see the benefit Tbh (abandoned bundle that nobody uses)

Not only NewsBunle: https://github.com/sonata-project/SonataClassificationBundle/blob/4.x/src/Model/CategoryManagerInterface.php#L41

It is not changing but move current system to more appropriate place. Simmilar we can move some form types to form-extensions (like `ModelListType) and just extends it in AdminBundle. 

AdminBundle should not be monolit, we should split some functionality to make it reusable.

**Comment by VincentLanglet** [comment]
> > Changing current system (that works for Admin and persistence) just for news bundle, I dont see the benefit Tbh (abandoned bundle that nobody uses)
> 
> Not only NewsBunle: https://github.com/sonata-project/SonataClassificationBundle/blob/4.x/src/Model/CategoryManagerInterface.php#L41

And this is not used at all https://github.com/sonata-project/SonataClassificationBundle/search?q=getSubCategoriesPager

For instance the Pager usage in the NewsBundle is
https://github.com/sonata-project/SonataNewsBundle/blob/f98fad6ab30398adce8088ff300a37c7dbae616d/src/Controller/Api/PostController.php#L96


> Pager on Media bundle and classification is not needed.
 
IMHO this is just the truth. All the Pager related stuff were related to the API.

We should just
- Deprecate the API
- Deprecate all the method getPager
- Deprecate all the PageableManager extension and usage

For the same reason I would say we don't need https://github.com/sonata-project/SonataPageBundle/pull/1369 since all the `getPager` method are deprecated.

**Comment by jordisala1991** [comment]
When we deprecate all the api this wont be needed, shall we close?

**Comment by VincentLanglet** [comment]
As long as we deprecate the API, all the method getPager and all the PageableManager extension, yes.
