### ISSUE TITLE
Release train

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#1715]
There are still some project that do not have a stable version which supports sonata admin 4 or symfony 5/6.

This is an ordered list with all open steps for our main projects.

- [x] Next major: `SonataSeoBundle`
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release
- [x] Next major: `SonataClassificationBundle`
  - [x] Bump psalm/phpstan level
  - [x] Bump php version
  - [x] Remove deprecations
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release
- [x] Next major: `SonataMediaBundle`
  - [x] Bump psalm/phpstan level
  - [x] Bump php version
  - [x] Remove deprecations
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release
- [x] Next major: `SonataTranslationBundle`
  - [x] Add `symfony` 5/6 support
  - [x] Bump psalm/phpstan level
  - [x] Bump php version
  - [x] Remove deprecations
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release
- [x] Next major: `SonataUserBundle`
  - [x] Drop `FOSUserBundle`
  - [x] Add `symfony` 5/6 support
  - [x] Bump psalm/phpstan level
  - [x] Bump php version
  - [x] Remove deprecations
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release
- [x] Next major: `SonataFormatterBundle`
  - [x] Depends on `SonataMediaBundle` v4 (needs admin v4 support)
  - [x] Add `symfony` 5/6 support
  - [x] Bump psalm/phpstan level
  - [x] Bump php version
  - [x] Remove deprecations
  - [x] Add formatter plugins (e.g. CKEditor, Markdown, ...)
  - [x] Change services declaration from xml to php
  - [x] Create pre-release
  - [x] Update documentation
  - [x] Create release

Referencing issues:
- https://github.com/sonata-project/dev-kit/issues/1712
- https://github.com/sonata-project/dev-kit/issues/1465
- https://github.com/sonata-project/dev-kit/issues/785
- https://github.com/sonata-project/dev-kit/issues/1420

Continues https://github.com/sonata-project/dev-kit/issues/216

**Comment by VincentLanglet** [comment]
> Yes, but this is an other topic to me. The bundle mentioned above are the sonata core bundle which are used for among each other.

That's exactly why I talked about the UserBundle. I consider it as one of our main bundle so it's not off topic
It's currently used a lot more than SonataPageBundle or SonataClassificationBundle for instance.

**Comment by core23** [comment]
Feel free to add missing points

**Comment by VincentLanglet** [comment]
@core23 @jordisala1991 Did you have time to test SonataMedia and SonataClassification dev branches ?
What's missing for a stable release ?

**Comment by jordisala1991** [comment]
I didnt had time, and we first need to release classification. IMO we should release it and if someone reports anything we can do the bugfixes...

**Comment by core23** [comment]
> @core23 @jordisala1991 Did you have time to test SonataMedia and SonataClassification dev branches ?

Not yet. Maybe I can find some time next week.

**Comment by VincentLanglet** [comment]
> I didnt had time, and we first need to release classification. IMO we should release it and if someone reports anything we can do the bugfixes...

I agree. Let's release Classification then

**Comment by VincentLanglet** [comment]
I moved page bundle to https://github.com/sonata-project/dev-kit/issues/2009 in order to have only one issue
