### ISSUE TITLE
New label for squash merge

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#172]
I was thinking if would be great to avoid forgetting squash merging and rewriting the commit message in the process when relevant. IMO, PRs with one commit and a poor commit message could be tagged with a `Needs : squash merge` label, and the contributor tagging with this could provide a better commit message.

I talked about that with @Soullivaneuh , and he told me he was thinking of splitting the `RTM` label into two other labels, one for squash merge, the other for classical merge.

What do you think @sonata-project/contributors ?

**Comment by Soullivaneuh** [comment]
> I talked about that with @Soullivaneuh , and he told me he was thinking of splitting the RTM label into two other labels, one for squash merge, the other for classical merge.

Something like this:

* `RTM (merge)` for a "classic" merge
* `RTM (squash)` for a merge by squash

BTW, this would help SonataCI to know what to do when automatic merge will be added (#81)

**Comment by greg0ire** [comment]
SonataCI won't be able to change the commit message though, will it?

**Comment by Soullivaneuh** [comment]
It technically cans, but we have to feed it with what to put on the commit message, this is the hard way.

Otherwise, it will just take the first commit message and squash them.

Actual working for SonataCI PR merges:

* If only one commit -> Merge by squash
* If multiple commit with exactly same message -> Merge by squash (take the first one)
* If multiple and different commits -> Classic merge

**Comment by Soullivaneuh** [comment]
What I currently expect with the RTM label: Put it only if the PR **can** be merge as is, including commits message.

So if a commit message is wrong or commits should be squashed, the RTM label should not be added.

**Comment by VincentLanglet** [comment]
I may be wrong but the merge is (now ?) always a squash merge
![image](https://user-images.githubusercontent.com/9052536/90311608-f0b8f700-defc-11ea-91f2-3762146c99f6.png)

So we can't forget to do it, isn't it ? @greg0ire

**Comment by greg0ire** [comment]
… for me it's always Rebase and merge, that's weird.

**Comment by VincentLanglet** [comment]
Oh weird indeed.

I always made squash and merge, thinking it was the Sonata standard.

I just discovered I could do a rebase and merge too, but that my second choice.
That's why I never understood when you explained on PR that you could do a squash and merge but you have to *not forget*.

**Comment by OskarStark** [comment]
It took the last used method as the default selected one next time

**Comment by jordisala1991** [comment]
I dont think we need a new label and more workflow process. We are normally doing great.
