### ISSUE TITLE
Travis: Composer parallel installs with hirak/prestissimo plugin

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#173]
https://packagist.org/packages/hirak/prestissimo

Try this plugin on a "big" project to see if it worth it.

Ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1995

**Comment by keradus** [comment]
just be sure to use at least ^0.2 if you use Composer ^1

**Comment by Soullivaneuh** [comment]
> just be sure to use at least ^0.2 if you use Composer ^1

Thanks for the tip, we will use the latest one! :wink:

**Comment by Soullivaneuh** [comment]
After a `composer clearcache` and deleted vendor on admin-bundle, I tried a `composer install`:

* Without the plugin: `1m17s`
* With the plugin: `0m29s`

This is indeed a great addition to have.

**Comment by keradus** [comment]
You see, I know what am I doing ;)
Be aware that the boos is not that big when the deps is already cached (but then, you will have prestissimo cached as well, right? ;) )

**Comment by Soullivaneuh** [comment]
> You see, I know what am I doing ;)

If you are talking about adding phpunit as a project dev, sorry but I still disagree. :stuck_out_tongue: 

> Be aware that the boos is not that big when the deps is already cached (but then, you will have prestissimo cached as well, right? ;) )

Yes we are caching composer files: https://github.com/sonata-project/dev-kit/blob/a4574f4ff3428bdd89ecf1c2f4f0190227abb250/.travis.yml#L13

But cache has a timeout, so...

**Comment by jordisala1991** [comment]
I cant find where, but I know I already tested it on travis (and @greg0ire / you saw it) and we didnt gain any performance, due to the cache @keradus mentioned, and the fact that we are doing another command to install prestissimo in the first place.

Closing for now, feel free to reopen if this needs to be checked again.
