### ISSUE TITLE
Move HHVM out of allowed failures

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#176]
Refs:
- https://github.com/symfony/symfony/pull/18947/files
- https://docs.travis-ci.com/user/languages/php#HHVM-versions

I think we can start by LTS versions: http://hhvm.com/blog/6083/hhvm-long-term-support

**Comment by Soullivaneuh** [comment]
Job sample: https://travis-ci.org/sonata-project/exporter/builds/138338243

Related diff: https://github.com/sonata-project/exporter/compare/1.x...travis-hhvm

**Comment by jordisala1991** [comment]
We ended up dropping hhvm here: https://github.com/sonata-project/dev-kit/pull/333

Closing because this is no longer relevant.
