### ISSUE TITLE
Don't load test classes in production

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#179]
Today all classes are loaded by the autoloader. Instead we should use `autoload` for sources and `autoload-dev` for test classes. See: https://getcomposer.org/doc/04-schema.md#autoload-dev

Maybe we should adopt the `src` and `tests` folder structure?

- [x] GoogleAuthenticator
- [x] SonataBlockBundle
- [x] SonataCoreBundle
- [x] SonataAdminBundle
- [x] SonataAdminSearchBundle
- [x] SonataCacheBundle
- [x] SonataClassificationBundle
- [x] SonataCommentBundle
- [x] SonataDashboardBundle
- [x] SonataDatagridBundle
- [x] SonataDoctrineMongoDBAdminBundle
- [x] SonataDoctrineORMAdminBundle
- [x] SonataDoctrinePhpcrAdminBundle
- [x] SonataEasyExtendsBundle
- [x] SonataFormatterBundle
- [x] SonataIntlBundle
- [x] SonataMediaBundle
- [x] SonataNewsBundle
- [x] SonataNotificationBundle
- [x] SonataPageBundle
- [x] SonataPropelAdminBundle
- [x] SonataSeoBundle
- [x] SonataTimelineBundle
- [x] SonataTranslationBundle
- [x] SonataUserBundle
- [x] cache
- [x] ecommerce
- [x] exporter
- [x] sonata-doctrine-extensions

**Comment by greg0ire** [comment]
This is not the sf recommend (or rather, official) way for bundles, but I already tried it and it works just fine. One could go even one step further and separate fw-independant classes from sf integration classes

**Comment by Soullivaneuh** [comment]
@core23 Both idea are great but BC breaks.

Let's focus first on code cleanup, coverage increase and old version support dropping first. :wink:

**Comment by Soullivaneuh** [comment]
Another idea: Simplify GitHub repository names.

`sonata-project/SonataAdminBundle` -> `sonata-project/admin-bundle`.

Advantages:

* Short names
* Sames names as Packagist, easier to retrieve IMHO.

**Comment by greg0ire** [comment]
> @core23 Both idea are great but BC breaks.

How so exactly ?

**Comment by Soullivaneuh** [comment]
For the autoload-dev, some classes are used between our projects. We have to be sure they are not before doing that.

Plus, some people might use the autoloaded class. They should not, but...

For `src` and `tests` folder, this is not really a BC break except for people loading manually some classes, but theyr should not.

But I'm afraid of the possible merge conflicts, we have to test on one repo and do it carefully if we want to apply it.

**Comment by greg0ire** [comment]
> For src and tests folder, this is not really a BC break except for people loading manually some classes, but theyr should not.

Maybe we could start a BC PR with just that (tests in `autoload` instead of `autoload-dev`) ?

**Comment by Soullivaneuh** [comment]
I think I will try it manually before to check merge results.

**Comment by core23** [comment]
> For the autoload-dev, some classes are used between our projects. We have to be sure they are not before doing that.

That's not completly true. Only `*TestCase`s should be used accross bundles. Simple tests under the `Tests` folder should only be used inside their repository.

> Plus, some people might use the autoloaded class. They should not, but...

Sorry, but that's *their problem* and we should deprecate this behavior. No one should extends tests, except it's a test case.

**Comment by Soullivaneuh** [comment]
> That's not completly true. Only `*TestCase`s should be used accross bundles. Simple tests under the `Tests` folder should only be used inside their repository.

Yes, in Theory, that beautiful country. But this not **currently** the case on internal bundle.

> Sorry, but that's *their problem* and we should deprecate this behavior. No one should extends tests, except it's a test case.

I agree, but this is not a reason to move this without any warning.

For exporter and cache, we did that on a new minor but with a tiny upgrade note. cc @greg0ire

**Comment by core23** [comment]
Maybe we can resolve this by throwing a deprecation warning in the test classes?

```php
    public function __construct() {
        if (get_class($this) != __CLASS__) {
            @trigger_error('Extending ' . __CLASS__ . ' is not supported', E_USER_DEPRECATED);
        }
    }
```

**Comment by greg0ire** [comment]
> Yes, in Theory, that beautiful country. But this not currently the case on internal bundles.

Do you really think that happens in practice ? Inside Sonata?

**Comment by Soullivaneuh** [comment]
> Do you really think that happens in practice ? Inside Sonata?

Already fall on a case like this. Had to fix an ugly abstract test class in core-bundle because the travis of an another sonata bundle (can't remember which one) using it was failing.

So yes, that really happens in practice, inside Sonata. :-)

**Comment by Soullivaneuh** [comment]
> Maybe we can resolve this by throwing a deprecation warning in the test classes?

I think it would be better to find those usage, fix them and then, apply the autoload-dev rule.

**Comment by core23** [comment]
There are the following test dependencies across our bundles:

SonataAdminBundle 
--------------------
Tests/Block/AdminListBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;
Tests/Block/AdminSearchBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;
Tests/Block/AdminStatsBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;
Tests/Form/ChoiceList/ModelChoiceListTest.php:use Sonata\CoreBundle\Tests\Fixtures\Bundle\Entity\Foo;
Tests/Form/ChoiceList/ModelChoiceLoaderTest.php:use Sonata\CoreBundle\Tests\Fixtures\Bundle\Entity\Foo;

SonataDashboardBundle
--------------------
Tests/Block/ContainerBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;

SonataFormatterBundle
--------------------
Tests/Block/FormatterBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;

SonataMediaBundle
--------------------
Tests/Block/Breadcrumb/BreadcrumbTest.php:use Sonata\SeoBundle\Tests\Block\BaseBlockTest;
Tests/Block/GalleryListBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;
Tests/Block/GalleryListBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;


SonataPageBundle
--------------------
Tests/Block/PageListBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\AbstractBlockServiceTest;
Tests/Block/PageListBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;

SonataSeoBundle
--------------------
Tests/Block/Social/FacebookLikeBoxBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;
Tests/Block/Social/FacebookLikeButtonBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;
Tests/Block/Social/FacebookSendButtonBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;
Tests/Block/Social/FacebookShareButtonBlockServiceTest.php:use Sonata\BlockBundle\Tests\Block\Service\FakeTemplating;

**Comment by core23** [comment]
So we can fix this on all minor versions, except for the seo, block and core bundle.

**Comment by Soullivaneuh** [comment]
> except for the seo, block and core bundle.

why ?

**Comment by core23** [comment]
As you can sea above:

 * media bundles has a dependency to seo tests
 * nearly all have a dependency to block tests
 * admin bundle as a dependency to the core tests

**Comment by Soullivaneuh** [comment]
Yeah, so:

> fix them and then, apply the autoload-dev rule.

Apply on minor ofc. :wink:

**Comment by core23** [comment]
That's what I'm doing in the block bundle right now ;)

**Comment by Soullivaneuh** [comment]
@greg0ire @OskarStark @core23:

https://github.com/sonata-project/SonataSeoBundle/pull/163 and https://github.com/sonata-project/SonataBlockBundle/pull/312 have to be reverted.

After that, for seo-bundle as exemple:

* Remove autoload on minor (2.x) with an upgrade not like the other
* Ping me to release a 2.1 version
* Fix broken related repositories (as patches, with bumping seo-bundle constraint to `^2.1`)

Same after for block bundle, for 3.x.

**Comment by core23** [comment]
We can't do this without any risk. 

(Techincally) a project could require block bundle 3.1.0 and seo bundle 2.0.0. This version of the seo bundle requires the `Tests` classes of the block bundle to be autoloaded. If we remove the autoloader, the project will fail.

We can resolve this, if we release new minor releases of admin, dashbard, formatter, media, page and seo bundle. After that we add all lower versions to the `conflict` section in the block bundle `composer.json` config.

Same for the other master changes

**Comment by Soullivaneuh** [comment]
> (Techincally) a project could require block bundle 3.1.0 and seo bundle 2.0.0. This version of the seo bundle requires the Tests classes of the block bundle to be autoloaded. If we remove the autoloader, the project will fail.

Then bump requirement of seo-bundle to `^2.1`.

> We can resolve this, if we release new minor releases of admin, dashbard, formatter, media, page and seo bundle. After that we add all lower versions to the `conflict` section in the block bundle `composer.json` config.

`conflict` key **only** if the dependency is not a mandatory (e.g. not in the `require` section). Otherwise, just bump the concerned requirement constraint.

> Same for the other master changes

What do you mean?

@greg0ire I continue here for https://github.com/sonata-project/SonataSeoBundle/pull/163#issuecomment-229600643

> This has nothing to do with the issue at hand IMO.

> Here we have SonataSeoBundle. If we change something in this bundle and it means people (and in people I include "other bundles") have to change their code (be it fix their tests or whatever) if they upgrade, that means the change is a BC-break. And every reasonable BC-break should trigger a major release.

> So in this case, unless we consider it's not a reasonable BC-break (meaning we consider people should not rely on the test classes being public), it should be major.

Test classes should never be used. Autoload all of them was a mistake. So no it's not really a not-reasonable BC break.

**Comment by greg0ire** [comment]
> Test classes should never be used. Autoload all of them was a mistake. So no it's not really a not-reasonable BC break.

Ok then.

**Comment by Soullivaneuh** [comment]
Ok so let's start reverting concerned PR.

Then apply https://github.com/sonata-project/dev-kit/issues/179#issuecomment-229599354 with:

* Constraint requirement bumping if on `require`
* `conflict` key if not a mandatory requirement

@core23 Are we :ok: now?

**Comment by core23** [comment]
> Test classes should never be used. Autoload all of them was a mistake. So no it's not really a not-reasonable BC break.

That's true, it was a mistake. If we are strict on semver, we must handle it on the master because someone could use it. Maybe could get some other @sonata-project/contributors opinion??

**Comment by Soullivaneuh** [comment]
> If we are strict on semver, we must handle it on the master because someone could use it.

Not if it's a not wanted behavior at all. It was never said on docs or another place to not use those tests.

For me, it's a bugfix.

**Comment by Soullivaneuh** [comment]
> we must handle it on the master because someone could use it

Plus, in this case all the other bundle should have modification of master. We didn't do that because test removal was not considered as a BC break.

I don't see why we should not do the same for those ones.

**Comment by Soullivaneuh** [comment]
I'll revert those PRs.

You said we should not because some end users may extend/use test classes, but this was already done on stable branches for other projects, so this is not relevant.

For internal cases, we just have to fix test according to the change.

Let's start one by one and ask me if you have to get some new release when the time comes. :wink:

**Comment by core23** [comment]
Revert if you like. Hope nobody uses this classes.

**Comment by Soullivaneuh** [comment]
> Hope nobody uses this classes.

As said, if we wanted to keep BC on class which should not be used, it should be done on master for *all* project.

This was not the case so let be consistent.

After that, if you think some class should be moved on the public namespace this can be done at the same time.

**Comment by Soullivaneuh** [comment]
PR reverted for seo and block.

@core23 Are they the only ones?

**Comment by core23** [comment]
All internal `Tests` dependencies are now fixed.

**Comment by rande** [comment]
@core23, nice works! I like to learn new composer options ;)

**Comment by core23** [comment]
All done here 🎉

**Comment by Soullivaneuh** [comment]
Thanks a lot for your work and your time @core23! :heart: :+1:
