### ISSUE TITLE
codestyle: enforce phpdoc textual description

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#18]
A lot of the code right now use IDE oriented php docblocks, giving only the params & return types but no human-friendly description.
While this is useful for autocompletion, it is frustrating when you try to fix something,  add a feature, extend a class, implement an interface, etc... Because what the method does is not described, you have to read it's code (and sometimes read through a dozen others), just to know if this is the one you should use/implement or not.

So I propose enforcing that:
- all methods have a docblock with `@param`, `@returns` (and `@throws` when needed) 
- all public/protected methods MUST have a textual description. 
- private methods MUST have a textual description, unless they are very short (one loc or one loc + a return statement). 

As with the commit messages, give some examples of what's a good description and what's not.

**Comment by greg0ire** [comment]
I have mixed feelings about this, maybe you will too after you read [this](http://mnapoli.fr/approaching-coding-style-rationally/)

**Comment by greg0ire** [comment]
So what I would enforce is : remove docblocks that paraphrase code, so that what remains is always intersting (otherwise no one reads it)

**Comment by Soullivaneuh** [comment]
> all methods have a docblock with @param, @returns (and @throws when needed)

:+1: 

> all public/protected methods MUST have a textual description.

:-1: for "all"

Example:

```php
/**
 * Returns the cake.
 *
 * @return Cake
 */
public function getTheCake()
{
    return $this->cakeWithALie;
}
```

Well, we understood that `getTheCake` returns the cake...

> private methods MUST have a textual description, unless they are very short (one loc or one loc + a return statement).

:+1:, unless they are very short **or** enough comprehensible.

**Comment by ju1ius** [comment]
I agree, do not paraphrase code.
But the important thing is
```php
/**
 * Tell what the hell is the cake, what's its purpose?
 * Where does it come from and where should it go.
 * Giva a small code sample. 
 * That would be useful. 
 *
 * @return Cake
 */
public function getTheCake()
{
    return $this->cakeWithALie;
}
```

Take for example the [AminInterface](https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/AdminInterface.php).
How the hell am I supposed to understand how things work with this documentation ?
And the funniest thing is that Admin uses {@inheritdoc} !

**Comment by greg0ire** [comment]
Ok for enforcing this, but of course, enforcing it should not be done with an automatic tool, otherwise we will get lots of useless `Gets the cake`

**Comment by Soullivaneuh** [comment]
> Tell what the hell is the cake, what's its purpose?

Well, don't forget the description of the `Cake` class...

Why the hell did I get this example? I'm hungry now.

**Comment by greg0ire** [comment]
BTW, I don't know what is the point of the AdminInterface : 

- no one is going to implement it without extending the `Admin` class
- it violates the ISP so hard, no one is going to want to implement it.

**Comment by ju1ius** [comment]
From https://symfony.com/doc/current/contributing/code/standards.html#documentation

**Comment by ju1ius** [comment]
Thinking about it a bit more, maybe making it a two-steps process would work.
Enforce description with automated tool, then check when reviewing if the description is actually useful.
The goal of enforcing it is to make people actually think a bit more about how they would properly explain the method without reading it's body.
I think in most cases, when you actually think about it, you can find a good description, event for getters/setter.

For example:

Bad auto-generated description:
```php
interface Cake {
  /**
   * Set $topping
   *
   * @param Topping $topping
   */
  public function setTopping(Topping $topping);
  /**
   * Get $topping
   *
   * @return Topping|null
   */
  public function getTopping();
}
```
Better
```php
interface Cake {
  /**
   * Sets the topping instance to use for this cake.
   *
   * While you can use any kind of topping, a sweet topping is most common for cakes.
   * Once you've set the topping for a cake, you should not reuse it for anything else.
   *
   * @param Topping $topping
   */
  public function setTopping(Topping $topping);
  /**
   * Returns the topping instance in use for this cake, if any.
   *
   * @return Topping|null
   */
  public function getTopping();
}
```

**Comment by greg0ire** [comment]
I don't know. Here is an example of method with no description : https://github.com/sonata-project/SonataAdminBundle/blob/master/Event/ConfigureEvent.php#L76 Not sure we can say anything interesting about it.

**Comment by ju1ius** [comment]
Something like that maybe ?
```php
/**
 * Returns the admin instance currently being configured.
 *
 * @return AdminInterface
 */
```

**Comment by greg0ire** [comment]
I said "interesting" :wink: Your message is just a fancy way of saying "returns the admin". So I don't think it should automatically be enforced. Instead, reviewers should ask contributors to describe methods whose name is not enough to describe their purpose.

**Comment by ju1ius** [comment]
> Your message is just a fancy way of saying

I don't find it very fancy :stuck_out_tongue:

**Comment by ju1ius** [comment]
I think you might be missing something in this particular case.
An event always have, in one way or another, the concept of a "target" (or "subject").
Saying:
> «Returns the admin instance **currently being configured**»

Does not only means «returns the admin», but «returns the admin **that is the subject of this event**».
If you look at the whole file's documentation this is never explicitely stated anywhere.

**Comment by ju1ius** [comment]
>  Instead, reviewers should ask contributors to describe methods **whose name is not enough to describe their purpose**.

What's enough for somebody knowing the whole codebase by heart might be quite different for a newcomer.

From «How to write unmaintable code», documentation chapter:
 > **Monty Python Comments**
> On a method called makeSnafucated insert only the JavaDoc /* make snafucated */.
> Never define what snafucated means anywhere.
> Only a fool does not already know, with complete certainty, what snafucated means.
> For classic examples of this technique, consult the Sun AWT JavaDOC.

**Comment by greg0ire** [comment]
You're making really good points, maybe we should indeed enforce good documentation.

**Comment by greg0ire** [comment]
@ju1ius what about constructors ? Would you also force documentation for them ?
