### ISSUE TITLE
CS: @inheritDoc tag

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#180]
# TL;DR

Usage of `{@inheritDoc}` should be forbidden if no additional documentation is provided.
`@inheritDoc` should be used instead.

# Long version

From the [PHPDoc documentation](https://phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag):

> Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
>
> However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard `@inheritDoc` that will serve that purpose.

According to this and given the following:

```php
interface Thing {
  /**
   * Sets a name for this thing.
   *
   * Because all things shall be given a name.
   *
   * @param string $name
   */
  public function setName($name);
}
```

The following are valid usages of the tag:

```php
// nothing, use default inherintance behavior
class Gizmo implements Thing {
  public function setName($name) {
    $this->name = $name;
  }
}
// Keeps default inheritance, but explicitely states
// it's been documented up in the type hierarchy
class Hoozit implements Thing {
  /**
   * @inheritDoc
   */
  public function setName($name) {
    $this->name = $name;
  }
}
// overrides the parent description field
class Thingy implements Thing {
  /**
   * {@inheritDoc} But as thingies are small, it will be cut at 42 characters.
   */
  public function setName($name) {
    $this->name = mb_strimwidth($name, 0, 42);
  }
}
```
But the following is not:
```php
class WatchamaCallit implements Thing {
  /**
   * {@inheritDoc}
   */
  public function setName($name) {
    $this->name = $name;
  }
}
```

**Comment by Soullivaneuh** [comment]
So if I well understood:

* `{@inheritDoc}` If you have additional information to add from the parent
* `@inheritDoc` If you have nothing to add?

And the difference are just `{}`. Wow, so much complication for nearly nothing IMHO...

**Comment by Soullivaneuh** [comment]
BTW I take a look on Symfony code.

* They are using `inheritdoc` label, without camel case.
* Only `{@inheritdoc}`

And they have a quite well documented api: http://api.symfony.com/3.0/index.html

Plus a Symfony CS fixer is already working for that, `phpdoc_inline_tag`:

> Fix PHPDoc inline tags, make inheritdoc always inline.

So let just follow this convention.

If you are convinced this should be changed, try your chance on the Symfony repository (link here would be appreciated). :wink:
