### ISSUE TITLE
How to handle deprecated repositories

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#181]
There are some old repositories that are deprecated and not supported anymore. We shouldn't allow any new issues and PRs on these. Maybe a bot can help with autoclosing PRs?

This should be done at least here:
- [x] https://github.com/sonata-project/composer-archive-creator
- [x] https://github.com/sonata-project/sonata-capistrano
- [x] https://github.com/sonata-project/SonataBluePrintBundle
- [x] https://github.com/sonata-project/SonataGoutteBundle
- [x] https://github.com/sonata-project/SonataMarkItUpBundle
- [x] https://github.com/sonata-project/SonatajQueryBundle

They aren't deprecated yet, but no one contributes:
- https://github.com/sonata-project/sonata-composer
- https://github.com/sonata-project/stats
- https://github.com/sonata-project/php-travis-client
- https://github.com/sonata-project/math
- https://github.com/sonata-project/symfony-marketing

**Comment by Soullivaneuh** [comment]
First, I can edit repositories settings to block issue creation.

For the PR auto-close, I have to integrate on dev-kit, I don't really want to... :-/

Or maybe a simple config section listing all deprecated packages?

> They aren't deprecated yet, but no one contributes:

I think some are deprecated but not specified.

Ping @rande for more precision.

**Comment by Soullivaneuh** [comment]
@core23 I deactivated issue section for repositories marked as deprecated.

**Comment by Soullivaneuh** [comment]
@core23 You can remove the sandbox-build from the list.

This repository is an automate to provide ready to use sandbox builds.

**Comment by core23** [comment]
> This repository is an automate to provide ready to use sandbox builds.

Sure? Last commit is nearly one year old...

**Comment by Soullivaneuh** [comment]
> Sure? Last commit is nearly one year old...

Maybe because the sandbox itself is currently broken. Ref: #138 

cc @rande

**Comment by core23** [comment]
@rande Can you have a look at the ref'd repos?

* https://github.com/sonata-project/sonata-composer
* https://github.com/sonata-project/stats
* https://github.com/sonata-project/php-travis-client
* https://github.com/sonata-project/math
* https://github.com/sonata-project/symfony-marketing

**Comment by jordisala1991** [comment]
Those repositories are archived. There is a new issue related to this one here: #347 

Closing.
