### ISSUE TITLE
Running Sonata's tests at the project level

### ISSUE THREAD

**Issue by rande** [sonata-project/dev-kit#182]
I don't want to comment on this https://github.com/sonata-project/SonataAdminBundle/issues/3766. However, I prefer to have a open discussion on `dev-kit`.

Bundles' tests autoload are built to be tested using either the current `vendor` inside the bundle OR the `vendor` at the project level. (see: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/tests/autoload.php.dist) That is why the sandbox have a dedicated test suite running the sonata projet vendors.

@greg0ire point out tests are already played inside each vendor, and there is no need to run them at the projet level. I do not agree with that.

Resolving dependencies at the project level can be different than the ones resolved in the bundle. So we must also test sonata's bundle with this particular scenario, which is the most important as it represent the final production code.

Of course, removing this feature will also not be BC and might also alter the way the sandbox is tested.

We might be able to create a custom function to avoid this can of code: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/tests/autoload.php.dist

**Comment by Soullivaneuh** [comment]
Also I planned to add a special job on Travis to run sandbox test with the code of the concerning PR/commit.

But we have to get a clear way of #138 before.

**Comment by greg0ire** [comment]
> So we must also test sonata's bundle with this particular scenario, which is the most important as it represent the final production code.

That's a good point, and testing for the lowest deps is not enough to make sure of that. I think there is no harm done in allowing that.

**Comment by ju1ius** [comment]
> So we must also test sonata's bundle with this particular scenario, which is the most important as it represent the final production code.

There's no +100 button, so: +:100:

**Comment by Soullivaneuh** [comment]
I don't get the point of requiring project vendor from PHPUnit bootstrap like done by @ju1ius in https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/394.

AFAIK, when you clone a sonata repository, the project is... the concerned bundle or the library, right?

Am I missing something?

**Comment by ju1ius** [comment]
@Soullivaneuh It is a DX improvement when you develop on several bundles.

Say you're working on admin-bundle, doctrine-orm-admin-bundle, doctrine-mongodb-admin-bundle and doctrine-phpcr-admin-bundle.
Without the phpunit autoloader being able to fallback to the project's vendor, you have to:
* setup your custom repositories and branch aliases for the project's composer.json
* do the same inside each bundle
* run `composer install` inside each bundle
* now every time you change something in admin-bundle and want to launch the tests all others:
```sh
cd admin-bundle
git commit
git push origin my-branch
cd  ../doctrine-orm-admin-bundle && composer update && phpunit -c phpunit.xml.dist
cd  ../doctrine-mongodb-admin-bundle && composer update && phpunit -c phpunit.xml.dist
cd  ../doctrine-phpcr-admin-bundle && composer update && phpunit -c phpunit.xml.dist
```

This is a very repetitive and time-consuming task.
And commiting+pushing stuff just to be able to test them... :sob:

**Comment by Soullivaneuh** [comment]
Oh so it's just a "ain't nobody got time for that" problem! :trollface: 

I'm not used to work as is, this is why I didn't get the point.

If this has no consequence for the "classic" way, I don't see anything thing to be against. :+1:

**Comment by Soullivaneuh** [comment]
Doesn't this be not relevant anymore after https://github.com/sonata-project/dev-kit/issues/179?

**Comment by jordisala1991** [comment]
It looks like this is no longer relevant, Tests are no longer autoloaded when the bundle is installed with composer, and they are not even there, because of git exclusions.

Closing.
