### ISSUE TITLE
Lint twig templates via github actions as part of CI?

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/dev-kit#1829]
See https://github.com/sonata-project/SonataAdminBundle/pull/7669#issuecomment-1000217113

This could prevent such issues

**Comment by VincentLanglet** [comment]
@jordisala1991 You already said to me that most of our recent bug are twig related, this could be a great way to avoid it.

**Comment by jordisala1991** [comment]
It would be nice, yes. IMO we should also have some functional tests that covers some of the basic features, that helps a lot too.

**Comment by jordisala1991** [comment]
If we standarize how we create the test kernel across all bundles we can move some things to dev kit, and it would be nice, because that allows to execute console commands like lint twig or lint container (maybe there are others too)
