### ISSUE TITLE
Missing require for sllh/php-cs-fixer-styleci-bridge

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#183]
SonataDoctrineMongoDBAdminBundle is missing a require field for `sllh/php-cs-fixer-styleci-bridge` in his composer.json.

As a result, it is impossible to run php-cs-fixer for this bundle.
Maybe your automated task should ensure that ?

Moreover the .php_cs config file requires the library to be installed inside the bundle's vendor directory, which is quite a pain when developing on 5 bundles at the same time.

**Comment by Soullivaneuh** [comment]
> Maybe your automated task should ensure that ?

No. I just forgot it. :wink: 

> Moreover the .php_cs config file requires the library to be installed inside the bundle's vendor directory, which is quite a pain when developing on 5 bundles at the same time.

No choice. I can't determine where is the composer home from `.php_cs` to have a global setup.

**Comment by ju1ius** [comment]
@Soullivaneuh fixed in https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/176
