### ISSUE TITLE
Make private methods final?

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#185]
We have several discussion on many issues, so I want to start a global one here. Should we make all private methods final?

In theory, you can only extend `protected` and `public` methods. The `final` keyword permits overriding an existing method / class.

In practice, there are some issues if you have private methods:

- You can't declare a new method, if a **final private** method exists in the parent class (https://3v4l.org/VL1Js). But you can declare it on **non final private** methods (https://3v4l.org/578Rs)
- You can't declare a new method, if a method with a **different method header** exists in the parent class (https://3v4l.org/oCG5c).

:+1: To make private method `final`
:-1: To not do it

**Comment by core23** [comment]
IMHO if we make a private method final, the only thing that changes is exception type. So no need to make them final 👎

**Comment by Soullivaneuh** [comment]
@core23 I updated your post.

For me, it's a :+1: because add a `final` keyword does not hurt anyone and reduce crappy code BC breaks and useless issue opening.

**Comment by core23** [comment]
> But as protected and public method, should be done on next majors for existing ones.

For me that's not the part of the discussion. It's a general decision where we want go. Sure, we can't do this on stable branches for consequential reasons.

If we want a final keyword infront of private methods, we must adapt this to all exsting methods to have a clear view.

**Comment by Soullivaneuh** [comment]
> For me that's not the part of the discussion.

Yes an no. Just a reminder. :wink:

**Comment by core23** [comment]
Maybe we can address this to the php bugtracker? The actual behavior looks wrong to me.

**Comment by Soullivaneuh** [comment]
I agree, looks very weird. Maybe it's already addressed?

**Comment by greg0ire** [comment]
I vote :-1: : by making a private method final, you prevent author of child classes from choosing the same name for a private method if they want to. As for public methods, the behavior looks indeed buggy, and I couldn't find an issue, [so I filed one](https://bugs.php.net/bug.php?id=72496&thanks=4)

**Comment by Soullivaneuh** [comment]
> I vote :-1:

So why did you do that? https://github.com/sonata-project/SonataCoreBundle/pull/270#discussion-diff-68501023R96 :trollface:

**Comment by greg0ire** [comment]
Hadn't made up my mind and give it a real thought until now, I'll see how this ends. Anyway, I think it's a quite pedantic issue.

**Comment by greg0ire** [comment]
Yay guys I have a reply from nikic himself ! The bug report is verified, so this means this is truly a buggy behavior :)

**Comment by core23** [comment]
In other words, there is clearly no reason to make private methods final

**Comment by greg0ire** [comment]
Someone wrote a PR : https://github.com/php/php-src/pull/1971 :clap:

**Comment by Soullivaneuh** [comment]
Also made a proposition for PHP-CS-Fixer here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1899
