### ISSUE TITLE
Doc: who is the core team ?

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/dev-kit#19]
There should be something resembling http://symfony.com/doc/current/contributing/code/core_team.html
Without going that far, at least let people know:
- Who is (are) the project leader/BDFL, if any ?
- Who is (are) the main maintainer of a given repo ?
- Who has merge rights on what ?
- ...

So as to put "faces" on the project, know who to ping/mention in issues/PRs/StackOverflow, and all that...

**Comment by core23** [comment]
Not sure, if the team is big enough to split them into groups like mergers, reviewers, ...

In general it's a good a idea to have one project leader for each repository.

**Comment by Soullivaneuh** [comment]
About core team, see: https://sonata-project.org/blog/2016/4/22/the-new-sonata-project-team

I talk about rander about release management. We will start with a reduce group of people allowed to tag on any project and, like @core23 says, add some specific person for "exotic" projects.

**Comment by jordisala1991** [comment]
As @core23 said we are not a super big team, and we are all maintaining everything, there is no sense to split us.

As @Soullivaneuh said, we are using the blog and twitter to do comunications.

Closing for now.
