### ISSUE TITLE
Close issues that have been pending for too long

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#190]
It would be great IMO to automatically close issues that have been pending for <insert time duration here>.
It would also be great to automatically close PRs that have been pending for <insert longer time duration here>, asking the author if to feel free to reopen when they have time to reply / work on the PR.

What do you think @sonata-project/contributors ?

**Comment by Soullivaneuh** [comment]
Yes I already had this idea on my mind and have to work on it.

I think we have to close issue/PR only if the "Pending Author" label is present and calculate the time from the label add date, if possible.

**Comment by greg0ire** [comment]
> calculate the time from the label add date

Or from the author's last comment?

**Comment by Soullivaneuh** [comment]
> Or from the author's last comment?

It will be a problem for very old issues before the dev-kit system.

If some issue has no answer from staff and got an auto-close, this will not be very nice. :-/

**Comment by greg0ire** [comment]
> If some issue has no answer from staff and got an auto-close, this will not be very nice. :-/

If there is no answer from staff, then there won't be any "pending author" tag, right?

**Comment by Soullivaneuh** [comment]
Concrete example:

Let's assume the max time is 90 days (~3 months).

1. A user open an issue
2. A staff member add an answer asking for more details 4 months after the opening
3. The staff member add the "Pending Author" label
4. According to the **author** message, the issue will be immediately closed by the bot

So we can't set the limit based to the author last message.

At least, if we can't used the label adding date, we can use the last message of author **and** staff members, but it will be risky if the staff member add the label before answering.

**Comment by greg0ire** [comment]
Your right, my logic was flawed, and I agree the label adding date would be best. I would set it to 1 week for issues, 1 month for PRs.

**Comment by Soullivaneuh** [comment]
> I would set it to 1 week for issues, 1 month for PRs.

Wow, it's a way too short IMHO!

90 days it's a good deal for me. Don't forget that people can got to vacation and answer on GitHub later. :wink:

**Comment by Soullivaneuh** [comment]
Also we should block the auto-close if we add the "In progress" label.

**Comment by greg0ire** [comment]
> 90 days it's a good deal for me

Who takes 90 days vacations? I think 1 week might be short indeed though, how about 3 weeks ? (one 2 week vacation + some time to react). Sounds fair?

**Comment by Soullivaneuh** [comment]
> Who takes 90 days vacations?

Some guys can. :wink: 

And it's not only for vacation. All contributors does not apply free times only for Sonata.

It could be possible to not be available to work on an issue/PR because we have more important things to do.

On other projects, some PR can be still open for months and get finally reworked and merged.

3 months is not a big deal IMHO, time go fast you know. :-)

**Comment by greg0ire** [comment]
> All contributors does not apply free times only for Sonata.

> It could be possible to not be available to work on an issue/PR because we have more important things to do.

Yes but you can still answer, right ? Being busy to the point you cannot take the time to say you are is what I don't understand.

**Comment by Soullivaneuh** [comment]
> Yes but you can still answer, right ?

Depends of people too.

For some cases, I prefer answer later and let the issue on my notification list. :wink: 

Let's start with a longer time and see later if we have to make some adjustments! :-)

**Comment by greg0ire** [comment]
> Let's start with a longer time and see later if we have to make some adjustments! :-)

Given that we are dealing with time period that can be as long as one year or more, I think it will be quite useful already with a 3 month delay

**Comment by pulzarraider** [comment]
3 months are OK. People are doing open source in their free time (me too). If somebody invests time to create the PR, we should let him enough time to complete the work.

**Comment by VincentLanglet** [comment]
There is now a stale bot
