### ISSUE TITLE
How to handle Symfony 2 / Symfony 3 doc

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#194]
Currently, most bundles are supporting two versions of Symfony. Which should be the default in the docs, and how should we handle showing configuration for two versions?

See 
- https://github.com/sonata-project/SonataFormatterBundle/pull/209
- https://github.com/sonata-project/SonataAdminBundle/pull/4067

**Comment by Soullivaneuh** [comment]
IMHO, we should handle the latest version.

**Comment by greg0ire** [comment]
@sonata-project/contributors , please vote on @Soullivaneuh 's answer.

**Comment by greg0ire** [comment]
3 positive votes. Latest version it is.
