### ISSUE TITLE
Mark deprecated code with exact version

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/dev-kit#195]
In https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md is written:

```
In some cases, you will have the possibility to warn the user that things will change, and recommend a new way of doing things. You can do so by triggering the dedicated kind of error, like this:

<?php
if (/* some condition showing the user is using the legacy way */) {
    @trigger_error(
        'The '.__METHOD__.' method is deprecated since 42.x, to be removed in 43.0. '.
        'Use FooClass::barMethod() instead.',
        E_USER_DEPRECATED
    );
} else {
    // new way of doing things
}
```
Mentioning `42.x` in the example is inaccurate. Is the way how we want to mark the deprecated features? I think, that in the code there should be always specified the exact version from which is the code deprecated.

So instead of `42.x` in the example should be: `42.5`.

### Problems with `42.x` in the code
User doesn't know exact version from which is the code deprecated. Is the version that was released before one month or before one year? He should check the changlog for more informations. We can mark this deprecation notice as incomplete.

If we will insist on `42.x` in the code of PRs, there should be some responsible person (or script), who will change the `42.x` texts to `42.5` just before the new release.

### The proposal
Instead of forcing users to write `42.x`, let user to specify the next minor version.

If the number will not be correct because we need to release new version quickly, it can be fixed after merging the PR.

What do you think @sonata-project/contributors ?

**Comment by Soullivaneuh** [comment]
The `.x` part is replaced on each release.

We put `.x` simply because a new minor can be release before the concerned PR is going to be merged.

This is the same for the upgrade note.

At the end, the user will have an exact version warning on stable releases.

**Comment by greg0ire** [comment]
On the one hand, I don't know who could care about this information, and on the other hand, since deprecation notices are supposed to be removed before the next major, we bring zero information when saying "since 42.x". I propose we simply drop the "since 42.x" part.

**Comment by Soullivaneuh** [comment]
> I propose we simply drop the "since 42.x" part.

:-1: for that. Specify the version is a good helper for developer making libraries depending on ours and supporting multiple versions.

**Comment by pulzarraider** [comment]
@Soullivaneuh If it's done automatically, there is missing information about this. The `.x` can be understood as something that should be replaced by developer.

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh If it's done automatically, there is missing information about this.

This is done automatically by a bot named @Soullivaneuh. :stuck_out_tongue: 

But yeah, this part should be documented when we will work on a contributing guide for admins.

**Comment by greg0ire** [comment]
> Specify the version is a good helper for developer making libraries depending on ours and supporting multiple versions.

I didn't think of this use case, it makes sense.
