### ISSUE TITLE
SonataCI won't remove "review required"

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#196]
When SonataCI adds the `pending author` tag, it won't remove the `review required` at the moment. This should be changed.

Either we should do something (`review required`) or the author (`pending author`).

**Comment by Soullivaneuh** [comment]
Where did you see SonataCI adding Pending Author tag? It should not. This tag is added manually by us.

**Comment by core23** [comment]
e.g. https://github.com/sonata-project/SonataAdminBundle/pull/4073

**Comment by Soullivaneuh** [comment]
Indeed, this is the only case.

But this is only for rebase asking. I don't see why the review can't be done.

**Comment by core23** [comment]
We could review it, but we have to wait for the author to merge. So a review wouldn't help as long as there is no further action from the user.

I would prefer only one of these tags in a PR.

**Comment by OskarStark** [comment]
`review required` should be removed by SonataCI after merge

**Comment by greg0ire** [comment]
Also, `review required` is a bit useless now that there is the review system that literally shows "Review required" on the PR and on the PR list natively.

**Comment by Soullivaneuh** [comment]
> Also, `review required` is a bit useless now that there is the review system that literally shows "Review required" on the PR and on the PR list natively.

You are right about it.

The label should be removed and the branch protection updated.
