### ISSUE TITLE
Management: Sync Labels across bundles

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#20]
We should find a way to sync the labels and have them across all bundles.

Version labels:
- major
- minor
- patch

General labels:
- doc
- pending user reply
- work in progress
- review required
- question
- feature / nice to have

This tools might help:
- https://github.com/Jimdo/github-sync-labels-milestones
- https://github.com/piwik/github-sync

**Comment by Soullivaneuh** [comment]
Thanks for the link @core23 and yes, this was already planned on my brain! :wink:

**Comment by core23** [comment]
Refs https://github.com/sonata-project/dev-kit/pull/29
