### ISSUE TITLE
Update sonata-project website

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#200]
We should update the sonata-project website:
- [x] [homepage](https://sonata-project.org/) is talking about a google group
- [x] [contributing page](https://sonata-project.org/contributing) is talking about IRC which no one is using at the moment
- [ ] [get started](https://sonata-project.org/get-started) refers to the old sandbox release

**Comment by OskarStark** [comment]
@rande could we setup sth like the symfony-marketing website?

In this case we would have a git repository which could be used. With RST like the docs and a custom theme?

**Comment by rande** [comment]
@OskarStark no, however I can provide access to the application code source, so you can alter the code with MR (the code is now on gitlab)

**Comment by rande** [comment]
@core23 all good points!

**Comment by OskarStark** [comment]
> @OskarStark no, however I can provide access to the application code source, so you can alter the code with MR (the code is now on gitlab)

ok

**Comment by rande** [comment]
@core23 @OskarStark just give me your gitlab account

**Comment by greg0ire** [comment]
https://gitlab.com/search?project_id=1578617&scope=issues&search=IRC does not yield any results… is it stored in the DB?

**Comment by greg0ire** [comment]
It does yield results in fact, here is the MR : https://gitlab.com/sonataproject/sonata-project.org/merge_requests/6/commits

Please merge and deploy.

**Comment by core23** [comment]
Should we allow https://slackinvite.me/ to join or slack team?

**Comment by VincentLanglet** [comment]
Closing in favor of the recent @jordisala1991 work
- moving the docs to readthedocs.io
- using weblate for translations
- creating a new homepage
