### ISSUE TITLE
The next release train

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#2009]
Even if https://github.com/sonata-project/dev-kit/issues/1715 is not finished (some contributors are working on it) we may want to move on for other sonata packages.

- [x] SonataFormExtensions v2
  - [x] Resolve deprecated code: https://github.com/sonata-project/form-extensions/pull/359
  - [x] Drop support for PHP 7.3
  - [x] Drop support for PHP 7.4
  - [x] Add rector
  - [x] Drop support for Symfony 4 (and twig 2 ?)
  - [x] Update docs: https://github.com/sonata-project/form-extensions/pull/354
  - [x] Add support on SonataAdmin
  - [x] https://github.com/sonata-project/form-extensions/pull/335
  - [x] Release alpha
  - [x] Cleanup older upgrade files
  - [x] Create 3.x branch and configure on dev-kit
  - [x] Release stable
- [x] BlockBundle v5
  - [x] Resolve deprecated code
  - [x] Drop support for PHP 7.3
  - [x] Drop support for PHP 7.4
  - [x] Add rector: https://github.com/sonata-project/SonataBlockBundle/pull/1057
  - [x] Drop support for Symfony 4 (and some lowest version of dependencies ?): https://github.com/sonata-project/SonataBlockBundle/pull/1060
  - [x] Update docs
  - [x] Add support on SonataAdmin
  - [x] Wait for PageBundle v4 to be sure we don't need any change on BlockBundle 4.
  - [x] Release alpha
  - [x] Add upgrade file
  - [x] Add everything on upgrade file
  - [x] Cleanup older upgrade files
  - [x] Create 6.x branch and configure on dev-kit
  - [x] Release stable

The best would be to support all those new versions on SonataAdmin without the need for a new SonataAdmin major version.

Done: 
- SonataDoctrineExtension v2
- Exporter v3
- SonataTwigExtension v2
- SonataIntl v3
- SonataPage v4

**Comment by VincentLanglet** [comment]
cc @dmaicher @jordisala1991, since you started working on it

**Comment by dmaicher** [comment]
Regarding BlockBundle: Do we plan any more (breaking) changes for 5.0? Or are we close to releasing it?

@VincentLanglet maybe we can create another release on 4.x? See https://github.com/sonata-project/SonataBlockBundle/compare/4.12.0...4.x

**Comment by VincentLanglet** [comment]
> Regarding BlockBundle: Do we plan any more (breaking) changes for 5.0? Or are we close to releasing it?

I think we're close to releasing it.
But I thought we could focus on extensions library before

**Comment by VincentLanglet** [comment]
We might start soon to release the alphas cc @jordisala1991 @dmaicher

**Comment by VincentLanglet** [comment]
After the merge of https://github.com/sonata-project/exporter/pull/593 we're ready.

Do you think we need an alpha/beta releases for those bundle ?

**Comment by VincentLanglet** [comment]
Seems ready:
- https://master-7rqtwti-ptm4dx6rjpjko.eu-5.platformsh.site/next-release/doctrine-extensions/2.x
- https://master-7rqtwti-ptm4dx6rjpjko.eu-5.platformsh.site/next-release/exporter/3.x
- https://master-7rqtwti-ptm4dx6rjpjko.eu-5.platformsh.site/next-release/form-extensions/2.x
- https://master-7rqtwti-ptm4dx6rjpjko.eu-5.platformsh.site/next-release/twig-extensions/2.x
- https://master-7rqtwti-ptm4dx6rjpjko.eu-5.platformsh.site/next-release/block-bundle/5.x

Form-extensions is blocked by https://github.com/sonata-project/form-extensions/pull/335, but for others it's seems ok to make an alpha. Do you agree @jordisala1991  @dmaicher @sonata-project/contributors or do you see any others blocking points ?

**Comment by dmaicher** [comment]
Yeah good for me :+1:

**Comment by jordisala1991** [comment]
Yes, we can do an alpha release for all of them and wait for the form-extensions

**Comment by VincentLanglet** [comment]
Blockbundle has a dependency on form-extensions
https://github.com/sonata-project/SonataBlockBundle/blob/5.x/composer.json#L28

For others, there are
https://github.com/sonata-project/sonata-doctrine-extensions/pull/425
https://github.com/sonata-project/exporter/pull/598
https://github.com/sonata-project/twig-extensions/pull/331

**Comment by VincentLanglet** [comment]
Should we release the stable version of exporter/twig-extension and doctrine-extensions @jordisala1991 @dmaicher ?

**Comment by jordisala1991** [comment]
Exporter should be ready too. And we might try to prepare SonataIntlBundle too.

**Comment by VincentLanglet** [comment]
Yes, I'm starting SonataIntlBundle with https://github.com/sonata-project/SonataIntlBundle/pull/531

**Comment by VincentLanglet** [comment]
Should we go for the stable release of SonataIntl 3 https://github.com/sonata-project/SonataIntlBundle/releases ?

**Comment by dmaicher** [comment]
@VincentLanglet could we release BlockBundle v5? :thinking: This is waiting for a long time now

I would like to get rid of

```
sonata-project/cache          2.2.0              2.2.0              Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
``` 

I just tested on my biggest project and it works fine for me with `composer req sonata-project/block-bundle "5.x-dev as 4.99"`.

We need to allow `^5.0` on SonataAdminBundle though

**Comment by VincentLanglet** [comment]
I thought it was better to wait for formExtension before because of
https://github.com/sonata-project/SonataBlockBundle/blob/4.x/composer.json#L30
but maybe not.

I just tested on my biggest project and it works fine for me with `composer req sonata-project/block-bundle "5.x-dev as 4.99"`.
Can you also try with formExtension 2.x-dev as 1.99 ?

I'd like to confirm that:
- The current 2.x branch doesn't require new BC break on blockBundle
- The last point https://github.com/sonata-project/form-extensions/pull/335 doesn't require a BC break on BlockBundle (ping @jordisala1991)

Then we can release BlockBundle 5.0 and add later in a minor the FormExtension 2.0 support.

**Comment by dmaicher** [comment]
@VincentLanglet also additionally with `composer req sonata-project/form-extensions "2.x-dev as 1.99"` all my tests are passing and did some random manual testing: everything works fine

**Comment by jordisala1991** [comment]
Yes, we did not do an alpha for block bundle. It would be nice to do it. Also for form extensions (I only need to take a look at the twig thing for form extensions).

Do you have time to prepare the block bundle one?
