### ISSUE TITLE
PR/issue template with hint for screenshots?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#201]
What about adding a section to the PR/issue template, that the users should provide a screenshot (before/after) of visual changes/bugs ?

**Comment by Soullivaneuh** [comment]
It would be complicated. Screenshot are not always necessary.

**Comment by greg0ire** [comment]
Plus I think the main reason lazy people do not fill the template is its length, so I think we should try to keep it short.

**Comment by Soullivaneuh** [comment]
But this could be an interesting section on the contributing doc IMHO.

**Comment by greg0ire** [comment]
I think it is already in there, isn't it?

**Comment by jordisala1991** [comment]
There is: https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md#issues

Closing.
