### ISSUE TITLE
Convention for naming new twig blocks

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/dev-kit#205]
Naming twig blocks in Sonata bundle`s templates are inconsistent.

There are blocks, that are without any prefix (convention A), e.g. 
- [`meta_tags`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L27),
-  [`javascripts`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L39),
-  [`body_attributes`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L109),
-  [`bootlint`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L350).

But there are blocks, that has `sonata` in it`s name in the begining (convention B)
-  [`sonata_head_title`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L81),
-  [`sonata_breadcrumb`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L141),
-  [`sonata_top_nav_menu`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L182),
-  [`sonata_wrapper`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L213).

I prefer this way of defining new twig blocks, because any template in Sonata can be oveloaded. It's clearer to navigate in the overloaded templates if the template mix Sonata`s blocks and the own project twig blocks.

PR  sonata-project/SonataAdminBundle#4134 suggests to add `sonata` in the body of the twig block (convention C):
-  [`javascripts_sonata_config`](https://github.com/sonata-project/SonataAdminBundle/pull/4134/files#diff-01b33b418441737612fb2735e2bc2354R40),
-  [`javascripts_sonata_pool`](https://github.com/sonata-project/SonataAdminBundle/pull/4134/files#diff-01b33b418441737612fb2735e2bc2354R61).

Renaming already defined Twig block will be BC break. But we should decide which names we will use for new twig blocks.

Please @sonata-project/contributors  vote with :+1:  for the rule you prefer.

**Comment by pulzarraider** [comment]
convention A - do not add `sonata` in the twig block name

**Comment by pulzarraider** [comment]
convention B - prefix twig block name with `sonata`

**Comment by pulzarraider** [comment]
convention C - add `sonata` inside the twig block name

**Comment by elHornair** [comment]
For the sake of clarity: I wasn't suggesting that we use the ```sonata``` namespace inside of the block name (convention C - that would indeed be a very bad idea). I called it ```javascripts_sonata_config``` because ```javascripts``` is the name of the parent block and ```sonata_config``` is a description of the actual block (stating that it's the configuration for Sonata).

I recommend going with convention A for the following reasons:
* Option B makes all the block names more verbose
* There is no need for prefixing the blocks with ```sonata_``` because all the blocks are part of the Sonata project anyway
* Option B can't consistently be implemented without BC breaks (so you can either only apply it for new blocks and be inconsistent OR apply it for all blocks and break all extending templates)

**Comment by greg0ire** [comment]
I have weighed the pros and cons and I think avoid potential collisions might not be worth the hassle. Just like we don't prefix all methods in non final classes with `sonata`, I think we shouldn't prefix our blocks with `sonata`.

**Comment by pulzarraider** [comment]
> Thanks @pulzarraider for raising this interesting question though.

@greg0ire you're welcome.

> Just like we don't prefix all methods in non final classes with sonata

@gregoire yes, your're right. The difference here is that we have support and documentation how to overload core templates. If someone overloads the core class of Sonata, he is doing it at his own risk, because his changes may not work later (that's why creating PR is better).
We expect and accept overloading core templates.
Prefixing twig blocks don't help us - it's more ugly and longer, it helps people in overloaded templates.

>I called it javascripts_sonata_config because javascripts is the name of the parent block and sonata_config is a description of the actual block 

@elHornair I understand your way of naming templats. But what you've suggested ends with `sonata` inside the block name. Why not to name it `javascripts_config` and `javascripts_pool`? `sonata` inside the 
template name is still verbose. We are still usign sonata`s pool and configuring javascript libraries inside Sonata's template.

> There is no need for prefixing the blocks with sonata_ because all the blocks are part of the Sonata project anyway
@elHornair Yes, they are. I agree.  But if you overload the template (and you will do it sooner or later), you will mix blocks that you declare yourself and blocks that comes from the overloaded template.

And there is also another potential problem - if user choose name for his block, that we will declare, too, but in later versions, it can ends with very strange output (or error). So user won't easily upgrade on newer minor release without changing his template.

What we really miss here is some support to deprecate some block (with nice warning for user) so we can rename it in new major version for any convention we will choose.

This idea can also ends with another recommendation for users - we will not prefix blocks in Sonatya

**Comment by greg0ire** [comment]
> If someone overloads the core class of Sonata, he is doing it at his own risk, because his changes may not work later (that's why creating PR is better).
We expect and accept overloading core templates.

There are cases when you don't really have a choice to extend a class, b/c it is abstract (`AbstractAdmin`, for instance), and we still do not prefix all method names with `sonata`, but fully support people extending it.

> And there is also another potential problem - if user choose name for his block, that we will declare, too, but in later versions, it can ends with very strange output (or error). So user won't easily upgrade on newer minor release without changing his template.

We have the same problem with any new method of `AbstractAdmin`.

**Comment by greg0ire** [comment]
> What we really miss here is some support to deprecate some block (with nice warning for user) so we can rename it in new major version for any convention we will choose.

I filed [an issue](https://github.com/twigphp/Twig/issues/2112) about that.

**Comment by pulzarraider** [comment]
> We have the same problem with any new method of AbstractAdmin.

You' re right. So any new method added in AbstractAdmin can be potentional BC break.

**Comment by greg0ire** [comment]
> You' re right. So any new method added in AbstractAdmin can be potentional BC break.

One more reason to favor composition over inheritance if you ask me…

**Comment by greg0ire** [comment]
I think we have enough votes! Solution B it is.
