### ISSUE TITLE
deprecated vs NEXT_MAJOR

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#206]
Classes and method might be marked as deprecated. @core23 suggested that in that case, `NEXT_MAJOR` would be somewhat redundant. What should we do ? 

Things to be taken into account : 
- Always using `NEXT_MAJOR` will make greping for things left to do easier
- [@core23 couldn't find any usage of both things together](https://github.com/sonata-project/SonataCoreBundle/pull/311#r79307431)
- `@deprecated` plays nice with IDEs

**Comment by greg0ire** [comment]
```php
/**
 * Solution 1
 *
 * @deprecated this class is deprecated since 41.0 and will be removed in 42.0.
 */
```

**Comment by greg0ire** [comment]
```php
/**
 * Solution 2
 * NEXT_MAJOR : remove this class
 */
```

**Comment by greg0ire** [comment]
```php
/**
 * Solution 3
 * NEXT_MAJOR : remove this class
 *
 * @deprecated  this class is deprecated since 41.0 and will be removed in 42.0.
 */
```

**Comment by greg0ire** [comment]
```php
/**
 * Solution 4
* NEXT_MAJOR : remove this class
*
* @deprecated 
*/
```

**Comment by core23** [comment]
IMO we overcomplicate stuff by adding the `NEXT_MAJOR` comment in general. For normal deprecation / removing information, we have the corresponding `@deprecated` annotation which is a common way in all projects. 

The `NEXT_MAJOR` comment is just a hint for us, so we now what to do inside a method, e.g. removing BC hacks.

**Comment by greg0ire** [comment]
I removed my vote from solution 3, b/c when I see, https://github.com/sonata-project/SonataAdminBundle/pull/4124, I think that it would indeed be overkill. Too much work, and grep'ing for one more thing is not that big of a deal IMO.

**Comment by Soullivaneuh** [comment]
First of all, AFAIK it's `NEXT_MAJOR:`, not just `NEXT_MAJOR`.

And I vote for both for a simply reason: We just have to look after all `NEXT_MAJOR` tag instead of both `NEXT_MAJOR` and `@deprecated`.

BTW, `@deprecated` is here to warn end user first.

**Comment by greg0ire** [comment]
How about allowing summaries? For instance, for sonata-project/SonataAdminBundle#4124, put in the class header : 

```
/**
 * NEXT_MAJOR:
 * - remove setTranslator method 
 * - remove getTranslator method 
 * - remove trans method 
 * - remove transChoice method 
 * - remove translator property 
 */
```

**Comment by Soullivaneuh** [comment]
I'm not a big fan. Having `NEXT_MAJOR:` on the right section make thing easier to retrieve the place who you have something to do.

**Comment by greg0ire** [comment]
Yeah but I think it's a nice compromise between 1 and 3. What do you think @core23 ?

**Comment by Soullivaneuh** [comment]
> Yeah but I think it's a nice compromise

Not for me, sorry. :-)

**Comment by Soullivaneuh** [comment]
In any case, the `@deprecated` tag is **mandatory**, at least for warning message for IDE and Symfony toolbar.

So the solution 2 is not acceptable at all.

**Comment by OskarStark** [comment]
I totally agree with @Soullivaneuh , for now it works great with the `NEXT_MAJOR:` because is where it is needed, not in a summary!

**Comment by greg0ire** [comment]
Ok I think the matter can be considered as settled then. Solution 3 it is!

**Comment by core23** [comment]
> Ok I think the matter can be considered as settled then. Solution 3 it is!

If we apply solution 3. Who will look at the existing code and create the missing PRs which adds `NEXT_MAJOR` to all `@deprecated` methods.

**Comment by greg0ire** [comment]
> If we apply solution 3, who will look at the existing code and create the missing PRs which adds NEXT_MAJOR to all @deprecated methods.

I'd say no one, it's a bit late now. But let's do it this way for 5.0 .

**Comment by core23** [comment]
So we can merge https://github.com/sonata-project/SonataAdminBundle/pull/4124? Because it's for the 4.0 release.

**Comment by greg0ire** [comment]
No. all new PRs should have this from now on. I'll fix sonata-project/SonataAdminBundle#4124 and make a PR on your repo.

**Comment by greg0ire** [comment]
See https://github.com/core23/SonataAdminBundle/pull/1

**Comment by core23** [comment]
> No. all new PRs should have this from now on.

👎 When introducing this new information on methods / classes, we MUST add them to all methods to be consistent in our code.

**Comment by greg0ire** [comment]
![sigh](http://i.imgur.com/VXxJx.gif)
Jesus… fine, I'll do it, starting with https://github.com/sonata-project/SonataAdminBundle/pull/4144

**Comment by core23** [comment]
What about `@group legacy` for test classes? Should we use the `NEXT_MAJOR` comment too?

**Comment by greg0ire** [comment]
I can't think of a case where you will remove the code under test and not notice these tests break, and remove them.

**Comment by Soullivaneuh** [comment]
So let's keep to solution 3? This is the actual one.

**Comment by greg0ire** [comment]
You mean current ;) . And yes solution 3 please
