### ISSUE TITLE
Update PHP version in composer.json

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#208]
After merging https://github.com/sonata-project/dev-kit/pull/225, we need to update the composer.json files for:

- [ ] GoogleAuthenticator
- [ ] SonataAdminBundle
- [ ] SonataAdminSearchBundle
- [ ] SonataBlockBundle
- [ ] SonataCacheBundle
- [ ] SonataClassificationBundle
- [ ] SonataClassificationMediaBundle
- [ ] SonataCommentBundle
- [ ] SonataCoreBundle
- [ ] SonataDashboardBundle
- [ ] SonataDatagridBundle
- [ ] SonataDoctrineMongoDBAdminBundle
- [ ] SonataDoctrineORMAdminBundle
- [ ] SonataDoctrinePhpcrAdminBundle
- [ ] SonataEasyExtendsBundle
- [ ] SonataFormatterBundle
- [ ] SonataIntlBundle
- [ ] SonataMediaBundle
- [ ] SonataNewsBundle
- [ ] SonataNotificationBundle
- [ ] SonataPageBundle
- [ ] SonataPropelAdminBundle
- [ ] SonataSeoBundle
- [ ] SonataTimelineBundle
- [ ] SonataTranslationBundle
- [ ] SonataUserBundle
- [ ] cache
- [ ] ecommerce
- [ ] exporter
- [ ] sonata-doctrine-extensions

**Comment by rawkode** [comment]
Holding off on doing anymore, as I'm not sure if I should be targetting 3.x or to continue with master. Advice, @core23 ?

**Comment by greg0ire** [comment]
Should definitely be done on master, but it says "After merging #165"

**Comment by rawkode** [comment]
Oops, totally misread the comment. I'll hold off and rebase when it's merged.

Thanks, @greg0ire :+1:

**Comment by Th3Mouk** [comment]
Just asking, are theses changes can be handled by the dev-kit ?

**Comment by greg0ire** [comment]
The composer.json file is not managed through dev-kit, and needs to be changed, so I think not.

**Comment by OskarStark** [comment]
@rawkode thanks for your PR's 👍 keep on contributing 😃

**Comment by greg0ire** [comment]
@core23 I ticked some boxes, please review my other PRs to get more :)

**Comment by core23** [comment]
Just reseted the list, because we should update the files the for >=PHP 7

**Comment by jordisala1991** [comment]
This is solved already, all repositories are perfectly setup with newer php versions.
