### ISSUE TITLE
Label: "Pending author" automation

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#21]
It would be great to add some automation for the "Pending author" label.

This label is used when we ask the author for something.

The problem is when the author responds on the issue/PR, the label is still here.

At the end, it's pretty hard to set priority when reviving issues/PRs lists.

What I'm proposing is to set up a kind of bot that will immediately remove the "Pending author" when the author send a message.

Maybe also when he push new commits?

**Comment by greg0ire** [comment]
I think instead of tagging these issues, we should simply close them, and kindly ask the author to reopen if he feels like answering.

**Comment by Soullivaneuh** [comment]
> I think instead of tagging these issues, we should simply close them, and kindly ask the author to reopen if he feels like answering.

I would prefer to not close issue each time we just want an answer.

But, if we have automation on this label, we will able to easily find issues with this label and not updated since a while so we can close them.

**Comment by greg0ire** [comment]
Might be a bit more friendly indeed :)
