### ISSUE TITLE
Cleanup .gitignore files

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#211]
We have some plattform files in the `.gitignore` file that should be removed. We should also use full paths for file exlusions (`/vendor` instead of `vendor`):
- [x] GoogleAuthenticator
- [x] SonataAdminBundle
- [x] SonataAdminSearchBundle
- [x] SonataBlockBundle
- [x] SonataCacheBundle
- [x] SonataClassificationBundle
- [ ] SonataClassificationMediaBundle
- [x] SonataCommentBundle
- [x] SonataCoreBundle
- [x] SonataDashboardBundle
- [x] SonataDatagridBundle
- [x] SonataDoctrineMongoDBAdminBundle
- [x] SonataDoctrineORMAdminBundle
- [x] SonataDoctrinePhpcrAdminBundle
- [x] SonataEasyExtendsBundle
- [x] SonataFormatterBundle
- [x] SonataIntlBundle
- [x] SonataMediaBundle
- [x] SonataNewsBundle
- [x] SonataNotificationBundle
- [x] SonataPageBundle
- [x] SonataPropelAdminBundle
- [x] SonataSeoBundle
- [x] SonataTimelineBundle
- [x] SonataTranslationBundle
- [x] SonataUserBundle
- [x] cache
- [x] ecommerce
- [x] exporter
- [ ] sonata-doctrine-extensions

**Comment by shulard** [comment]
Hello !

I think I've created an `.gitignore` update PR on each of the missing packages. Just one question about `sonata-project/SonataClassificationMediaBundle`, it seems empty for the moment do I need to create a `.gitignore` ?

**Comment by greg0ire** [comment]
Thanks for doing this huge chore! I think you can leave this bundle alone, the file will be created when necessary.

**Comment by shulard** [comment]
^^ no problem happy to help !

**Comment by greg0ire** [comment]
@core23 : how can we make sure @shulard gets the Hacktoberfest recognition? Should we create an issue on one of the repos and ask him to amend his commit message so that it auto-closes the issue?

**Comment by core23** [comment]
AFAIK, you should just like to an issue and get merged. Just recived the T-Shirt order mail today, also I was a little lazy with PRs.

**Comment by shulard** [comment]
Hello, don't worry about the Hacktoberfest recognition, I just received the T-Shirt order mail today 😄.

**Comment by shulard** [comment]
I've just pushed the new line order on all the PR (alphabetically sorted). 

I've a `/build` line on most of them but can't find a reference to that folder anywhere. Is it used ? Is the line must be removed from `.gitignore` ?
