### ISSUE TITLE
Workflow for backports

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#215]
Do we have any workflow for backports to the master branch? AFAIK we have many projects with missing PRs from the 3.x branch.

AFAIK @Soullivaneuh had a script which does this every night automatically, but some projects have problems so we have to do this ourself. What's the prefered way to do this? Fork the master branch and create PR to the master branch?

**Comment by greg0ire** [comment]
It there are conflicts, you must indeed fix them locally. IMO the best way to be sure your fixes are OK is to make a PR : if you push directly and you screw up somewhere, the build will be red. So I agree with you : 

1. start a new branch from master;
2. `git merge <stable_branch>`;
3. fix any conflicts;
4. push that and make a PR.

**Comment by sstok** [comment]
Maybe https://github.com/park-manager/hubkit/ `upmerge` can provide what you are looking for.

Sonata uses 3.x however instead of 3.1 so I'm not sure if the next version detection will work as expected 😃 this would have to be fixed first, properly how Composer handles relative versions.

But feel free to re-use the code logic for sonata/dev-kit 👍

**Comment by sstok** [comment]
https://github.com/sonata-project/dev-kit/blob/master/src/Console/Command/AutoMergeCommand.php#L93 No, except that HubKit does this locally rather then using the API, making it possible to resolve conflicts. It's more handwork though, I based of the GH tool used by the Symfony core team.

**Comment by greg0ire** [comment]
Would've been great to know that before developing dev-kit :P

**Comment by sstok** [comment]
GH is not open-source ;) I used Gush for a long time, but after to many issues and problems with the project itself I started something new (for GitHub only), it's still very young and I actually took some inspiration from Dev-kit 😄 there is another tool (planned), which is similar to dev-kit in terms of updating common files and setting-up webhooks/services, but that's currently only planned.

What I am very proud of with HubKit is the release command which can (finally!) create categorized changelog (keepachangelog.com) based on the [pull request merge information](https://github.com/park-manager/hubkit/issues/8). It's something I have wanted for so long.

**Comment by greg0ire** [comment]
> What I am very proud of with HubKit is the release command which can (finally!) create categorized changelog (keepachangelog.com) based on the pull request merge information. It's something I have wanted for so long.

Sounds like a killer feature indeed :)
