### ISSUE TITLE
Make docs easy to build

### ISSUE THREAD

**Issue by eerison** [sonata-project/dev-kit#2165]
Could we add a command in Makefile to install the requirements for docs?

for example

```
doc-requiments:
  apt install pip
  pip install -r docs/requirements.txt
```

**Comment by VincentLanglet** [comment]
I'm not sure about it.
Apt is for linux. On mac, I think it's `brew install pip` and I don't even know how it's installed on Windows.

So we can't provide a generic way to install it.

We could just provide
```
install:
     composer install

doc-install:
     pip install -r docs/requirements.txt
```
And let the developper install composer/pip by himself

**Comment by eerison** [comment]
> I'm not sure about it. Apt is for linux. On mac, I think it's `brew install pip` and I don't even know how it's installed on Windows.
> 
> So we can't provide a generic way to install it.
> 
> We could just provide
> 
> ```
> install:
>      composer install
> 
> doc-install:
>      pip install -r docs/requirements.txt
> ```
> 
> And let the developper install composer/pip by himself

But if it's required to install the docs, don't you think it should be into the Make file?
usually I install this into the docker container and usually it there isn't pip 😄

**Comment by VincentLanglet** [comment]
> But if it's required to install the docs, don't you think it should be into the Make file?

I never installed the docs locally.
Also, it's "required" to install the php dependencies but there is not composer install shortcut in the make file.

What I said is that we won't add `apt install pip` in the makefile since it won't work on every os.

**Comment by eerison** [comment]
well it's a start 😄 


when I try to install the docs, I'll see that it requires pip!
```
doc-install:
     pip install -r docs/requirements.txt
```

should I provide a PR?

**Comment by VincentLanglet** [comment]
> ```
> doc-install:
>      pip install -r docs/requirements.txt
> ```
> 
> should I provide a PR?

You can. Dunno what think @jordisala1991 about it.

But IMHO we add a command to install the doc, it could be consistent to add one for php dependencies too...

**Comment by jordisala1991** [comment]
We already have one for php dependencies right? is the composer install. Pip is to python what composer is to php.

**Comment by VincentLanglet** [comment]
> We already have one for php dependencies right? is the composer install. Pip is to python what composer is to php.

I meant an entry in the makefile.

**Comment by jordisala1991** [comment]
I thought we already had one command in the make file to install composer deps, fine by me, but TBH `composer install` will be already shorter than `make composer-install`

**Comment by VincentLanglet** [comment]
I was thinking

Make install: composer install
Make doc-install: pip ...

Yeah it's as short as composer install. But it kinda answer the question how to install such things, like we doing for docs
