### ISSUE TITLE
Merge diverged branches

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#221]
Some branches couldn't get merged into the master branch, because there are conflicts:

- [x] exporter ([20 commits](https://github.com/sonata-project/exporter/compare/master...1.x)) https://github.com/sonata-project/exporter/pull/136
- [x] SonataAdminBundle ([16 commits](https://github.com/sonata-project/SonataAdminBundle/compare/master...3.x)) https://github.com/sonata-project/SonataAdminBundle/pull/4238
- [x] SonataBlockBundle ([33 commits](https://github.com/sonata-project/SonataBlockBundle/compare/master...3.x)) https://github.com/sonata-project/SonataBlockBundle/pull/349
- [ ] SonataClassificationBundle ([23 commits](https://github.com/sonata-project/SonataClassificationBundle/compare/master...3.x)) https://github.com/sonata-project/SonataClassificationBundle/pull/260
- [x] SonataCoreBundle ([31 commits](https://github.com/sonata-project/SonataCoreBundle/compare/master...3.x)): https://github.com/sonata-project/SonataCoreBundle/pull/363
- [x] SonataMediaBundle ([42 commits](https://github.com/sonata-project/SonataMediaBundle/compare/master...3.x)) https://github.com/sonata-project/SonataMediaBundle/pull/1158
- [x] SonataSeoBundle ([9 commits](https://github.com/sonata-project/SonataSeoBundle/compare/master...2.x))
- [ ] SonataUserBundle ([29 commits](https://github.com/sonata-project/SonataUserBundle/compare/master...3.x))

**Comment by greg0ire** [comment]
I'm going to give the admin bundle a try.

**Comment by greg0ire** [comment]
Trying the block bundle…

**Comment by core23** [comment]
Closing this in favor of https://github.com/sonata-project/dev-kit/issues/229
