### ISSUE TITLE
Drop PHP 5 support completely

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#222]
We started to drop all unsupported versions on the latest master branches. Maybe we could / should drop support for PHP 5 completely, because the [active support ended yesterday](https://secure.php.net/supported-versions.php). [PHPUnit will drop PHP 5 support](https://github.com/sebastianbergmann/phpunit/wiki/Preparing-for-PHPUnit-6) too with their next major release.

Maybe we should do the same. There is no release plan for the next major versions, so this might be the right way.

**Comment by greg0ire** [comment]
> There is no release play for the next major releases

WAT

**Comment by greg0ire** [comment]
Maybe make a twitter poll for this? I feel this is kind of important.

**Comment by Soullivaneuh** [comment]
PHP 5.6 still have security support. We must not drop it before it ends IMHO.

**Comment by greg0ire** [comment]
Link to the twitter poll : https://twitter.com/core23de/status/817044245018185728 , please RT

**Comment by lsmith77** [comment]
imho its too early to drop php 5.6 support

**Comment by greg0ire** [comment]
Hmmm… so the poll went surprisingly strongly in favor of dropping php 5. If we consider the twitter crowd is representative enough of our user base and we are ready to piss off 6% of it, we can safely drop php 5. What do we do? @OskarStark @rande @dbu ? Thoughts?

**Comment by core23** [comment]
Refs https://github.com/sonata-project/dev-kit/pull/225

**Comment by dbu** [comment]
that is for the next major version? then i think its ok.

**Comment by core23** [comment]
Yes, for all next *major* releases. We have no release plan for this versions, so we have enough time to prepare the users.

**Comment by greg0ire** [comment]
This is deployed.

**Comment by TomasVotruba** [comment]
Awesome job!
