### ISSUE TITLE
Should we drop support for Symfony 2.3?

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#228]
Support for bug fixes in sf 2.3 has ended, and I think I found a new bug in Symfony that prevents us from running our test suites successfully if we want to support Twig 2 : see https://github.com/sonata-project/SonataCoreBundle/pull/371 . Since this is not a security issue, it will not get fixed, so what should be do about that?

1. Drop support for Symfony 2.3 ?
2. Continue support for Symfony 2.3, but stop running the sf 2.3 Travis job ?
3. Skip the particular tests that fails? What if other bugs show up?

**Comment by core23** [comment]
AFAIK we must keep symfony 2.3 in the stable branch, because it's a BC break. Same reason for old outdated php versions. 

Also I don't like it :(

**Comment by core23** [comment]
Solution 3 should be the preferred way

**Comment by greg0ire** [comment]
> AFAIK we must keep symfony 2.3 in the stable branch, because it's a BC break.

You should read this then : https://github.com/sonata-project/SonataAdminBundle/pull/4276#discussion_r96682693 :trollface:

**Comment by core23** [comment]
Wtf?

**Comment by greg0ire** [comment]
It would be great to find the original discussion we had about this, because apparently it wasn't very clear :P

**Comment by Soullivaneuh** [comment]
@greg0ire What would you mean by linking this?

> For Sonata, ATM, we just want to lock constraints and change them on major only for PHP, Symfony (because of main dependency and LTS support), and when we want to change a constraint for a next major bump (e.g. Twig ^2.0 instead of ^1.28).

So for Symfony, yes we must keep it for the current stable, remove it for next major.

BTW, it's already done.

So lest go for solution 3. :wink:

**Comment by greg0ire** [comment]
I mean that no, it isn't a BC-break

**Comment by greg0ire** [comment]
Solution 3 applied : https://github.com/sonata-project/SonataCoreBundle/pull/371
