### ISSUE TITLE
Our Backwards Compatibility Promise

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#236]
I am opening this issue on dev-kit because of this PR: https://github.com/sonata-project/SonataMediaBundle/pull/1196

IMO we should have our BC rules defined at some place. There is some work done in https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md#the-base-branch but it does not explain when is BC and when is not. 

As this is important when deciding what branch should target every PR and when we are going to see the changes on a new version, we should specify what is BC and what is a BC break. This might be a little opinionated but I think we should follow the same rules as Symfony because sonata is a Symfony bundle.

http://symfony.com/doc/current/contributing/code/bc.html

I can open a PR on dev-kit but I wanted to know first everyone thoughts.

**Comment by core23** [comment]
There should be a chapter for PHP version management which explains if / that we can drop old PHP versions on stable branches.

**Comment by greg0ire** [comment]
I think the sf BC promise is a good basis, but IIRC we are stricter in some cases. We should add these cases here, and maybe vote on them if they are controversial.

**Comment by jordisala1991** [comment]
I think the Contribution guide is really complete now, closing
