### ISSUE TITLE
support src/ and tests/ folder

### ISSUE THREAD

**Issue by dbu** [sonata-project/dev-kit#253]
many symfony bundles moved the php classes out of the repository root into a src folder, and tests into a tests folder.

a quick grep through dev-kit makes me thing that there are two places we would need to handle:

projects/.styleci.yml:    - 'Tests/Fixtures'
projects/.gitattributes.twig:Tests/* export-ignore

we could just duplicate those to also include tests (lowercase) in addition to Tests. the phpunit.xml file is affected the most, but that seems to not be centrally managed as far as i can tell.

**Comment by Soullivaneuh** [comment]
See #278
