### ISSUE TITLE
travis_wait is not found

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#256]
Most builds are broken right now 🚨 

The error message: 

> .travis/install_test.sh: 24: .travis/install_test.sh: travis_wait: not found

[The docs](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) say this isn't a command, but an exported function, maybe that's why it is not found, IIRC we invoke it a bit indirectly. It was introduced in #252

**Comment by greg0ire** [comment]
As discussed with @dbu on Slack, this seems to be a Travis issue: some jobs are using precise, and some other jobs are using a more recent version, with a missing `travis_wait`

**Comment by greg0ire** [comment]
Correction: all builds are using precise.

**Comment by dbu** [comment]
trying to contact travis-ci on twitter: https://twitter.com/dbu/status/893203827637268484

**Comment by greg0ire** [comment]
@dbu is there a build that passes where `travis_wait` . Not quite sure yet, but sometimes build are not run entirely because only non-php files have been changed.

**Comment by greg0ire** [comment]
I made a proof PR: https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/jobs/260918957

`travis_wait` seems to be recognized when used directly in `travis.yml`: https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/jobs/260918957#L329

**Comment by greg0ire** [comment]
I think we should add a boolean variable in the config telling whether to add `travis_wait`. Or maybe just revert the change and fix the root cause.

**Comment by greg0ire** [comment]
Root cause fixed.
