### ISSUE TITLE
Issue with relevant files check

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#258]
Most dev kit updates happen on files that will not trigger that check, so do proof PRs for dev-kit. That means some dev kit updates can break the build very badly, which happened twice in a row.

This can be fixed by removing the feature, and removing the files (not sure if dev-kit can do that, or if we would have to do it manually).

Another fix might be to include all the files managed by dev-kit in the files that trigger the build. What do you think?

**Comment by greg0ire** [comment]
With the relevance check, the group of builds an update gives is quite long though...

**Comment by VincentLanglet** [comment]
I'm not sure to understand the issue @greg0ire, is it related to https://github.com/sonata-project/dev-kit/issues/798#issuecomment-667570936

**Comment by greg0ire** [comment]
No, it's related to https://github.com/sonata-project/dev-kit/blob/1615ce63f1b7828b50f872ec171c7c665cc4b167/templates/project/.travis/check_relevant_test.sh#L9

For instance if we do something wrong with a shell file, we might not notice it because that check will cause some jobs to be simply skipped: https://github.com/sonata-project/dev-kit/blob/bb21eb0d3bcd8601487bf822d30b88cd3bf1405b/templates/project/.travis.yml.twig#L68

**Comment by VincentLanglet** [comment]
Ok.

You proposed to remove the feature. But I don't understand what is called a *relevant file*... 😅
Could you elaborate please ?

**Comment by greg0ire** [comment]
A relevant files is a file that is relevant to a given job. For instance, javascript files are not relevant to the `phpunit` job, and a PR changing only js files should not trigger that job.

**Comment by VincentLanglet** [comment]
I think we can close this since there is no `RELEVANT_FILES` and travis build anymore.
