### ISSUE TITLE
Releasing next major version

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#266]
This is a new PR with a priority list based on https://github.com/sonata-project/dev-kit/issues/216 for the next major releases:

Critical bundles, which are used in many other bundles and don't have any dependency on another sonata lib
- cache bundle
- exporter
- google auth
- datagrid bundle
- easy extends bundle

Bundles that should be released after the critical bundles
- <s>core bundle</s> depends on datagrid bundle
- doctrine extension
- notification bundle
- block bundle
- admin bundle(s)
- classification bundle
- media bundle
- user bundle
- intl bundle
- seo bundle
- formatter bundle

Uncritical bundles with no further internal usage
- news bundle
- page bundle

**Comment by jordisala1991** [comment]
This is duplicated of #216 

This will create a link on that issue, to not lose this information.

Closing
