### ISSUE TITLE
SonataClassificationMediaBundle needs the default labels

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#273]

**Comment by jordisala1991** [comment]
I think that we need to create SonataClassificationMediaBundle on packagist and then dev-kit will have access to it, and it will create everything needed

**Comment by core23** [comment]
We have a travis setup: https://packagist.org/packages/sonata-project/classification-media-bundle

**Comment by jordisala1991** [comment]
Closing, we already have those labels :)
