### ISSUE TITLE
SonataClassificationMediaBundle setup

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#275]
The following parts are missing:

- [x] Add packagist hook @rande 
- [x] Add coveralls hook @Soullivaneuh 
- [x] StyleCI settings?
- [x] TravisCI settings?
- [x]  Fix directory structure in `Makefile` and `.gitattributes`

**Comment by Soullivaneuh** [comment]
The StyleCI is already configured: https://styleci.io/repos/65559292

TravisCI to: https://travis-ci.org/sonata-project/SonataClassificationMediaBundle

**Comment by jordisala1991** [comment]
Everything is ready.

Closing.
