### ISSUE TITLE
docker-compose up fails on Windows

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/dev-kit#279]
Hey guys,

I am unable to run ./configure on windows but I think I set up everything as it should be.
My docker-compose.env looks like this:

> 
> UNIX_USERNAME=$(id -un)
> UNIX_GROUP=$(id -gn)
> UNIX_UID=$(id -u)
> UNIX_GID=$(id -g)
> 

When I do docker-compose up (and everything is built) I get this

> 
> Starting devkitmaster_data_1 ...
> Starting devkitmaster_data_1 ... done
> Starting devkitmaster_fpm_1 ...
> Starting devkitmaster_fpm_1 ... done
> Starting devkitmaster_nginx_1 ...
> Starting devkitmaster_nginx_1 ... done
> Starting devkitmaster_console_1 ...
> Starting devkitmaster_console_1 ... done
> Attaching to devkitmaster_data_1, devkitmaster_fpm_1, devkitmaster_nginx_1, devkitmaster_console_1
> fpm_1      | getent: invalid option -- 'g'
> fpm_1      | Try `getent --help' or `getent --usage' for more information.
> fpm_1      | Create group $(id -gn)
> console_1  | getent: invalid option -- 'g'
> fpm_1      | groupadd: invalid group ID '$(id -g)'
> console_1  | Try `getent --help' or `getent --usage' for more information.
> console_1  | Create group $(id -gn)
> console_1  | groupadd: invalid group ID '$(id -g)'
> devkitmaster_data_1 exited with code 0
> devkitmaster_fpm_1 exited with code 3
> devkitmaster_console_1 exited with code 3

Any idea where I can go to fix this?

**Comment by greg0ire** [comment]
Looks like docker on windows takes things a bit too literally. Try updating both docker and docker compose

**Comment by Soullivaneuh** [comment]
Dev-kit is just an internal project to help managing Sonata repositories.

No Windows support is planned here.

Regards.
