### ISSUE TITLE
Is the three branches system really worth it?

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#284]
Since #153 was written, voted and applied on some project, some of the @sonata-project/contributors already complain about this system.

The principal reason? Really heavy to maintain. And I can understand that.

So this is a simple vote issue:

:+1: To going back to the 2 roads branches.
:-1: To stay on the 3 roads branches.

If we go back to the 2 roads classic system, be warn that the schema will be like (**starting the next major**):

- `master`: The unstable branch, like actual (5.x for core-bundle)
- `stable`: For BC features, deprecation and bug fixes (4.x for core-bundle)

And nothing more. The legacy branch must not be maintained anymore and will not be managed by dev-kit.

Thanks to use reaction emoji to vote.

**Comment by greg0ire** [comment]
I'd like 3 branches, but with a backport system instead of a forward port, can you add this option?

**Comment by Soullivaneuh** [comment]
@greg0ire Would be a mess with dev-kit and general organisation.

This should be a very marginal option. Legacy branch should already be quite fixed. :-)

**Comment by greg0ire** [comment]
How would it be a mess???

**Comment by Soullivaneuh** [comment]
Maintaining but not merging branch would be hard to maintain if the bugfix concern legacy and current stable.

Yeah, we can cherry-pick, but this is not proper as merging.

In any case, bug fixes on legacy may be done without merge branches but only if it critical. E.g. the last legacy release does not work at all. But it should be exception and not encouraged on contributing note because it would be the same as the 3 roads way in this case. :wink: 

This is why I'm saying this will be marginal and don't have a place on the vote list.

BTW, if we vote yes to #285, the next major releasing would concern only internal breaking changes, so the major releasing frequency would be reduced.

**Comment by greg0ire** [comment]
> In any case, bug fixes on legacy may be done without merge branches but only if it critical. E.g. the last legacy release does not work at all. But it should be exception and not encouraged on contributing note because it would be the same as the 3 roads way in this case. :wink:

This changes everything

**Comment by jlamur** [comment]
On the admin bundle, there have never been any PR accepted on `2.x` (legacy). It's the same as having the 2 roads branches.

So, I'm :+1: to not change anything ;)

**Comment by Soullivaneuh** [comment]
> On the admin bundle, there have never been any PR accepted on `2.x` (legacy). It's the same as having the 2 roads branches.

Well, this is not really comparable as the `2.x` come from the "old way" and is strictly diverged from the current.

**Comment by jordisala1991** [comment]
IMO there should be some time between the release of the new stable and the drop support of the old one, because we should give some time to the people to adapt. Anyway im +1 to the 2 way instead of 3

**Comment by Soullivaneuh** [comment]
@jordisala1991 Adopting #285 too will reduce the major release needs IMHO.
