### ISSUE TITLE
Should we drop each vendor version support on minor releases?

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#285]
Simple question, tiny issue.

:+1: To drop vendor support even for PHP and SF on minor release.
:-1: To keep as we do today. Drop version support on next releases only.

My thought:

:+1: Because it's semver compliant, and Doctrine maintainers already follow this way.
:+1: Because it would be **much** simpler to maintain
:-1: Because we don't have minor branches, so we can't provide bug-fixes for older minors supporting older vendor versions.

In any case, if we decide to do that, we must wait a bit after vendor release before dropping support. BTW, if we can support older version without a lot of pain, we should keep it to make transition smoother.

:warning: This does not affect this rules: We **DO NOT** drop version support of still maintained PHP and SF version and we **MUST** keep at least on LTS SF version support (currently 2.8) for concerned projects.

**Comment by greg0ire** [comment]
To clarify, that would mean dropping php 5.3-5.5, and sf 2.3 on the stable branches, right? Will this policy apply on the current stable branches, or only starting with the next wave of major releases?

**Comment by Soullivaneuh** [comment]
> To clarify, that would mean dropping php 5.3-5.5, and sf 2.3 on the stable branches, right?

Right.

> Will this policy apply on the current stable branches, or only starting with the next wave of major releases?'

I don't see why this can't be apply to current stable branches.

**Comment by Soullivaneuh** [comment]
> BTW, if we can support older version without a lot of pain

Example: If PHP 7.2 goes out and our project perfectly work with PHP 7.0 and 7.1 without having to deal with BC condition (`method_exists`, `class_exists` etc...) we should not drop the support form composer right now.

**Comment by greg0ire** [comment]
> I don't see why this can't be apply to current stable branches.

I'm all for it, just wanted to clarify

**Comment by jordisala1991** [comment]
IMO if there is a good reason to drop some version of SF or PHP. We should be able to do it. Not as a: we will only be working with the latest version only, but to avoid things like having to deal with old PHP 5.3. Im +1 to have the power. But with a great power comes great responsibility

**Comment by greg0ire** [comment]
I think we should only use it for versions that are no longer maintained.

**Comment by Soullivaneuh** [comment]
@jordisala1991 Speciales rules for PHP and SF:

* PHP: Keep support for maintained versions (too late for 5.6, but we should not repeat this)
* Symfony: Support at least one LTS version (currently 2.8, nearly 3.4)

**Comment by greg0ire** [comment]
@OskarStark  please vote

**Comment by OskarStark** [comment]
sorry for the delay!
