### ISSUE TITLE
Readme is broken

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#291]
The `README.md` looks broken, if there is only one (or two branches):

<img width="550" alt="bildschirmfoto 2017-09-30 um 09 58 02" src="https://user-images.githubusercontent.com/3440437/31043949-f4c9d788-a5c5-11e7-9ab6-61cab01cc18f.PNG">

We should add some conditions to fix this.

**Comment by Soullivaneuh** [comment]
This is not "Broken", this was already discussed for other repos. I won't change the markdown file to twig template because we will loose the GitHub preview here.

This is not a big deal IMHO. Plus, the 3 branches system is going to be removed. (#284)
