### ISSUE TITLE
[RFC] Handle manual merges

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#307]
Sometimes when the dev-kit tries to merge changes to a higher branch (3.x => master), there are some merge conflicts in it.

ATM we have the problem that someone needs to make a direct push to the master branch without a PR.

My idea is, that the dev-kit will create a new `merge-3.x` branch on the corresponding project repo with all changes that got a merge conflict. Only this branch doesn't have any restrictions to our team, so we can rebase as we want. So we can resolve the conflict there and create PR afterwards or the dev-kit will do this if it is approved by the team.

Not sure if this is even possible. It's just a frist start to handle the problem.

**Comment by greg0ire** [comment]
> Only this branch doesn't have any restrictions to our team, so we can rebase as we want.

merge commit shouldn't be rebased (otherwise you loose the information about the commit having 2 parents).

**Comment by jordisala1991** [comment]
Actually we are handling this by doing a PR , getting an approval and manual push on master after. Maybe it could be documented.

**Comment by VincentLanglet** [comment]
> Actually we are handling this by doing a PR , getting an approval and manual push on master after. Maybe it could be documented.

Only team member can do a push to master, isn't it ?
The bad part is that contributor cannot help us on this. (But then, it's not needed to add this to the Contributing.md)

**Comment by VincentLanglet** [comment]
This issue is pretty old and I feel like the slack log help us a lot to track which project need to be merged manually.
This seems to be enough
