### ISSUE TITLE
Remove VersionEye integration

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#308]
VersionEye is dead: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/

So we should remove this from our projects:

- [ ] https://www.versioneye.com/php/sonata-project:cache
- [ ] https://www.versioneye.com/php/sonata-project:translation-bundle

**Comment by Soullivaneuh** [comment]
Are the services required on PR checks?

**Comment by greg0ire** [comment]
I don't think they are

**Comment by Soullivaneuh** [comment]
I'll take a look if this is causing issue later, but at least it's not a big deal to keep the config.

When the service will be dead, the Merge Request won't have any more notification from the service.

Rest In Peace VersionEye.
