### ISSUE TITLE
Symfony Flex integration

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#309]
It's still an alpha system, but it's great to have a note here.

We should consider proposing a Symfony Flex integration.

* https://symfony.sh/
* https://symfony.com/doc/current/setup/flex.html

Recipes can be added on this repository: https://github.com/symfony/recipes-contrib

This may be hard to do on current stable (or not), so this might be done after next major.

This issue is here for re-flexion ATM, feel free to comment all your concerns/ideas/warning/what-you-want! :+1:

**Comment by rande** [comment]
What are the blocker for not implementing flex recipes ?

**Comment by greg0ire** [comment]
I think it's unclear whether there is one until someone tries :P

**Comment by rande** [comment]
@greg0ire ok that was my feeling too

**Comment by rande** [comment]
Ok testing with an easy one: sonata-project/core-bundle - https://github.com/symfony/recipes-contrib/pull/151

**Comment by core23** [comment]
Do we have to create a new recipe, once we create a new minor release?

**Comment by scuben** [comment]
@core23 only if the recipe needs a change. otherwise it will be reused.

**Comment by core23** [comment]
So the recipe under `sonata-project/core-bundle/3.7/manifest.json` will work for all core-bundle version >=3.7?

**Comment by jordisala1991** [comment]
Core and admin are already configured for flex and have its recipe created, for the complex bundles with entities and multiple persistence layers, we have another issue that is more focused than this one: #397 

Closing this one.
