### ISSUE TITLE
Vote for the merge system

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#310]
GitHub currently give 3 merge options on Merge Requests:

* Classic merge commit. I think everybody know this one.
* Rebase merge. The commit structure is rewritten on top of master, this avoid the merge commit.
* Squash merge. All the commit are squashed onto one commit. The message may be edited.

Currently, only rebase and squash are enabled on Sonata repositories. This seems to not be pleasant to every one. So I would like to propose a vote.

First of all, let me honestly list the pros and cons of each side. Feel free to add your owns on comments.

## Classic merge

* Con: This add a new commit especially for merge, making the classic commit listing less clear.
* Con: We must ask contributors to squash commits they-self if necessary. Note, this is relevant only for one commit PR.
* Pro: The merged commits will always be the author commit and GPG signature will not be lost.

## Rebase and Squash merge

* Con: The commit are re-written. So we will lose integrity and GPG signature if any.
* Pro: No merge commit, clean history.
* Pro: The squash merge permit to make the merges easier, especially for contributors who are not familiar with git tools.

Personal opinion: I first preferred the rebase and squash system only for the commit history. For me, the classic merge was useless since the rebase was here. But this was before GPG signature. They are still here for releases. The question is: Do we really matter those signature for each commit?

Time to vote!

:+1: To keep the current rebase and squash system.
:-1: To avoid this system and going back to the classic merge commit.

Regards.

**Comment by greg0ire** [comment]
I think we should be able to choose what's best every time

**Comment by jordisala1991** [comment]
Rebase and squash -> regular PR
Classic merge -> manual merge PR

**Comment by Soullivaneuh** [comment]
> Rebase and squash -> regular PR
> Classic merge -> manual merge PR

Maybe on :unicorn: world, but I don't think this rule will be heavily applied. :trollface: 

> I think we should be able to choose what's best every time

Could you elaborate? The only thing I see with this option is not consistent git history with multiple merge methods.

**Comment by greg0ire** [comment]
> Could you elaborate? The only thing I see with this option is not consistent git history with multiple merge methods.

If a contributor uses GPG, me should probably prefer a classic merge, Otherwise, if he has more than one meaningful commit, then rebase, and otherwise, squash.

**Comment by Soullivaneuh** [comment]
> If a contributor uses GPG, me should probably prefer a classic merge, Otherwise, if he has more than one meaningful commit, then rebase, and otherwise, squash.

Well, here to, in a :unicorn: world... :stuck_out_tongue:

**Comment by jordisala1991** [comment]
Not sure what do you mean with 🦄 . For a lot of things we have certain rules we should follow to work together/contribute/review/etc... why can’t we define some rules for merging PR and apply them?

**Comment by Soullivaneuh** [comment]
> Not sure what do you mean with :unicorn: .

Maybe this is better? :trollface: 

![image](https://user-images.githubusercontent.com/1698357/31856012-625c3e2e-b6b7-11e7-82ea-be05f5c03971.png)

I'm talking about accident merging. This can happen to every one, even me or @rande for example.

When it's done a the code we can revert it. We can rewrite a git commit on a protected branch.

**Comment by jlamur** [comment]
IMO, it's better to have merge commits for the commit history.
You can always use `git log --merges` to have a clean list.

**Comment by Soullivaneuh** [comment]
> You can always use `git log --merges` to have a clean list.

I'm not talking about git command only, but also git history on github.

**Comment by VincentLanglet** [comment]
Squash merge seems to be the new standard
