### ISSUE TITLE
[RFC] Remove docs from artifact

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#314]
According to @rande's [comment](https://github.com/sonata-project/dev-kit/pull/281#issuecomment-339116500) I would start a vote for the docs.

Votes:
👍 We should include the docs folder in any case, so the developer could read the docs, also if no internet is available.
👎 We should remove the docs from the artifact to reduce the total file size (of a docker / vagrant container)
😄 We should decide in each case. Please leave a comment on this

cc @sonata-project/contributors

**Comment by greg0ire** [comment]
It varies a lot, but in some cases, like the block bundle, the docs account for a huge part of the filesize, hence my vote.
