### ISSUE TITLE
PHP support : stable branches and minor releases

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#315]
The new version dropping policy seems to be to much rude with PHP version according to the community feedback.

So, to make it clear and buried, here is a last vote.

Which PHP version should we keep supporting on the **stable** branch (e.g. sonata-admin 3.x while I'm writing this issue)?

:+1: For PHP versions on the **green** zone: http://php.net/supported-versions.php
:-1: For PHP versions on the **orange** zone: http://php.net/supported-versions.php
:confused: For lowest PHP version of last LTS OSes like Ubuntu.

Please also vote on #316  for the unstable branches (:warning: vote options are different).

**Comment by Soullivaneuh** [comment]
:warning: Please be aware that by talking about stable branch, we are talking about **minor** releases. (x.**Y**.z) :warning:

**Comment by core23** [comment]
Side note: The latest stable PHP version for Red Hat Enterprise is PHP 7.0

**Comment by greg0ire** [comment]
Ok so it's pretty clear that we are alienating half our userbase right now. Let's add support for 5.6 back on stable.

**Comment by greg0ire** [comment]
I'm creating a board for this right now: https://github.com/orgs/sonata-project/projects/4

**Comment by greg0ire** [comment]
Stopping until we are sure this is where we are headed.

**Comment by Soullivaneuh** [comment]
@greg0ire Proposition:

- Rolling back the configuration on dev-kit.
- Wait dev-kit to dispatch PR with updated configuration for Travis.
- Fix the compatibility on each PR.

WDYT? As you want.

**Comment by greg0ire** [comment]
Sound like a good plan, I can change my script to checkout the dev-kit branch, apply the changes and push

**Comment by Soullivaneuh** [comment]
Also, the CONTRIBUTING file must be updated.

**Comment by Soullivaneuh** [comment]
Ok I'll update the dev-kit configuration right now.

**Comment by Soullivaneuh** [comment]
Also, for each dev-kit pull request concerning this branch, please add a `minor` label and this change-log:

```markdown
### Changed
- Rollback to PHP 5.6 as minimum support.
```
