### ISSUE TITLE
Add a rule about abstract test case

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#331]
Public test cases should not be prefixed by `Abstract`. See https://github.com/sonata-project/SonataBlockBundle/issues/425

We should add an entry to the guide about this.

**Comment by greg0ire** [comment]
Why not?

**Comment by Soullivaneuh** [comment]
As usual, we follow SF coding style and no `Abstract` prefix is used on Symfony, neither on PHPUnit.

Sample: https://github.com/symfony/symfony/blob/ba3b17719272e614732a3d1323b556cf32da8dfb/src/Symfony/Component/Form/Test/TypeTestCase.php#L18

**Comment by greg0ire** [comment]
Ok :+1: 
But do you know why they did that?

**Comment by Soullivaneuh** [comment]
@greg0ire I guess to follow PHPUnit convention about this part?

**Comment by greg0ire** [comment]
probably

**Comment by jlamur** [comment]
Is prefixing abstract classes with `Abstract` a PSR rule or a SF rule?
I thought I've read it but I can't find it on the PSR.
I can even find an example on the PSR-2 where an abstract class is not prefixed with `Abstract`: http://www.php-fig.org/psr/psr-2/#45-abstract-final-and-static

**Comment by jlamur** [comment]
It's a SF rule: http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

**Comment by jlamur** [comment]
@Soullivaneuh You probably found that was created too early to comply with the SF rule.

This class, for example, follow the convention: https://github.com/symfony/symfony/blob/ba3b17719272e614732a3d1323b556cf32da8dfb/src/Symfony/Component/Form/AbstractExtension.php

**Comment by Soullivaneuh** [comment]
![image](https://user-images.githubusercontent.com/1698357/32504252-a68ac748-c3df-11e7-895f-323a906976c8.png)

**Comment by greg0ire** [comment]
> Yes, but clearly not for test case. The official documentation may be updated for it in this case.

Please make a docs PR first, so that we know what this is about, and if it is indeed a good practice.

**Comment by Soullivaneuh** [comment]
> Please make a docs PR first, so that we know what this is about

AFAIK, the incomplete doc is a hermetic issue, you can clearly see that the Abstract prefix is not used for test cases.

**Comment by Soullivaneuh** [comment]
I'll open an issue about missing documentation, but this change nothing for this one.

**Comment by greg0ire** [comment]
I don't think we should blindly adopt *de facto* standards as found in the code. Especially if we are unsure what reasons that lead to them.

**Comment by Soullivaneuh** [comment]
We are not talking about a single test case class having this name format here and some are recent. It's clear it's not a mistake.

**Comment by greg0ire** [comment]
What's unclear is the reasons behind it.

**Comment by Soullivaneuh** [comment]
https://github.com/symfony/symfony-docs/pull/8600
