### ISSUE TITLE
Dropping visual debt phpdoc

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#345]
I propose we remove phpdoc comments that do not bring any information. Symfony is starting to do it (not that it should matter, but hey).

Before:

```php
    /**
     * Constructor.
     *
     * @param string                           $token            A token
     * @param array                            $servers          An array of servers
     * @param RouterInterface                  $router           A router instance
     * @param string                           $purgeInstruction The purge instruction (purge in Varnish 2, ban in Varnish 3)
     * @param null|ControllerResolverInterface $resolver         A controller resolver instance
     * @param null|ArgumentResolverInterface   $argumentResolver
     */
    public function __construct(string $token, array $servers, RouterInterface $router, string $purgeInstruction, ControllerResolverInterface $resolver = null, ArgumentResolverInterface $argumentResolver)
    {
        $this->token = $token;
        $this->servers = $servers;
        $this->router = $router;
        $this->purgeInstruction = $purgeInstruction;
        $this->resolver = $resolver;
        $this->argumentResolver = $argumentResolver;
    }
```

After:

```php
    /**
     * @param string                           $purgeInstruction The purge instruction (purge in Varnish 2, ban in Varnish 3)
     * @param null|ControllerResolverInterface $resolver
     * @param null|ArgumentResolverInterface   $argumentResolver
     */
    public function __construct(string $token, array $servers, RouterInterface $router, string $purgeInstruction, ControllerResolverInterface $resolver = null, ArgumentResolverInterface $argumentResolver = null)
    {
        $this->token = $token;
        $this->servers = $servers;
        $this->router = $router;
        $this->purgeInstruction = $purgeInstruction;
        $this->resolver = $resolver;
        $this->argumentResolver = $argumentResolver;
    }
```

Note that the 2 last comment can disappear when dropping php < 7.1, because we can use the `?ArgumentResolverInterface`, it's arguably already visible right now because of the `= null` part.

As a bonus, should be also adopt multiline signatures, this would become the gorgeous following with php 7.1:

```php
    /**
     * @param string $purgeInstruction The purge instruction 
     *                                 (purge in Varnish 2, ban in Varnish 3)
     */
    public function __construct(
        string $token,
        array $servers,
        RouterInterface $router,
        string $purgeInstruction,
        ?ControllerResolverInterface $resolver = null,
        ?ArgumentResolverInterface $argumentResolver = null
    ) {
        $this->token = $token;
        $this->servers = $servers;
        $this->router = $router;
        $this->purgeInstruction = $purgeInstruction;
        $this->resolver = $resolver;
        $this->argumentResolver = $argumentResolver;
    }
```

👎 to keep phpdocs as is
👍 to remove redundant docs as described
❤️ to also remove it for nullable arguments

**Comment by Soullivaneuh** [comment]
> Symfony is starting to do it (not that it should matter, but hey).

It should, as usual, no need to troll at each issue. :-)

Where did you see that BTW?

**Comment by greg0ire** [comment]
I wouldn't want people to think that I condone following every sf standard for the sake of it. And it's not for trolling, I really am sincere whem I think it should not matter.

Here is a link: https://github.com/symfony/symfony/pull/24611

**Comment by Soullivaneuh** [comment]
> I wouldn't want people to think

Sonata issues are not here for that, you have dev.to or something else for that. ;-)

Anyway, the proposal seems good to me.

**Comment by greg0ire** [comment]
Maybe yeah :P I just wanted to make clear that I did not change my mind on that issue, but indeed, a blog post might be worth it someday.

**Comment by core23** [comment]
I voted for 👎 because they will be autogenerated by PhpStorm and other IDEs

**Comment by greg0ire** [comment]
I think IDEs should change too

**Comment by core23** [comment]
That's right. But from the current point of view: 👎

**Comment by greg0ire** [comment]
Is there no way to configure that?

**Comment by jlamur** [comment]
Would you like to also remove `{@inheritdoc}` comments?

--------
```php
/**
 * {@inheritdoc}
 */
protected function foo()
{
    return 'bar';
}
```

would then be:
```php
protected function foo()
{
    return 'bar';
}
```
--------
but:
```php
/**
 * {@inheritdoc}
 * 
 * @param string $var An usefull message.
 */
protected function foo(string $var)
{
    return 'bar';
}
```

would stay as it.

--------
Please vote :+1: or :-1:.

**Comment by jlamur** [comment]
Would you like to also remove useless comments on `@param`?

------
```php
/**
 * @param null|FooInterface $foo A foo interface.
 */
protected function bar($foo)
{
    // ...
}
```

would then be:
```php
/**
 * @param null|FooInterface $foo
 */
protected function bar($foo)
{
    // ...
}
```

because `A foo instance` adds no valuable information.

------
Please vote 👍 or 👎.

**Comment by Soullivaneuh** [comment]
> Would you like to also remove `{@inheritdoc}` comments?

@jlamur What do you mean by that? If a method inherit from another one, you must set this tag. You can't control what will happen to the parent phpdoc later.

And same here for those kind of propositions, the Symfony style must be followed.

For the second one (useless comment), I think it make sense and is already the case. Commented var are not mandatory AFAIK.

**Comment by jlamur** [comment]
@Soullivaneuh 

https://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag

> Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
>
> However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard `@inheritDoc` that will serve that purpose.

**Comment by greg0ire** [comment]
tautologic . This issue will now show up when typing "tautologic"
