### ISSUE TITLE
Create next major for the user bundle

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#346]
Symfony 4 will become stable soon, but our user bundle is still stucked on sf2. 

The problem is, that the FOS user bundle made a major release for the sf3 and refactored a lot of stuff. So we can't support sf2 and sf3 with one major version.

IMHO we have the following options:
👍 create a new major release **only for the user bundle**, so we can use sf3 in our other projects
👎 create releases of **all our own depending bundles**: https://github.com/sonata-project/SonataUserBundle/blob/3.x/composer.json#L22-L27

😕  find any other way (please comment)

**Comment by core23** [comment]
Please vote @sonata-project/contributors

**Comment by greg0ire** [comment]
IMO the right solution for this is 2 major releases, one right now, and another quite soon.

**Comment by Soullivaneuh** [comment]
Ok for the next major, it's a very special case. Just wait december for PHP 7.0 EOL.

**Comment by core23** [comment]
> Ok for the next major, it's a very special case. Just wait december for PHP 7.0 EOL.

Why would you waste more time... There is ever a reason to not release a bundle. We should finally do this step. This is not a frozen version. We could release a new major version in a shorter term

**Comment by greg0ire** [comment]
Yeah we must quit being afraid of releasing majors.

**Comment by Soullivaneuh** [comment]
@core23 Simply because I don't want to have another people yelling because we are dropping a supported version of PHP.

7.0 active support will be dropped in 13 days, we can wait 13 little days.

**Comment by core23** [comment]
Sorry, but this kind of release management really starts to pissing me off...

As I said, we will ever find a reason to not release something. Next time we will wait for a new symfony version, a new doctrine version, a new twig version, ... We waited long enough!

> 7.0 active support will be dropped in 13 days, we can wait 13 little days.

Is supporting PHP 7.0 vs. PHP 7.1 really a major step for you?

**Comment by Soullivaneuh** [comment]
> Is supporting PHP 7.0 vs. PHP 7.1 really a major step for you?

Not for me, this is why I proposed #285 and this was massively refused by the users community and made interminable discussions on Slack to finally revert what we done (#315).

So I prefer to wait 13 days to prove we really apply the final policy about this (see contributing) and don't have any issue in the future.

But if this piss you off and want to release it now, then it may be release now. But I'll let handle you to answer why we don't follow the policy again.

Trust me, if it was only me, PHP 7.1 will be already required on stable release as proposed in #315  because it's semver compliant.

**Comment by Soullivaneuh** [comment]
Another solution to release quickly and stay in accordance with our policy would be to go back to PHP 7.0.

Is that what you proposed @greg0ire? https://github.com/sonata-project/dev-kit/issues/346#issuecomment-345515338

But I don't think it worth it for 13 days, but if you want to handle it that way, why not.

**Comment by jordisala1991** [comment]
I prefer to wait 13 days

**Comment by greg0ire** [comment]
I don't know to what extent the code is 7.0-incompatible (it's probably not). several things:

- dropping major versions of php on a major version of our software is completely ok with everybody
- if you allow backports, you still effectively keep support down to php 5.6
- here we need 2 majors to close the gap, one to allow users to use sf 3, another that will require more than 13 days of work: sf4 compat, exporter release, cache release, and other sonata deps I forget release

**Comment by Soullivaneuh** [comment]
> (it's probably not)

Well, then just wait 13 days and user-bundle will be the first repository to have a major.

I let you ping my Slack until my death if I don't do it. :trollface:

**Comment by core23** [comment]
We have a new stable release
