### ISSUE TITLE
Archive projects

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#347]
I would like to discuss if we should deprecate and archive some projects, because we don't have enough man power to maintain all of the bundles.

Some bundles are replaceable, because there are far better (maintained) libs out now:

- ecommerce bundle (http://sylius.org/)
- cache bundle / lib
- sandbox (sf flex should do this)

Some projects should be archived:
https://github.com/sonata-project/SonataPropelAdminBundle
https://github.com/sonata-project/SonataMarkItUpBundle
https://github.com/sonata-project/sonata-composer
https://github.com/sonata-project/sandbox-build
https://github.com/sonata-project/SonatajQueryBundle
https://github.com/sonata-project/composer-archive-creator
https://github.com/sonata-project/stats
https://github.com/sonata-project/SonataGoutteBundle
https://github.com/sonata-project/SonataBluePrintBundle
https://github.com/sonata-project/php-travis-client
https://github.com/sonata-project/sonata-capistrano

**Comment by jordisala1991** [comment]
Careful with ecommerce, I am not using it, but there are some people that rely on that solution

**Comment by greg0ire** [comment]
For cache it would be great to make it PSR-6 compatible, and to rely on PSR-6 interfaces on other bundles, so that people could move away from it easily. I don't know if that makes sense...

**Comment by core23** [comment]
132 downloads this month... That's not much. Most of the downloads could be travis CI

**Comment by Soullivaneuh** [comment]
@core23 Some of the projects of this list are already deprecated (see description).

Some others will be deprecated soon. For the rest, I'll talk with @rande for it.

For the sandbox, it would be great to move it to something automated on Travis for each bundle to test.

**Comment by rande** [comment]
Hello,

I think those projects can be archived:
- https://github.com/sonata-project/SonataPropelAdminBundle
- https://github.com/sonata-project/SonataMarkItUpBundle
- https://github.com/sonata-project/sonata-composer
- https://github.com/sonata-project/sandbox-build
- https://github.com/sonata-project/SonatajQueryBundle
- https://github.com/sonata-project/SonataGoutteBundle
- https://github.com/sonata-project/SonataBluePrintBundle
- https://github.com/sonata-project/sonata-capistrano
- https://github.com/sonata-project/stats
- https://github.com/sonata-project/composer-archive-creator

The ``https://github.com/sonata-project/php-travis-client`` is used by the sonata-project website as some fields were missing. Maybe the library is now uptodate.

Cache lib has specific method signatures used in the PageBundle/CacheBundle. Not sure it is a good idea to remove them from now.

The ecommerce need to be kept, I will see what we can do about this bundle.

**Comment by core23** [comment]
> Some of the projects of this list are already deprecated (see description).

I'm not talking about a textual deprecation. See: https://github.com/blog/2460-archiving-repositories

**Comment by core23** [comment]
> The ``https://github.com/sonata-project/php-travis-client`` is used by the sonata-project website as some fields were missing. Maybe the library is now uptodate.

This projects looks dead. Last commit is from March 2012! If this is used by the website, maybe we should move this to gitlab too?

**Comment by Soullivaneuh** [comment]
> I'm not talking about a textual deprecation. See: https://github.com/blog/2460-archiving-repositories

Indeed, I didn't know this feature exists.

**Comment by Soullivaneuh** [comment]
@rande The listed project must be marked as abandoned on packagist to. Could you please handle that or share the access to me?

**Comment by Soullivaneuh** [comment]
All the projects listed by @rande are now archived.

Packagist must be checked and updated for abandoned packages and then we may close this issue.
