### ISSUE TITLE
Multiline signature counter proposal

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#349]
@Soullivaneuh doesn't like the fact that I hijack his issue, so here's a new one, might be clearer / better anyway indeed.

So here is my counter-proposal: allow multiline signatures when the line is longer than 120 characters and do not wait for a fixer to exist before allowing it. That's sane and simple. Please vote for or against.

My main point is that you should not confuse consistency, and deliberately not using one tool of your toolbox. You don't always have to choose, just like for `sprintf` vs encapsed strings vs concatenation, some are better suited to some situations.

**Comment by Soullivaneuh** [comment]
Method signatures are not comparable to `sprintf` usage or whatever.

Having them one-lined give a visual consistency of the code structure. This consistency must be kept and this proposition as is does not keep it.

**Comment by greg0ire** [comment]
> This consistency must be kept and this proposition as is does not keep it.

That's your opinion, please don't make it sound like it should be anything more.

**Comment by Soullivaneuh** [comment]
Not only a matter of opinion. The consistency of one-lined signature method is also why Symfony choose it AFAIK and this will be kept. Unless I'm wrong and it is not the reason, we have to keep this consistency.

**Comment by greg0ire** [comment]
> The consistency of one-lined signature method is also why Symfony choose it AFAIK and this will be kept

Source or it did not happen.

**Comment by Soullivaneuh** [comment]
> Source or it did not happen.

Can't retrieve, this is why I told "Unless I'm wrong".

But whatever, do you vote. I'll not fight anymore for this time, quite boring.

**Comment by greg0ire** [comment]
@jlamur @jordisala1991 @OskarStark please cast your vote

**Comment by jordisala1991** [comment]
Done, if the line is bigger than 120 chars, just multiline it. Not sure why this cannot apply to signatures

**Comment by greg0ire** [comment]
It's official everyone! 🎉

**Comment by Soullivaneuh** [comment]
Well, this bad choice can be official after a PR on contributing guide.

**Comment by greg0ire** [comment]
I'm on it!
