### ISSUE TITLE
remove coding style line

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#356]
See #355 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3168

**Comment by VincentLanglet** [comment]
I saw you started https://github.com/greg0ire/PHP-CS-Fixer/commit/da28d7a32d918ed732eae03ca0590bddd796bf73
What was missing to create a PR ?

**Comment by greg0ire** [comment]
Time and energy I suppose.

**Comment by VincentLanglet** [comment]
Maybe we should close this issue then ?

**Comment by greg0ire** [comment]
Sure
