### ISSUE TITLE
XMLLint is not working anymore

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#359]
https://travis-ci.org/sonata-project/SonataUserBundle/jobs/311259638#L527

It seems the binary is no longer provided.

Was introduced in #144.

Man ref: http://xmlsoft.org/xmllint.html

**Comment by greg0ire** [comment]
`xargs` would probably do a better job:

```
find . -name '*'|xargs missingBinary
xargs: missingBinary: No such file or directory
```
