### ISSUE TITLE
Use gitmate

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#360]
Gitmate is a tool to help you organize (open source) projects by auto tagging issues and close duplicate ones. It also pings / closes issues with no further action

https://gitmate.io/report/https:%2F%2Fgithub.com%2Fsonata-project%2FSonataAdminBundle

**Comment by Soullivaneuh** [comment]
To be tested. But I'm not a fan of the auto-closing part.

**Comment by jordisala1991** [comment]
I just tested it and I cant find a good usage of it, since it shows duplicates but of already closed issues. And the free plan dont cover our usage.

Closing for now, if you think we should give it a try regardless of this, please reopen.
