### ISSUE TITLE
Setup Slack hook with dev-kit

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#365]
The authenticated mode does not work well because of permission issue.

![image](https://user-images.githubusercontent.com/1698357/33667476-3c245598-da9d-11e7-9e60-00480a00b02c.png)

**Comment by jordisala1991** [comment]
In my case, Slacks let's me authenticate with Github. The problem is that I am not the admin of all those sonata repositories and it does not let me add them to the hook.

**Comment by Soullivaneuh** [comment]
@jordisala1991 Yes, this is the issue. SonataCI is admin of all repositories, this is why I would like to setting up that way.

**Comment by VincentLanglet** [comment]
The hook works fine with every other repository. I'm not sure to understand the difference of dev-kit ?
Do you know how to fix this @OskarStark ?

**Comment by jordisala1991** [comment]
I think this issue is obsolete, devkit is pushing messages to slack without problem.

**Comment by VincentLanglet** [comment]
> I think this issue is obsolete, devkit is pushing messages to slack without problem.

Not for the dev-kit repository.
There is no notifications when someone open an issue/post a message or do anything in this repository.
And I dunno why.

**Comment by VincentLanglet** [comment]
Looking at the current activity of the slack, the issue is not worth it
