### ISSUE TITLE
[RFC] Twig namespaced paths in templates

### ISSUE THREAD

**Issue by fracsi** [sonata-project/dev-kit#374]
In `symfony-flex` the directory structure is a little different than the normal symfony skeleton.

It uses the `templates` folder in the root directory for the twig templates. You can override third-party bundle templates in `templates/bundles/[BUNDLENAME]/`, but twig can only find templates if they are referenced with the new namespaced paths. (https://symfony.com/doc/2.8/templating/namespaced_paths.html)

The old syntax that is used by SonataAdmin (e.g.: `SonataAdmin::standard_layout`), is resolved by the symfony/framework-bundle.

The ideal solution would be to use the new namespace syntax everywhere.

Original issue from SonataAdminBundle: https://github.com/sonata-project/SonataAdminBundle/issues/4761

**Comment by core23** [comment]
Will this work in symfony 2.8 too?

**Comment by enleur** [comment]
- [ ] https://github.com/sonata-project/SonataAdminBundle
- [ ] https://github.com/sonata-project/SonataUserBundle
- [x] https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle
- [ ] https://github.com/sonata-project/SonataDoctrineORMAdminBundle
- [ ] https://github.com/sonata-project/SonataPageBundle
- [ ] https://github.com/sonata-project/SonataNewsBundle
- [ ] https://github.com/sonata-project/SonataCoreBundle
- [ ] https://github.com/sonata-project/SonataBlockBundle
- [ ] https://github.com/sonata-project/SonataIntlBundle
- [ ] https://github.com/sonata-project/SonataNotificationBundle
- [ ] https://github.com/sonata-project/SonataClassificationBundle
- [ ] https://github.com/sonata-project/SonataFormatterBundle
- [ ] https://github.com/sonata-project/SonataSeoBundle
- [ ] https://github.com/sonata-project/SonataTranslationBundle
- [ ] https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle
- [ ] https://github.com/sonata-project/SonataMediaBundle
- [ ] https://github.com/sonata-project/SonataCommentBundle
- [ ] https://github.com/sonata-project/SonataDatagridBundle
- [ ] https://github.com/sonata-project/SonataDashboardBundle
- [ ] https://github.com/sonata-project/SonataArticleBundle

**Comment by jordisala1991** [comment]
It would be nice to know which bundles are missing. I know that ecommerce is missing for sure, probably sandbox too, but there could be more
