### ISSUE TITLE
Make FlintCI status required

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#376]
And remove the Travis lint commands which duplicate the FlintCI job.

To be done later, after some testing.

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors Did you reveal any issue on FlintCI since the integration?

**Comment by kunicmarko20** [comment]
Nop, it was fine in the past few months. IIRC we need to enable xml lint and us can remove travis job

**Comment by core23** [comment]
We don't need this if we migrate everything to GitHub Actions #532
