### ISSUE TITLE
CS: List of useful php fixers to add

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#379]
(Changelog read until from 2.8 to 2.10)

- backtick_to_shell_exec
- multiline_comment_opening_closing
- multiline_whitespace_before_semicolons (with `new_line_for_chained_calls` strategy)
- explicit_string_variable
- static_lambda
- php_unit_test_annotation

**Comment by OskarStark** [comment]
Do we still need some of them or shall we close here?
