### ISSUE TITLE
Decouple sonata-project bundles from Templating Component, Stage 1

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/dev-kit#380]
Using `templating` service is a main barrier for creating a recipe for Symfony Flex. This service can be activated only by configuring `framework.templating` manualy, and there is no way how to turn in on automaticaly. Also, i believe, Templating Component will be deprecated soon, so all sonata-project bundles must switch from `templating` service to `twig` in next major release (without BC breaks in current branch).

There are 24 bundles, i splited them into three groups.

Bundles, that uses SonataBlockBundle:
---

There is a plan how to use Templating Component without "templating" service for SonataBlockBundle: https://github.com/sonata-project/SonataBlockBundle/issues/456.

- [x] After https://github.com/sonata-project/SonataBlockBundle/pull/457 and https://github.com/sonata-project/SonataBlockBundle/pull/466 will be merged and released, all bundles, that uses SonataBlockBundle, should be updated too:

1. Dependency to `sonata-project/block-bundle` must be modified/added
2. Change all template names to Twig namespaced syntax from `BundleNameBundle:directory:filename.html.twig` to `@BundleName/directory/filename.html.twig`

    We should search `Bundle:` in `docs`, `src` and `tests` directories and rename all template references there.

3. Switch from `templating` service to `sonata.templating`

    We should search `templating` in `src/Resources/config` and rename argument service id. Also we should search for `templating` in `src` directory to find `$this->getContainer()->get('templating');` there

- [x] [AdminBundle](https://github.com/sonata-project/SonataAdminBundle/pull/4897)
- [x] [ArticleBundle](https://github.com/sonata-project/SonataArticleBundle/pull/68) (requires BlockBundle indirectly)
- [x] [CommentBundle](https://github.com/sonata-project/SonataCommentBundle/pull/107)
- [x] [DashboardBundle](https://github.com/sonata-project/SonataDashboardBundle/pull/127)
- [x] [DoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/794)
- [x] [DoctrinePhpcrAdminBundle](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/517)
- [x] [FormatterBundle](https://github.com/sonata-project/SonataFormatterBundle/pull/315)
- [x] [MediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/1373)
- [x] [NewsBundle](https://github.com/sonata-project/SonataNewsBundle/pull/428)
- [x] [PageBundle](https://github.com/sonata-project/SonataPageBundle/pull/945)
- [x] [SeoBundle](https://github.com/sonata-project/SonataSeoBundle/pull/259)
- [x] [TimelineBundle](https://github.com/sonata-project/SonataTimelineBundle/pull/159)
- [x] [TranslationBundle](https://github.com/sonata-project/SonataTranslationBundle/pull/217)
- [x] [UserBundle](https://github.com/sonata-project/SonataUserBundle/pull/1000) (requires BlockBundle indirectly)

Other bundles:
---

These bundles does not use BlockBundle, but somehow uses Templating Component and should be updated:

1. Switch template references to Twig namespaced syntax

    We should search `Bundle:` in `docs`, `src` and `tests` directories and rename all template references there.

- [x] [ClassificationBundle](https://github.com/sonata-project/SonataClassificationBundle/pull/380)
- [x] [DatagridBundle](https://github.com/sonata-project/SonataDatagridBundle/pull/121)
- [x] [DoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/273)
- [x] [IntlBundle](https://github.com/sonata-project/SonataIntlBundle/pull/203)

Do nothing:
---

- [X] [AdminSearchBundle](https://github.com/sonata-project/SonataAdminSearchBundle)
- [X] [CacheBundle](https://github.com/sonata-project/SonataCacheBundle)
- [X] [ClassificationMediaBundle](https://github.com/sonata-project/SonataClassificationMediaBundle)
- [X] [CoreBundle](https://github.com/sonata-project/SonataCoreBundle)
- [X] [EasyExtendsBundle](https://github.com/sonata-project/SonataEasyExtendsBundle)
- [X] [NotificationBundle](https://github.com/sonata-project/SonataNotificationBundle)

**Comment by jordisala1991** [comment]
Isnt it better to make the admin bundle or core the bundle that implements this new sonata.templating?

**Comment by covex-nn** [comment]
I've implemented `sonata.templating` in https://github.com/sonata-project/SonataBlockBundle/pull/457 for BlockBundle because BlockBundle uses Templating Component, and CoreBundle does not. So, if there is a bundle, that uses CoreBundle, but does not use BlockBundle it would recieve `symfony/templating` too with all other deps (and this is not good, i think). AdminBundle is not a right place for `sonata.templating` service too, because not so much bundles has `sonata-project/admin-bundle` as a dependency in composer.json

We could even create a new repository for `sonata.templating`. But this service is a temporary solution on a way between `templating` and `twig`. It will not be used in master branch and it will be removed in future master branch. So, a new repository is unnecessary too.

**Comment by covex-nn** [comment]
I found (fix me) that only [ArticleBundle](https://github.com/sonata-project/SonataArticleBundle) and [UserBundle](https://github.com/sonata-project/SonataUserBundle) uses `templating` service and does not uses BlockBundle. These bundles could be easily switched from `templating` to `twig` in next major release. Not sure about current stable branches.

**Comment by covex-nn** [comment]
@jordisala1991 i've updated issue. I downloaded all 24 non-archived bundles and searched for `templating` and `Bundle:` there. So, now we have full list of bundle with todo.

And BlockBundle is a right place for `sonata.templating` service, because there is no bundles, that uses Templating Component and needed this service to start decouple from `templating`

**Comment by covex-nn** [comment]
- [X] 18 PRs were created :godmode: 
- [ ] [DoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/273), awaiting for a new release of AdminBundle, then restart travis build
- [X] [DoctrinePhpcrAdminBundle](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/517), travis failed, but it is not related to PR
- [ ] [PageBundle](https://github.com/sonata-project/SonataPageBundle/pull/945), travis failed on `composer require`

**Comment by covex-nn** [comment]
Travis failed, need to restart travis jobs:

- [ ] Issue with [SonataDoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/794)
- [ ] Issue with [SonataFormatterBundle](https://github.com/sonata-project/SonataFormatterBundle/pull/315)
- [ ] Issue with [SonataMediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/1373)
- [ ] Issue with [SonataNewsBundle](https://github.com/sonata-project/SonataNewsBundle/pull/428)
- [ ] Issue with [SonataSeoBundle](https://github.com/sonata-project/SonataSeoBundle/pull/259)
- [ ] Issue with [SonataTimelineBundle](https://github.com/sonata-project/SonataTimelineBundle/pull/159)
- [ ] Issue with [SonataUserBundle](https://github.com/sonata-project/SonataUserBundle/pull/1000)

**Comment by greg0ire** [comment]
Done

**Comment by greg0ire** [comment]
> The requested package sonata-project/block-bundle ^3.11 exists as sonata-project/block-bundle[3.2.0] but these are rejected by your constraint.  

This message does not make any sense to me.

**Comment by covex-nn** [comment]
@greg0ire me too! May be there is something with packagist's cache? I saw it was failed with _"packagist ... 404 ... could not download ... use local copy"_, and now it failed again, and will fail until cache will not be invalidated (?)

**Comment by covex-nn** [comment]
May be it is because `require { "sonata-project/block-bundle": "^3.11" }` and `conflict { "sonata-project/block-bundle": "<3.1.1 || >=4.0" }` are in `composer.json` ?

**Comment by covex-nn** [comment]
I reproduced composer error localy. Tomorrow i will fix it.

**Comment by covex-nn** [comment]
I found out, that job for `FormaterBundle` could be restarted and it will be passed successfully if travis will wait for `composer update ... --prefer-lower`.

I suggest to run composer with `--verbose`, when it launched with `--prefer-lower`! Then travis will not think, that a build is stalled. See error message here: https://travis-ci.org/sonata-project/SonataFormatterBundle/jobs/332490006

For `SeoBundle` i removed `sonata-project/block-bundle` from `require-dev` (it is only on `require` section) and travis became green!

**Comment by covex-nn** [comment]
@greg0ire  I do not know what is better, i need an advice:

1. To add `"sonata-project/block-bundle": "^3.11` to `require` section
2. Or to add `"sonata-project/block-bundle": "<3.11"` to `conflict` and add `"sonata-project/block-bundle": "^3.11` to `require-dev` section

**Comment by covex-nn** [comment]
What if i will add `SYMFONY=2.8.0` to a job with `COMPOSER_FLAGS="--prefer-lowest"`? What if composer will execute `update` command faster? Without any changes `SonataFormatterBundle` travis build will be always failed =(

**Comment by greg0ire** [comment]
> What if i will add SYMFONY=2.8.0 to a job with COMPOSER_FLAGS="--prefer-lowest"? What if composer will execute update command faster? Without any changes SonataFormatterBundle travis build will be always failed =(

Could be worth a try. Are you saying that the build is currently KO regardless of your changes?

**Comment by covex-nn** [comment]
Travis build https://travis-ci.org/sonata-project/SonataFormatterBundle/builds/332830135 suddenly passed with `"sonata-project/block-bundle": "^3.2"`. It started to write to console on 8th-9th minute after `composer update --prefer-lowest`. And jobs with `"^3.11"` were always failed.

**Comment by covex-nn** [comment]
Travis build https://travis-ci.org/sonata-project/SonataFormatterBundle/jobs/332845215 with `COMPOSER_FLAGS="--prefer-lowest" SYMFONY=2.8.0` ran for **4 min 39 sec**! It is three times faster!

**Comment by greg0ire** [comment]
Nice find? How does it work? I guess it dramatically reduces the possibilities to explore, which probably helps a lot.

**Comment by greg0ire** [comment]
Would you mind contributing this to dev-kit? That's an issue we have on many repos (thinking of phpcr, cc @dbu @ElectricMaxxx

**Comment by dbu** [comment]
maybe you could use the symfony/lock component to limit which symfony lts to use? using symfony/symfony will hide dependency issues.

**Comment by covex-nn** [comment]
_google translate mode on_: @greg0ire i imagine it this way: each package is a dimension, the number of possible installations without optimizations is a multiplication of all dimensions (like a parallelepiped volume is A x B x C). With `SYMFONY=2.8.0` (it is one version!) we decreasing a number of dimensions and the number of possible installations, and composer processes less data and runs faster

**Comment by greg0ire** [comment]
@covex-nn My thoughs exactly. I think you are confusing symfony/lock and dunglas/symfony-lock

**Comment by covex-nn** [comment]
@greg0ire i think @dbu meant `symfony/lts`.

Travis build https://travis-ci.org/sonata-project/SonataFormatterBundle/jobs/332945647 with `COMPOSER_FLAGS="--prefer-lowest" SYMFONY_LTS=2` run for **12 min 37 sec**, and there is `"sonata-project/block-bundle": "^3.11"` in composer.json

I think, that `symfony/lts` will not help much! Because search for **minimum(packageVersion)** could not be optimized with additional condition **packageVersion < 3**. This condition is almost redundant.

@dbu i think, using symfony/symfony in job with PHP 5.6 and with `--prefer-lowest` will not hide dependency issues! Here https://travis-ci.org/sonata-project/SonataFormatterBundle/builds/332945638 **Job 942.1** will show all dependency issues, and **Job 942.7** will just run phpunit with lowest supported symfony and with composer's `--prefer-lowest`!

**Comment by dbu** [comment]
okay, i see. yeah if its only used for lowest, i don't think thats a problem. if anything, symfony is making their packages require *less* of each other in newer versions. so yeah, lets use the symfony/symfony for lowest version then.

while you are cleaning up the matrix, maybe you could also try moving towards the [best practices](https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration) that are now in the symfony doc. this could simplify and streamline the travis file some more.

**Comment by covex-nn** [comment]
A decision about updating `composer.json` by adding dependency to `sonata-project/block-bundle` must be made:

1. Add `"sonata-project/block-bundle": "^3.11"` to `require` section
2. Add `"sonata-project/block-bundle": "^3.11"` to `require-dev` section and `"sonata-project": "<3.11"` to `conflict` section
3. Do not change `composer.json` add create a CompilerPass, that replaces sonata.templating with templating if sonata.templating does not exists (this will be used for lower versions of BlockBundle)

- [ ] [UserBundle](https://github.com/sonata-project/SonataUserBundle/pull/1000)
- [ ] [SeoBundle](https://github.com/sonata-project/SonataSeoBundle/pull/259)
- [ ] [MediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/1373)
- [ ] [CommentBundle](https://github.com/sonata-project/SonataCommentBundle/pull/107)
- [ ] [ArticleBundle](https://github.com/sonata-project/SonataArticleBundle/pull/68)
- [ ] [NewsBundle](https://github.com/sonata-project/SonataNewsBundle/pull/428)

**Comment by core23** [comment]
> Add "sonata-project/block-bundle": "^3.11" to require-dev section and "sonata-project/block-bundle": "<3.11" to conflict section ?

This should be the prefered way. If we add the block-bundle to every project, we would have some big chuck of project like the CoreBundle again. This makes releasing a major version more difficult.

**Comment by covex-nn** [comment]
@core23 thank you for the advice, i will apply this today

**Comment by jordisala1991** [comment]
Take into account that blockBundle is required to use any bundle when you make the change from templating to sonata.templating

**Comment by covex-nn** [comment]
@jordisala1991 i checked all of them right now:

* AdminBundle, DashboardBundle, DoctrinePhpcrAdminBundle, FormatterBundle, PageBundle, TimelineBundle and TranslationBundle had dependency to `sonata-project/block-bundle` in `require` section of composer.json. I updated this dependency to `^3.11`
* ArticleBundle, CommentBundle, DoctrineORMAdminBundle, MediaBundle, NewsBundle, SeoBundle and UserBundle had no dependency to `sonata-project/block-bundle` in `require` section. I updated `conflict` and `require-dev` sections of composer.json

This will guarantee, that `sonata.templating` service will be available

**Comment by jordisala1991** [comment]
Only 2 missing: Article and User. 

Those are the only 2 bundles that uses templating directly but not in a block definition.

**Comment by covex-nn** [comment]
Both bundles require AdminBundle; AdminBundle require BlockBundle. So, `sonata.templating` service will be available with `"sonata-project/block-bundle": "<3.11"` in `conflict` section of composer.json

**Comment by covex-nn** [comment]
All checked and merged! =)
It took 40 days since i gave up with changing Flex from inside https://github.com/symfony/flex/issues/247#issuecomment-353320243 and looked into BlockBundle code https://github.com/sonata-project/SonataBlockBundle/issues/221#issuecomment-353440327

@jordisala1991 @greg0ire please merge 3.x branch into master (@SonataCI could not do it automaticaly, there are 3 files conflicting with each other). And there could be a problem with AdminBundle, because BlockBundle requires-dev Admin bundle and AdminBundle requires BlockBundle

**Comment by dbu** [comment]
thanks, great work!
