### ISSUE TITLE
Reduce Travis Matrix by testing only major version of dependencies

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#381]
The travis matrix of sonata project is quite huge.

Why not reduce it by testing dependencies major only? Like `2.*`, `3.*`... As minor version are supposed to be BC, we don't need to test each of them.

If we find an issue on a specific minor version, we can still add it to the matrix.

Though?

**Comment by greg0ire** [comment]
Why not…

**Comment by core23** [comment]
This would only remove two jobs (symfony 3.2, 3.3)

**Comment by core23** [comment]
If we try to fix some deprecation warnings in a new symfony minor version,  we wouldn't have test for older versions

**Comment by Soullivaneuh** [comment]
> we wouldn't have test for older versions

What do you mean? We have the `--prefer-lowest` option for that.

**Comment by core23** [comment]
> What do you mean? We have the `--prefer-lowest` option for that.

Good point. In that case we can drop old versions from travis.

**Comment by core23** [comment]
Maybe we can use https://packagist.org/packages/symfony/lts instead of `symfony/symfony` in our build. This could speedup travis a little bit.

**Comment by Soullivaneuh** [comment]
That's an idea indeed!

**Comment by VincentLanglet** [comment]
I think this can be closed https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml
