### ISSUE TITLE
Detect deprecation introduction and check for upgrade note

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#384]
If the code contains some deprecations, check for an upgrade note.

If the note is not present, add the corresponding label and block the PR status.

**Comment by OskarStark** [comment]
should we handle it like the changelog?
in the PR header instead of the "code" itself?

**Comment by Soullivaneuh** [comment]
@OskarStark No. The upgrade note should not produce any conflict if it's correctly updated.

**Comment by OskarStark** [comment]
> @OskarStark No. The upgrade note should not produce any conflict if it's correctly updated.

I thought about making the process less complex for the user. It is very handy that we can manipulate the changelog and don't need to ask and WAIT for the contributor
