### ISSUE TITLE
How to include assets (jQuery, admin-lte, ...)

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#387]
Today we have a really ugyl solution to include external assets (jQuery, Admin LTE, Bootstrap, ...) by making a hard copy of a library.

This is not a good solution, also if we add a `bower.json` or `package.json`, because this is always a temporary snapshot of a version. We don't have any update routine for it. 

Our bundles are also infected by some garbage files we don't use (test files for external libs, unused files). And the worst is that we could have some redudant files, e.g. if we need jQuery in more than one bundle.)

Affected bundles:
https://github.com/sonata-project/SonataAdminBundle/tree/3.x/src/Resources/public/vendor
https://github.com/sonata-project/SonataFormatterBundle/tree/3.x/src/Resources/public
https://github.com/sonata-project/SonataCoreBundle/tree/3.x/src/Resources/public/vendor

**Comment by jordisala1991** [comment]
We might look at how other popular bundles solve this to start getting some ideas for us

**Comment by core23** [comment]
The include only needed assets (e.g. EasyAdmin https://github.com/javiereguiluz/EasyAdminBundle/tree/master/src/Resources/public/javascript). This is a betters solution to reduce the bundle size, but got the same update problems.

**Comment by covex-nn** [comment]
If you can use CDN for all of these assets, then you could use it by default, make all assets' urls configurable and create instruction how to rebuild it with [Webpack encore](https://symfony.com/doc/current/frontend.html)

**Comment by core23** [comment]
> If you can use CDN for all of these assets, then you could use it by default, make all assets' urls configurable and create instruction how to rebuild it with Webpack encore

This is not about the deployment of your app ressources. The question is how you provide assets in your bundles, so anybody else can use them without any configuration

**Comment by Soullivaneuh** [comment]
Please see https://github.com/sonata-project/dev-kit/issues/398
