### ISSUE TITLE
[RFC] extend travis to install our bundles via flex?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#388]
We should be sure that our bundles are installable via flex.

WDYT

**Comment by core23** [comment]
What about the sandbox? Couldn't we use it for that?

**Comment by jordisala1991** [comment]
I think so. We should work on upgrading sandbox

**Comment by Soullivaneuh** [comment]
Well, we may simply run a `composer create-project symfony/skeleton` on an extra Travis job and then `composer require sonata-project/<bundle-name>`

Plus, it will allow us to check we require correctly all the needed dependencies.

**Comment by OskarStark** [comment]
That’s what I was thinking about :+1:

**Comment by OskarStark** [comment]
Like they do it here: https://github.com/symfony/recipes-contrib/blob/master/.travis.yml

**Comment by OskarStark** [comment]
@jordisala1991 do you think we should/can add a workflow based on GitHub actions?
