### ISSUE TITLE
[RFC] Structure of Flex-recipe for sonata-project bundles

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/dev-kit#397]
Several sonata-project bundles in their "Installation" chapter of documentation has instruction how to
generate the correct entities via `sonata:easy-extends:generate` command.

As a result, for example for NotificationBundle, there will be generated one `Entity` class and two .xml files with metadata configuration (for doctrine orm mapping and jms serializer). For MediaBundle there will be generated 2 classes in `Document`, 3 classes in `Entity` and 6 classes in `PHPCR` directory + 8 .xml files for doctrine orm and 6 .xml files for jms serializer.

I suggest to include all these files into Flex-recipe with bundle configuration, like i did it for NotificationBundle in https://github.com/symfony/recipes-contrib/pull/302. To create recipe files i ran `sonata:easy-extends:generate` command, updated classes namespaces and moved .xml file to another directory.

What do you think?

**Comment by kunicmarko20** [comment]
I think that this kind of thing only makes sense with bundles that have just `Entities` but `MediaBundle` where we have Document, Entity, and PHPCR we are forcing the user to delete them after flex install.

As I said already, this kind of thing only makes sense to me where we have just one type of database layer. 

What do rest think? /cc @sonata-project/contributors

**Comment by covex-nn** [comment]
I created demo application with Flex https://github.com/covex-nn/sonata-page-app and added configuration for NotificationBundle and PageBundle there.

Doctrine ORM configuration is in [config/packages/doctrine.yaml](https://github.com/covex-nn/sonata-page-app/blob/master/config/packages/doctrine.yaml) (see `doctrine.orm.mappings.Sonata` parameter), JMS Serializer configiration in in [config/packages/jms_serializer.yaml](https://github.com/covex-nn/sonata-page-app/blob/master/config/packages/jms_serializer.yaml) (see `jms_serializer.metadata.directories.app` parameter). Metadata configuration is in [config/metadata](https://github.com/covex-nn/sonata-page-app/tree/master/config/metadata). The location of the files differs from PR, but it works =)

To run application execute following commands:

```bash
git clone git@github.com:covex-nn/sonata-page-app.git .
composer install
docker-compose up -d
```
... wait for 1-2 minutes until mysql container is ready and then execute:

```bash
php bin/console doctrine:schema:update --force
php bin/console fos:user:create admin
php bin/console fos:user:promote admin ROLE_SUPER_ADMIN
php bin/console sonata:page:create-site --enabled=true --name=localhost --locale=- --host=localhost --relativePath=/ --enabledFrom=now --enabledTo="+10 years" --default=true
php bin/console sonata:page:update-core-routes --site=all
php bin/console sonata:page:create-snapshots --site=all
php -S 127.0.0.1:80 -t public
```
... then visit http://localhost/admin/ with your browser.

**Comment by kunicmarko20** [comment]
ping @sonata-project/contributors

**Comment by covex-nn** [comment]
@kunicmarko20 i suggest to remove xml files for doctrine and jms serializer, and also to add doctrine mappings via annotations. With this change there won't be any limitations like https://github.com/symfony/recipes-contrib/issues/303. I hope, doctrine mappings for phpcr/document could be added via annotations too (am i right?).

JMS serialized is optional dependency and it is not used by default, so we could add a comment to `src/Entity/NotificationMessage.php` how to enable serialization via annotations for Entity after `composer require jms/serializer-bundle`.

With these changes NotificationBundle will work out from the box after `composer require` and `doctrine:schema:update` without additional configuration. PageBundle will will work too.

**Comment by Xymanek** [comment]
While working on sandbox, I noticed that latest branch (before I started working, 2.4-develop) didn't have any of the `src/Application/` folders and instead has a single `AppBundle` which contains all entities, mappings, etc. Some links:

- [Entities](https://github.com/sonata-project/sandbox/tree/bd8eeab5ddda35041b96a7b41a37aa1b3bddc798/src/AppBundle/Entity)
- [Mappings](https://github.com/sonata-project/sandbox/tree/bd8eeab5ddda35041b96a7b41a37aa1b3bddc798/src/AppBundle/Resources/config/doctrine)
- [`MediaBundle` config with class overrides](https://github.com/sonata-project/sandbox/blob/bd8eeab5ddda35041b96a7b41a37aa1b3bddc798/app/config/sonata/sonata_media.yml#L5-L9)

Maybe this can be used as base/inspiration for flex recipes?

**Comment by kunicmarko20** [comment]
We support doctrine orm, phpcr and mongodb. That is the problem why we can't do this through recipes.

**Comment by Xymanek** [comment]
Oh right I see your point. What about backend specific packs? For example `sonata-project/media-phpcr` which would be something like [this](https://github.com/symfony/debug-pack) with a recipe.

> we are forcing the user to delete them after flex install

wasn't that the case with easy extends already?

**Comment by kunicmarko20** [comment]
Can a pack have Classes/configuration or just `composer.json`? 

It was the case but at least it was in a separate namespace.

**Comment by Xymanek** [comment]
A pack (or at least the ones symfony provides now) is a dummy package which does 1 thing: depends on actual packages so that composer pulls them when you install the pack (so you can can get multiple packages by depending only on one).

But you can also wire a recipe to it.

Another thing I though of now is the following: [`post-install-output` Configurator](https://github.com/symfony/recipes/blob/master/README.rst#post-install-output-configurator). We can put all 3 in one recipe and leave a comment to show after install (like "MediaBundle comes with examples for 3 backends, you can remove those that you do not need")

**Comment by kunicmarko20** [comment]
https://github.com/symfony/recipes/tree/master/symfony/webpack-encore-pack/1.0 yep just confirmed on Symfony Slack. So having multiple packs per database layer? Wouldn't we end up with a loooot of packs 😄

**Comment by kunicmarko20** [comment]
I know about that comment, but currently, it is automated with easy extends and I would rather have it like that.

**Comment by Xymanek** [comment]
> currently, it is automated with easy extends

Does it make any difference which tool prints the message?

**Comment by kunicmarko20** [comment]
Ah, I did not understand properly, so we generate all classes and then leave a message to remove what is not needed but why do we need a pack then? Don't like it really, @sonata-project/contributors what do others think?

**Comment by Xymanek** [comment]
It's not for pack, it's an alternative to having multiple packs. So either:

- Multiple packs
- Single recipe with "delete" message

**Comment by kunicmarko20** [comment]
so we would have 3 packs per repo?

**Comment by Xymanek** [comment]
Yes

**Comment by covex-nn** [comment]
Just fyi: I created an issue in `symfony/flex` https://github.com/symfony/flex/issues/344 where i asked to make Flex more interactive. The answer was no =) So, recipe must contain all necessary configuration to run `clear:cache` without errors, and additional configuration should be added with `sonata-project/easy-extend-bundle` or `symfony/maker-bundle ` or without them, if it will be "3 packs" and 3 recipes.

**Comment by kunicmarko20** [comment]
This will maybe sound stupid but can we add an extension to flex or a custom sonata composer plugin that would help us with this. We would be replacing easy extends with a custom plugin, does not sound like a good idea.

**Comment by covex-nn** [comment]
Flex is not extendable for now: almost everything important is private and cannot be used without making it public via reflection. So, we cannot inject our code inside Flex. Also, container is not accessable from Flex/Composer. Inside composer plugin we can operate with a list of installed packages, see `ocramius/package-versions`. For example, if `doctrine/doctrine-bundle` is installed, create something inside `Entity/` and update files inside `config/`. But it is not good, i think.

For now, in my point of view, if we are not including `Entity`, `Document` and `PHPCR` inside a recipe, the best alternative for `sonata-project/easy-extends-bundle` is a "maker" for `symfony/maker-bundle`, see [docs](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html#creating-your-own-makers). It could use container, interact with user and generate everything for all sonata bundles with one console command.

**Comment by Xymanek** [comment]
👍 for maker approach - way better than my suggestions

**Comment by kunicmarko20** [comment]
Isn't that almost the same thing like we currently have? We would just add commands to all bundles?

**Comment by Xymanek** [comment]
The current way is... weird and doesn't comply with sf4's best practices (no bundles). Maker is a way to

* take a new approach, that adheres to new best practices
* use a tool that's familiar to users and is standard across sf4 ecosystem

**Comment by covex-nn** [comment]
There could be only one maker for all bundles. It could create `Entity` classes with annotations (i hope `Document` and `PHPCR` classes can use annotations too). It could check if `jms/serializer-bundle` is installed, and skip adding annotations for serialization, and it could update entity classes if jms serializer was installed after maker first run.

But, @kunicmarko20, you are right - it is almost the same thing! We could create Maker inside easy-extends-bundle, that (1) asks user about database storage, (2) generates everything for all bundles, (3) creates everything inside App namespace, i.e. no bundles, (4) does not require a lot of arguments from command line, (5) but i am not sure about annotations here. I will try to create a prototype.

**Comment by kunicmarko20** [comment]
Don't know, it sounds better than easy extends but still we have an additional bundle that deals with this. cc @sonata-project/contributors wdyt?

**Comment by Soullivaneuh** [comment]
Personally, I never used easy-extends in any moment, and I'm moving to avoid using any generator such as `maker` or something else.

My opinion about class generation way: If we can provide a maker-bundle service instead of using easy-extends, then we should just deprecate the second one and move away.

There is no point to have two package doing the same thing, and this will reduce the maintenance load.

I read the issue quickly, but I don't really see the relation with Flex here.

**Comment by covex-nn** [comment]
I guess it could be closed in favour of https://github.com/sonata-project/dev-kit/issues/409, since my another [proposal](https://github.com/sonata-project/SonataMediaBundle/issues/1419) was accepted and a first PR was already [merged](https://github.com/sonata-project/SonataMediaBundle/pull/1420)
