### ISSUE TITLE
Move assets to NPM packages

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#398]
One package per bundle with proper requirement.

IMHO, doing it on a major will be simpler.

Of course, a documentation should be provided to show how to setup the asset. We should based our sample with a symfony/encore configuration.

Concerned packages (please comment for forgotten one):

- [ ] admin-bundle
- [ ] core-bundle https://github.com/sonata-project/SonataCoreBundle/pull/570
- [ ] formatter-bundle
- [ ] translation-bundle
- [ ] media-bundle
- [ ] dashboard-bundle
- [ ] page-bundle

**Comment by kunicmarko20** [comment]
translation-bundle

**Comment by kunicmarko20** [comment]
media-bundle

**Comment by kunicmarko20** [comment]
Dashboard, Formatter, Page

**Comment by Dunduro** [comment]
would anybody be interesting in sparring about how we'd accomplish this?

I'm not completely sure how to get npm/yarn to install packages from package.json's in the vendor. An option would be to make a command that combines all the package.json's and adds them to the package.json in the project root. we could combine it with producing a basic webpack.config.js that will produce the required assets independent of which bundles are added.

the command should be create or update concept so it shouldn't remove any packages, just add them if they haven't already so not to damage functionality when run in an existing project.

if we could have this command run on the composer install then right when you start your project all js dependencies are added to your package.json and whenever you update your composer.json and you pull in a new bundle with new dependencies they would get added to the package.json.

would something like the above mentioned already exist or would it be an idea to have it be a bundle on its own?

**Comment by greg0ire** [comment]
I'm at an sf conference an learnt about the yarn workspace

**Comment by Soullivaneuh** [comment]
The simplest way to do it is an entry-point and some documentation of how to enable it with webpack, encore, grunt etc...

One JS and CSS file including the right vendors and asset for each bundle. The only thing to do will to run a yarn/npm install and follow the documentation.

**Comment by wbloszyk** [comment]
I working on AdminLTE 3 in admin and bootstrap 4 in sandbox. Assets is load in 2 places: `admin-bundle` and `page-bundle` layout. This assets is: `bootstrap`, `jquery`, `select2`, they plugins and `moment`. In templates we should return information which assests is required like pagination have:
- @KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig
- @KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig

I think we can resolve assets and upgrade templates at the same times. Propose steps:
- copy current views files to views/bootstrap_3 (views should stay to keep BC and should be remove in 4.x)
- add views/bootstrap_4
- override js to check encore (Yea!!!) or use old js
- in new layouts load assets from encore or composer:
    - https://github.com/twbs/bootstrap
    - https://github.com/moment/moment/blob/develop/composer.json
    - https://github.com/components/jquery/tree/3.4.1 ???

@core23 @soullivaneuh @Contributors WDYT?

**Comment by wbloszyk** [comment]
Can be close in favor of #779
