### ISSUE TITLE
Run a daily build via travis cronjob

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#401]
Refs: https://github.com/sonata-project/dev-kit/pull/383#issuecomment-359782618

and we should run a cron build on sandbox (and maybe every project) every day 😄
![35276957-72b74f5c-0045-11e8-849e-9003d8c2e6a1](https://user-images.githubusercontent.com/995707/37895271-16232adc-30e1-11e8-851b-aa76efc90152.png)

**Comment by kunicmarko20** [comment]
cc @sonata-project/contributors we need this, @jordisala1991 saw that media bundle failed because of the new update to AdminBundle and we could have seen this yesterday.

I think anyone can set this up we just need all to agree?

**Comment by kunicmarko20** [comment]
Well, I do not know, was there a reason why you made an issue instead of adding it? 😄

**Comment by kunicmarko20** [comment]
I just saw that we already have cron jobs setup but they are monthly, we can just switch it to daily.

**Comment by OskarStark** [comment]
No reason but no time to setup all repos 

We should add a todo checkbox list

**Comment by jordisala1991** [comment]
I like the idea, but keep in mind to put a time after 2:00 because otherwise we will collapse travis with builds

**Comment by kunicmarko20** [comment]
I added daily cron jobs to all travis repos we have and they are starting now, so I guess they will run every morning

**Comment by kunicmarko20** [comment]
Do we get some kind of notification if travis fails or can we integrate that into slack or something?

**Comment by kunicmarko20** [comment]
So, cron jobs are still running and this can block potential PRs, maybe enable it late in the evening or do not enable all repos?

**Comment by OskarStark** [comment]
Maybe 5 oclock in the morning would be great

Otherwise we could ask for a sponsor on twitter for private Travis 😊
should be faster, because it could run more in parallel



Marko Kunic <notifications@github.com> schrieb am Mi. 11. Apr. 2018 um
10:07:

**Comment by kunicmarko20** [comment]
After 4 hours, they are still running... 😞

**Comment by jordisala1991** [comment]
Maybe we should not have crons then :P

Or we should configure to run if there are no build that day.

**Comment by Soullivaneuh** [comment]
:-1: for one reason: We already use **a lot** of resources and time to run the CI builds.

Run them everyday would be overkill and will make PR jobs stuck for a while.

**Comment by Soullivaneuh** [comment]
At least, weekly build would be debatable IMHO, even if I personally don't see the interest.

**Comment by OskarStark** [comment]
Now with GitHub actions we can schedule a daily build, WDYT jordisala1991 ?

**Comment by jordisala1991** [comment]
Yes, it can be done, it should be easy (but I dont know if they will trigger for every maintained branch or only the default one)

**Comment by OskarStark** [comment]
Open for a PR @jordisala1991 ?
