### ISSUE TITLE
.styleci.yml is still present in the repositories

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#402]
see: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.styleci.yml

Can we achieve this by `dev-kit` or do we need to do this manually? @Soullivaneuh

**Comment by jordisala1991** [comment]
Manually ATM, there are several files that were handled by dev-kit that are no longer necessary.

**Comment by OskarStark** [comment]
damn

**Comment by jordisala1991** [comment]
This is duplicated of #261 

Lets continue the discussion there.
