### ISSUE TITLE
Recipes for Symfony Flex

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/dev-kit#409]
This article contains a plan for creating recipes for sonata-project bundles. Each bundle must be prepared according to [my proposal](https://github.com/sonata-project/SonataMediaBundle/issues/1419):

1. It should be possible to create a default configuration, that allows to run `cache:clear` without errors
2. It should be possible to create an additional configuration for each supported persistence mechanism, that will make a bundle fully functional after installing some required additional packages

A default configuration will be a bundle's recipe. Additional configuration will be a recipe for a new package. This new package, a `pack`, will contain composer.json with all requirements for particular persistence mechanism.

A bundle, that will be installed without a pack (and without additional configuration) can throw exceptions with instructions for developer how to set it up with installing a pack.

**MediaBundle**

* [x] Update dependencies, https://github.com/sonata-project/SonataMediaBundle/pull/1417
* [x] Make a `db_driver` configuration parameter optional with `no_driver` default value, https://github.com/sonata-project/SonataMediaBundle/pull/1420
* [x] Create default configuration and a recipe, https://github.com/symfony/recipes-contrib/pull/375
* [x] Create new repository for `sonata-project/media-orm-pack`
* [x] Create additional configuration for ORM, create a recipe, https://github.com/symfony/recipes-contrib/pull/385
* [x] Create new repository for `sonata-project/media-odm-pack`
* [x] Create additional configuration for MongoDB ODM, create a recipe, https://github.com/symfony/recipes-contrib/pull/410
* [x] Create new repository for `sonata-project/media-phpcr-pack`
* [ ] Create additional configuration for PHPCR, create a recipe

**SeoBundle** and **CacheBundle**

Maybe a default configuration could be created? Or bundle configuration is enough?

**NotificationBundle**

* [x] Refactor bundle configuration, https://github.com/sonata-project/SonataNotificationBundle/pull/314
* [x] Update dependencies, https://github.com/sonata-project/SonataNotificationBundle/pull/327
* [x] Create default configuration and a recipe, https://github.com/symfony/recipes-contrib/pull/302
* [x] Create new repository for `sonata-project/notification-orm-pack`
* [x] Create additional configuration for ORM, create a recipe, https://github.com/symfony/recipes-contrib/pull/384

**PageBundle**

* [x] Auto-register sonata.page.router, https://github.com/sonata-project/SonataPageBundle/pull/960
* [x] Update bundle dependencies in composer.json, https://github.com/sonata-project/SonataPageBundle/pull/980
* [x] Wait until [symfony-cmf/routing-bundle](https://packagist.org/packages/symfony-cmf/routing-bundle) will be released with Symfony ^4.0 dependencies
* [x] Create default configuration and a recipe, https://github.com/symfony/recipes-contrib/pull/397

**ClassificationBundle**

* [x] Prepare bundle for recipe, https://github.com/sonata-project/SonataClassificationBundle/pull/403
* [x] Create default configuration and a recipe, https://github.com/symfony/recipes-contrib/pull/389

**TranslationBundle**

* [x] Prepare bundle for recipe, https://github.com/sonata-project/SonataTranslationBundle/pull/233
* [x] Create default configuration and a recipe, https://github.com/symfony/recipes-contrib/pull/400

**ArticleBundle**

* [ ] Create default configuration and a recipe

**TimelineBundle**

* [ ] Create default configuration and a recipe

**CommentBundle**

* [ ] Create a recipes for FOSCommentBundle first ??

**DashboardBundle**

* [ ] Create default configuration and a recipe

**UserBundle** and **NewsBundle**

It is not possible to create a recipe for these bundles, because they depends on FOSUserBundle, that does have and cannot have a recipe.

**FormatterBundle**

`egeloen/ckeditor-bundle` should be replaced with `friendsofsymfony/ckeditor-bundle`, but it is a BC break

**ClassificationMedia**

No plans, a recipe will be possible after next major release of MediaBundle and ClassificationBundle

**Comment by kunicmarko20** [comment]
> Make a db_driver configuration parameter optional with no_driver default value

 I think this will be a bc break 😞 

> Set admin.enabled configuration parameter == defaultFalse 

same

> SeoBundle and CacheBundle
> 
> Maybe a default configuration could be created? Or bundle configuration is enough?

If there is any configuration that has to be set in docs, then we add it to recipe.

So basically, we can only do: `SeoBundle, CacheBundle, PageBundle, ClassificationBundle, ArticleBundle, TimelineBundle , DashboardBundle`?

**Comment by covex-nn** [comment]
I believe, that changes for MediaBundle is not a BC break, i will create a PR soon, so we can discuss it there. I hope MediaBundle will have a recipe soon. And ArticleBundle depends on MediaBundle =)

PageBundle and DashboardBundle depends on NotificationBundle. And we can create a recipe for NotificationBundle, actualy. Changing `admin.enabled` is optional, and it is BC break, yes. With that change i want to enable admin only when `backend` is `sonata.notification.backend.doctrine` and Entity is available. Otherwise it will be disabled by default configuration in current release.

> If there is any configuration that has to be set in docs, then we add it to recipe.

:+1:

**Comment by kunicmarko20** [comment]
oh, if by default it is empty, then no, I thought it is `orm` by default. That won't be a bc for media then.

**Comment by covex-nn** [comment]
Updated PR for `sonata-project/notification-bundle`, see https://github.com/symfony/recipes-contrib/pull/302. Recipe contains only `config/packages/sonata_notification.yaml` file

**Comment by kunicmarko20** [comment]
Media pack name depends on:

>that depends whether you target ODM or plain MongoDB

Copied from Slack conversation I never used it so I am not sure, I guess ODM?

**Comment by kunicmarko20** [comment]
So, for now, we need:

```
sonata-project/media-orm-pack
sonata-project/media-odm-pack
sonata-project/media-phpcr-pack
sonata-project/notification-orm-pack
sonata-project/classification-orm-pack
sonata-project/classification-odm-pack
```
this repositories created?

**Comment by kunicmarko20** [comment]
cc @greg0ire, @jordisala1991, @core23, @OskarStark, @Soullivaneuh before I contact @rande, do you agree we continue this way and use packs?

**Comment by core23** [comment]
> do you agree we continue this way and use packs?

Never used symfony flex /w packs. Do we need this many packs or can we create a general `sonata/doctrine-pack`?

**Comment by covex-nn** [comment]
@core23 `sonata/doctrine-pack` is too generic, it cannot bring anything for `sonata-project/media-bundle` except `doctrine/doctrine-bundle` and `doctrine/doctrine-orm` - `symfony/orm-pack` already contain such dependencies.

With my proposal, see https://github.com/sonata-project/SonataMediaBundle/issues/1419, after `composer require sonata-project/media-orm-pack` developer will receive:

1. `sonata-project/media-bundle` and `sonata-project/doctrine-orm-admin-bundle` from pack's dependencies; also `doctrine/doctrine-bundle` with `doctrine/orm` will be installed
2. A default configuration from MediaBundle recipe, see [comment](https://github.com/sonata-project/SonataMediaBundle/issues/1419#issuecomment-382309378)
3. A storage configuration from MediaOrmPack recipe, see the same comment
4. Three Entity classes, see [gist](https://gist.github.com/covex-nn/76795ddb85fb3656d716e462a748156c)

And after `bin/console doctrine:schema:update --force` developer will have fully functional MediaBundle

**Comment by rande** [comment]
Do you want 1 repositories with all packs and split it like symfony ? or do you want many repositories ?

The pack solution looks great!

**Comment by rande** [comment]
@covex-nn it is possible: https://github.com/splitsh/lite

**Comment by covex-nn** [comment]
@rande i've starred that repo =) but anyway creating one more repository for all recipes does not bring us closer to achieving the goal. All recipes are not related to each other, each repository will contain only `composer.json`, there won't be even `.travis-ci.yml` (recipes will be tested in `symfony/recipes-contrib`, also #388 is about recipe testing). @kunicmarko20 what do you think?

Also, i think that it is too early for `sonata-project/classification-orm-pack` and `sonata-project/classification-odm-pack`. ClassificationBundle is not ready for using with MongoDB even with a pack. Right now it supports only Doctrine ORM; it requires `sonata-project/doctrine-orm-admin-bundle`; all services depends on `doctrine`; also see https://github.com/sonata-project/SonataClassificationBundle/issues/262. So, i think that recipe for ClassificationBundle should contain Entities, like PageBundle will contain.

**Comment by kunicmarko20** [comment]
I also think we should have separate repositories, didn't see any pack going with just 1 generic repo. So then we just need:

```
sonata-project/media-orm-pack
sonata-project/media-odm-pack
sonata-project/media-phpcr-pack
sonata-project/notification-orm-pack
```

for now? @covex-nn

**Comment by covex-nn** [comment]
Yes, just 4 new repositories

**Comment by covex-nn** [comment]
I prepared gists with Entity classes for [NotificationBundle](https://gist.github.com/covex-nn/d34ec8f3a97f566e581979ecff041954), [MediaBundle](https://gist.github.com/covex-nn/76795ddb85fb3656d716e462a748156c) and [PageBundle](https://gist.github.com/covex-nn/e9cbcebec05a4e1558460b8f7160637e), please review if you have time. I will use these classes in recipes

**Comment by kunicmarko20** [comment]
JMS is an optional dependency, I think it can't be done this way?

**Comment by covex-nn** [comment]
JSM serializer bundle is required dependency only for MediaBundle, and i added `* @Serializer\Groups` only for media entities. For notification and page entities i added `* // Serializer\Groups` <-- it is not annotation, but it could be modified by developer, if JMS will be installed (and i fixed SonataPageSite entity right now - i forgot to remove annotation there)

**Comment by kunicmarko20** [comment]
Hm, I guess it can work that way, I am not happy tbh. We should maybe add a message after recipe/pack about that if we go this way.

I would rather have `.xml|.yml` config and they do w/e they want with it, if they do not have JMS it won't be imported because there is nothing looking for them.

**Comment by kunicmarko20** [comment]
cc @sonata-project/contributors, wdyt?

**Comment by covex-nn** [comment]
@OskarStark `egeloen/ckeditor-bundle` is not replaced, actualy. FormatterBundle still require it =(

**Comment by rande** [comment]
@sonata-project/contributors done! You now have 4 new repositories!

**Comment by covex-nn** [comment]
New version of `symfony-cmf/routing-bundle` with Symfony4 support was released and tested with https://github.com/sonata-project/SonataPageBundle/pull/981, so now it is possible to created a recipe for SonataPageBundle! I am planning to create a PR in `symfong/recipes-contrib` after https://github.com/sonata-project/SonataPageBundle/pull/996 will be merged and released

**Comment by VincentLanglet** [comment]
Closing as the missing library are abandoned
