### ISSUE TITLE
Use roave/backward-compatibility-check

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#414]
This [utility](https://packagist.org/packages/roave/backward-compatibility-check) will detect BC breaks between the last tagged release and the current branch on the PHP code api.

I think it would worth it to test it. If it can help us to prevent BC breaks at least on PHP codebase, it might be a great addition.

WDYT?

**Comment by greg0ire** [comment]
I think we could start with an allow failures build, see how it goes…

**Comment by Soullivaneuh** [comment]
Yep. Also we should take care to not run it on master, as BC breaks are allowed on this branch.

**Comment by covex-nn** [comment]
I created a repository to test this package and found, that a tool can not check a class, that extends some other class from `require-dev` deps. See:

* [composer.json](https://github.com/covex-nn/test-bc-check/blob/master/composer.json), it contains `symfony/filesystem` in `require-dev`
* [Class1](https://github.com/covex-nn/test-bc-check/blob/master/src/Class1.php) extends `Symfony\Component\Filesystem\Filesystem`, i removed a public method there
* [Class2](https://github.com/covex-nn/test-bc-check/blob/master/src/Class2.php) extends `Symfony\Component\Filesystem\Filesystem` too

And a result:

* https://travis-ci.com/covex-nn/test-bc-check/builds/74891794 - build failed
* Provided node "Symfony\Component\Filesystem\Filesystem" is not class, but "interface" - a wierd error message =)
* There is no message about removing public method. It just stoped on that "interface"

So, i suspect, that to check BC they do not install all dependencies [here](https://github.com/Roave/BackwardCompatibilityCheck/blob/master/src/LocateDependencies/LocateDependenciesViaComposer.php) (search for `$installer->setDevMode(false);`)
