### ISSUE TITLE
Solution for assets 

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#433]
ATM we have the problem, that we use hard copies of all external assets. 

Maybe we have a solution (for the next stable releases) by using foxy https://github.com/fxpio/foxy. It is a composer plugin that will look for a package.json file and will run yarn after composer was executed. 

Didn't test it yet, but it looks nice ;)

**Comment by wbloszyk** [comment]
Please see https://github.com/sonata-project/dev-kit/issues/398#issuecomment-622045627

**Comment by wbloszyk** [comment]
Can be close in favor of #779
