### ISSUE TITLE
Lets manage tests/bootstrap.php and tests/autoload.php.dist via dev-kit?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#436]
Looks like I fixed the build of this [PR](https://github.com/sonata-project/SonataAdminSearchBundle/pull/126/files) in this [commit](https://github.com/sonata-project/SonataAdminSearchBundle/pull/126/commits/4b9b718d39e45315229dc272fc8f7cbbbf7d649d)

I copied the files from block-bundle.
My question is: Shall we manage these files via dev-kit? Most of them are equal, aren't they?

Please vote 👍 and 👎 

**Bundles:**
- [ ] UserBundle (https://github.com/sonata-project/SonataUserBundle/pull/1057)
- [x] AdminBundle (https://github.com/sonata-project/SonataAdminBundle/pull/5300)
- [x] BlockBundle (https://github.com/sonata-project/SonataBlockBundle/pull/519)

**Comment by OskarStark** [comment]
They are a bit different for example:

**AdminBundle**
[bootstrap.php](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/bootstrap.php)
has this part:
```php
// fix encoding issue while running text on different host with different locale configuration
setlocale(LC_ALL, 'en_US.UTF-8');
```

**UserBundle**
https://github.com/sonata-project/SonataUserBundle/blob/4.x/tests/bootstrap.php
has this part:
```php
// try to get Symfony's PHPunit Bridge
$files = array_filter([
    __DIR__.'/../vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bootstrap.php',
    __DIR__.'/../vendor/symfony/phpunit-bridge/bootstrap.php',
    __DIR__.'/../../../../vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bootstrap.php',
    __DIR__.'/../../../../vendor/symfony/phpunit-bridge/bootstrap.php',
], 'file_exists');
if ($files) {
    require_once current($files);
}
```

**BlockBundle**
[bootstrap.php](https://github.com/sonata-project/SonataBlockBundle/blob/3.x/tests/bootstrap.php)
is that simple:
```php
<?php
/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
if (file_exists($file = __DIR__.'/autoload.php')) {
    require_once $file;
} elseif (file_exists($file = __DIR__.'/autoload.php.dist')) {
    require_once $file;
}
```

PS: I don't know how to include selected lines of file in Github :(

**Comment by greg0ire** [comment]
You have to use a permalink, which you can obtain from the line numbers. You can highlight a range of line numbers. Not 100% it works between repos, it might if those are repos from the same organization.

**Comment by greg0ire** [comment]
Maybe make PRs to reduce the differences first?

**Comment by OskarStark** [comment]
Yeah I will do that, but setting a Locale makes sense to me
