### ISSUE TITLE
Replacing GitHub Services

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#457]
Dev-kit is concerned (hooks creation).

https://developer.github.com/v3/guides/replacing-github-services/

**Comment by Soullivaneuh** [comment]
Or maybe not ? https://developer.github.com/changes/2018-10-01-denying-new-github-services/

I need other review about that please.

**Comment by greg0ire** [comment]
I think this has to do with communication between GitHub and a 3rd party service, like the one listed here: https://github.com/github/github-services/tree/master/docs I don't see how that would affect dev-kit…

**Comment by VincentLanglet** [comment]
> January 31, 2019: GitHub will stop delivering installed services' events on GitHub.com.

So I assume I can close this issue.
