### ISSUE TITLE
Next major: Symfony version support

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#51]
Let's talk about Symfony version support drop for next major of sonata bundles.

I think we all agree that SF 2.3 to 2.6 would be dropped.

What I'm not sure it's about 2.7. Should will still support it?

My thinking: Keeping only 2.8+ support would get us free of **LOT** of BC tricks between SF 2.7 and 2.8, especially for Form.

With that, we will have a clean code to start BC layers for next 3.x versions of Symfony.

I know, that 2.7 is a LTS version. But this one is supported by our actual bundles and SF 2.8 is also an LTS. BTW, 2.8 is here because of a too early release of 2.7 AFAIK.

Let's vote, use emoji reaction for that:

:+1: For support beginning at SF **2.8**
:-1: For support beginning at SF **2.7**

Feel free to elaborate your thinking on this issue. :+1: 

cc @sonata-project/contributors

**Comment by greg0ire** [comment]
Migrating to 2.8 is super easy so :+1:

**Comment by rande** [comment]
Cannot we move to Symfony 3.0 ?

**Comment by Soullivaneuh** [comment]
@rande We have to keep at least one LTS.

BTW, 3.0 is the same as 2.8 but without deprecated stuff.

**Comment by rande** [comment]
Oky then. So 2.8 is the way to go. The next LTS version (3.4) will be release on 11/2017, so this is another story
