### ISSUE TITLE
Next major: PHP version support

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#52]
Let's talk about PHP version support drop for next major of sonata bundles.

Ref: http://php.net/supported-versions.php

PHP 5.5 will be not supported at all by the company soon (2 months).

PHP 5.6 is still supported for more than 2 years and I think we have to keep at least one PHP 5 support for the moment.

SF 3.0 supports PHP 5.5+ but I don't think we should absolutely follow them, we have not the same dynamic.

Let's do a vote for this too (emoji reaction):

:+1: for PHP 5.6+ support
:-1: for PHP 5.5+ support

Feel free to elaborate your thinking on this issue. :+1: 

cc @sonata-project/contributors

**Comment by Th3Mouk** [comment]
Beyond the end of support of PHP 5.5, i think if we drop this version we must argue a little more, on technical issues, the advantages of 5.6 compared to 5.5.
IMO many of servers running sonata are legacy (luckily i'm not), and the update to 5.6 can be a pain, it's necessary to go a little deeper into the process, and not simply impose a server upgrade.
If we don't use PHP 5.6 feature, Sonata isn't in charge of hosting maintenance, 5.5+ is sufficient and running as well on 5.6 and 7.0 environnement.
Maybe the rate of migration to php7, in the coming months, can ease the decision for 4.x version.

**Comment by Soullivaneuh** [comment]
Thanks for your answer @Th3Mouk.

> IMO many of servers running sonata are legacy (luckily i'm not), and the update to 5.6 can be a pain, it's necessary to go a little deeper into the process, and not simply impose a server upgrade.

Well, I have a friend who works on a company which have servers running PHP 5.3.3 and that don't want to upgrade. Do we have to keep support of PHP 5.3.3? I think not.

It's not imposing a server upgrade IMHO. For example, sonata admin 3.x still supports PHP 5.3+. If user don't want to upgrade, well just keep on this version.

In any case, staying at legacy version of PHP or any library is dangerous and the pain is here for me. This is not really concerning us.

> If we don't use PHP 5.6 feature, Sonata isn't in charge of hosting maintenance, 5.5+ is sufficient and running as well on 5.6 and 7.0 environnement.

Well, I already have one: PHPUnit. Indeed, PHPUnit 5 has many new features (for exception test for example) but works only starting PHP 5.6.

If we keep PHP 5.5 support, we will have to manage test for two major version of this tools just for dev env of our projects.

> and the update to 5.6 can be a pain

Well, not really. I agree that upgrading from 5.2 to 5.3 and 5.3 to 5.4 gave some issues, but BC between 5.4 and 5.6 are great, you can easily upgrade without breaking your application AFAIK.

The only things I agree for now, it's to keep a 5.x PHP version and not starting to 7. PHP 7 is a big major and is not yet compatible with some libraries (e.g. mongo).

**Comment by greg0ire** [comment]
Dropping 3 php versions at once is a bit much IMO, and, on a more selfish note, I have lots of servers running 5.5, and even some running 5.4, but not one running 5.6 (yet). That will change soon thanks to docker though.

**Comment by Soullivaneuh** [comment]
@greg0ire @Th3Mouk Please not that is for the **next major** that will not be pushed tomorrow! :wink:

**Comment by greg0ire** [comment]
I thought the next majors were going to come pretty fast :disappointed:

**Comment by Soullivaneuh** [comment]
> I thought the next majors were going to come pretty fast :disappointed: 

Well, I didn't say in two years. But it's not for right now, so PHP 5.5 that is already deprecated will be less important IMHO.

**Comment by Th3Mouk** [comment]
@Soullivaneuh i know, discuss about it allow to clear up ideas. I'm agree with you concerning 5.3 and 2.3.
The dependency with PHPUnit is an excellent reason to drop support of PHP 5.5, knowing that release will be not in 2016.
BTW the next major release will completely cleaning up all dependencies, and drop a lot of version, and i think that our dependency probably naturally go to `^5.6 || ^7.0`, in few months this choice 5.5/5.6 probably be obsolete.

**Comment by Soullivaneuh** [comment]
@Th3Mouk I'll start by SF version dropping since everybody looks agree for SF 2.8+.

Will look at PHP after that.

**Comment by Soullivaneuh** [comment]
Votes are more for PHP 5.6.

For me, this is the good way. For three reasons:

* Next major release of each package will introduce 3 branches (#153). So people using legacy PHP version can still use legacy packages version for a while, before upgrading.
* PHPUnit 5 only support PHP 5.6+. Doing the same will help us to get rid of BC tricks for tests and concentrate on your work.
* PHP 5.5 is already only supported for security fixes. This support will be EOL in one month. As we do for Symfony, there is no reason to support an EOL PHP version.
