### ISSUE TITLE
Use probot for project configuration

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#528]
Probot allows project configuration using `yaml` style: https://github.com/probot/settings#usage

So we don't need @soullivaneuh or @rande admin rights for simple things like updating labels, project topics, project description, ...

We could also define a global config inside dev-kit and extend it for each project, if needed: https://github.com/probot/settings#inheritance

WDYT @sonata-project/contributors

**Comment by core23** [comment]
This file should be managed using [CODEOWNERS](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) permissions

**Comment by greg0ire** [comment]
It enables pull requests for repo settings? This sounds really nice!

**Comment by core23** [comment]
> It enables pull requests for repo settings? This sounds really nice!

Yes, and you could also add / remove members with a simple config

**Comment by core23** [comment]
I just requested the installation of probot:

>  A request to install Settings has been submitted on the @sonata-project account. 

Can someone approve? @OskarStark ?

**Comment by OskarStark** [comment]
Done

**Comment by core23** [comment]
Thanks
