### ISSUE TITLE
Use stale bot for inactive issues

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#529]
We have many issues that are long running / did not get any attention. 

AFAIK we should close them after a while. If it's still a problem for anyone, it should come back or someone should be working on this.

[Stale](https://probot.github.io/apps/stale/) could close this issues for us, so we can focus on active issues.

**Comment by core23** [comment]
We still need a setup for this app

**Comment by OskarStark** [comment]
By whom?

**Comment by core23** [comment]
@rande or @soullivaneuh ?

**Comment by core23** [comment]
... or @greg0ire ? Can you install the app from the marketplace?

**Comment by OskarStark** [comment]
@core23 I activated it for all our repos.

**Comment by core23** [comment]
![Image](https://sayingimages.com/wp-content/uploads/so-it-begins-popcorn-mode-time-meme.jpg)

**Comment by core23** [comment]
We still need a new dev-kit deployment @soullivaneuh :(

**Comment by core23** [comment]
The file exists inside the admin repo (https://github.com/sonata-project/SonataAdminBundle/blob/master/.github/stale.yml), but there is no action from stale :(

@greg0ire @soullivaneuh  ?

**Comment by greg0ire** [comment]
![Screenshot_2020-01-14 sonata-project SonataAdminBundle](https://user-images.githubusercontent.com/657779/72328630-8e242200-36b3-11ea-932e-d0c322eab449.png)

**Comment by phansys** [comment]
Stale bot is currently working.
