### ISSUE TITLE
Create new .github repo for shared files

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#531]
We can remove some dev-kit sync actions, when creating a `.github` repository:
https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization

**Comment by OskarStark** [comment]
cc @localheinz

**Comment by localheinz** [comment]
Sounds good! 👌

**Comment by VincentLanglet** [comment]
I'm not sure it will be really useful.

The dispatch command seems to work well.

And we're starting to add condition in some files, for instance the README: https://github.com/sonata-project/dev-kit/pull/792. This will not be possible with a `.github` repository.

**Comment by core23** [comment]
> I'm not sure it will be really useful.

We could reduce the dev-kit updates for trivial things (issue templates, CODEOWNERS, ...).

**Comment by OskarStark** [comment]
I think we don’t need the .github repo, dev-kit works well with PRs

**Comment by OskarStark** [comment]
Let's close here, if someone is not fine, please reopen 😊
