### ISSUE TITLE
Remove Travis CI

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#532]
We don't need this anymore, when using GitHub actions. These actions are (atm) faster than running Travis CI. You get a faster response and you can see what test is failing, e.g. Code Style, PHP 7.3, ...

I switched to GA a few days ago for my personal repos:
https://github.com/core23/ShariffBundle/blob/master/.github/workflows/continuous-integration.yml

**Comment by greg0ire** [comment]
Yes please! How about we start with docs and lint? BTW, is lint still needed with Flintci?

**Comment by core23** [comment]
> Yes please! How about we start with docs and lint? 

That would be a good starting point :+1: 

> BTW, is lint still needed with Flintci?

We don't need Flint CI or any other proxy service. We can do everything with GH Actions :rocket:
