### ISSUE TITLE
Travis: Sphinx is already installed

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#56]
Ref: https://github.com/sonata-project/dev-kit/issues/55#issuecomment-218298611

Spinx should not be installed as it seems to be already here.

**Comment by greg0ire** [comment]
Fact-checking PR : https://github.com/sonata-project/SonataAdminBundle/pull/3792

**Comment by Soullivaneuh** [comment]
@greg0ire Is this issue still relevant?

**Comment by greg0ire** [comment]
Nope. Sphinx is required anyway by the other deps, and the system Sphinx can't be taken into account by pip (it seems)
