### ISSUE TITLE
Remove Prophecy in Sonata project

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#624]
Cf: https://github.com/sebastianbergmann/phpunit/issues/4141

Should we try to remove the dependency  and re-write the tests with prophecy ?

**Comment by greg0ire** [comment]
I think we could use the trait contributed here: https://github.com/phpspec/prophecy-phpunit/pull/20

There will probably be a rector for this soon

**Comment by VincentLanglet** [comment]
@sonata-project/contributors I feel like this could be reconsidered

Here, prophecy was recommended: https://github.com/sonata-project/dev-kit/issues/89

But if I search for `createMock` or `prophesize` I find:
- 225 prophesize and 381 createMock/createStub for SonataAdmin
- 33 prophesize and 61 createMock for SonataDoctrineORM

And I reviewed more PR with `createMock/createStub` than `prophesize` recently.

Shouldn't we recommend to follow the majority ?
IMHO both are fine, but if we want some consistency it could be easier to change all the `prophesize` rather than change and all the `createMock/createStub`.

**Comment by greg0ire** [comment]
Another argument in favor of PHPunit is how better it plays with PHPStan and Psalm, in my experience it is easier to work with, but maybe my experience is outdated.

**Comment by jordisala1991** [comment]
IMO phpuniy has improved a lot since when we recommended using prophecy. Now they look similar and we could consider stop using it.

**Comment by core23** [comment]
I prefer prophecy, because you can better mock method calls with different arguments. PHPUnit still requires the exact call order. You can also archive the same result with writing less code. (And the API is similar in Java  :D)

prophecy:
```php
        $this->request->get('start')->willReturn('2016-03-01');
        $this->request->get('end')->willReturn('2016-03-19 15:11:00');
```

phpunit
```php

        $this->request->expects(static::exactly(2))
            ->method('get')
            ->withConsecutive(
                ['start'],
                ['end'],
            )
            ->willReturn(
                '2016-03-01',
                '2016-03-19 15:11:00'
            )
        ;
```

**Comment by VincentLanglet** [comment]
> PHPUnit still requires the exact call order. 

Maybe one day it won't :)
https://github.com/sebastianbergmann/phpunit/issues/4026

I'm sure we will always find people who prefer prophecy and some who prefer phpunit.
But since https://github.com/sebastianbergmann/phpunit/issues/4141, I find weird to recommend prophecy.
And I think having consistency in our tests could be great, which seems easier to get if phpunit is the standard.

**Comment by jordisala1991** [comment]
This is almost done, AFAIK it only needs to be removed from docs now

**Comment by VincentLanglet** [comment]
> This is almost done, AFAIK it only needs to be removed from docs now

Could you provide a TODO list @jordisala1991 ? :)

**Comment by VincentLanglet** [comment]
it's done https://github.com/search?q=org%3Asonata-project+prophesize&type=code

I created the PR for the doc https://github.com/sonata-project/dev-kit/pull/1369
