### ISSUE TITLE
Add Markdown linter

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#63]
Maybe we could implement something which checks this:
https://github.com/sonata-project/SonataAdminBundle/pull/3798#issuecomment-218712963

**Comment by OskarStark** [comment]
Found this one: https://github.com/mivok/markdownlint

**Comment by Soullivaneuh** [comment]
1. https://github.com/wooorm/remark-lint
2. https://github.com/DavidAnson/markdownlint
3. https://github.com/mivok/markdownlint

I have a preference for `1` because it looks flexible and seems to have a nice output.

**Comment by greg0ire** [comment]
`1` seems more active and has many stars (less than `3`, but…)

**Comment by OskarStark** [comment]
`3` has a lot of rules and they are nice documented:
https://github.com/mivok/markdownlint/blob/master/docs/RULES.md

**Comment by Soullivaneuh** [comment]
I will manually check `1` and `3`

**Comment by Soullivaneuh** [comment]
Those linter looks both great, but none of them detect double backticks...

**Comment by OskarStark** [comment]
> Those linter looks both great, but none of them detect double backticks...

😄

**Comment by greg0ire** [comment]
> Those linter looks both great, but none of them detect double backticks...

- Create issue on both repos
- Use the first that solves the issue

**Comment by OskarStark** [comment]
We didn't really need it in the past... closing here
