### ISSUE TITLE
Discussion: Get rid of minor milestones

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#65]
This issue come from a dicussion with @greg0ire.

Minor milestones are painful for one and good reason: We will push minor release frequently, more frequently than Symfony.

Imagine we have 5 PRs for admin-bundle 3.x with deprecated messages and upgrade note for `3.1` and we have to push `3.1.0` release right now because of a security and/or critical fix.

Then, we have to tell to the 5 PRs authors to change deprecation message and upgrade notes to target `3.2`.

This will quickly be hard to manage them.

I have a solution to propose:
### Deprecated message

Don't specify since when it's deprecated. After all, if we push minor regularly, the user will not try to know from when this or that is deprecated and will just fix it.

Deprecated message could be like this:

``` php
/**
 * @deprecated since 3.x, will be removed on 4.0
 */
```

Or just don't specify the minor at all. But in this case, I don't really know how to construct the message. What do you think?
### Upgrade guides

Instead of creating an upgrade file of 5 lignes per minor, let's juste create only one that could be name, for example. `UPGRADE-3.x`.

The upgrade would be like this:

``` markdown
UPGRADE 3.x
===========

Deprecated stuff documentation...

UPGRADE FROM 3.1 to 3.2
=======================

Deprecated stuff documentation...

UPGRADE FROM 3.0 to 3.1
=======================

Deprecated stuff documentation...
```

The `UPGRADE 3.x` will be for the unreleased stuff. In any case, upgrade note on PR should be here.

When a new minor is release, the title will be changed to `UPGRADE FROM 3.2 to 3.3` and a new `UPGRADE 3.x` will appear.

What is your thinking about that?

cc @sonata-project/contributors

**Comment by greg0ire** [comment]
```php
/**
 * @deprecated since 3.x, will be removed on 4.0
 */
```

Honest question : who cares since when it is deprecated ?

**Comment by Soullivaneuh** [comment]
`@deprecated will be removed on 4.0` would produce a weird message on Symfony toolbar but, well, this is not the most important IMHO.

> or even this, since it will always be on the next major version and one could imagine a PR do be rescheduled to 5.0 :

:-1: for one important reason: other libraries implementing support of one of ours of many majors would like to add comment on BC layers like `To be dropped when bumping Sonata admin-bundle to 4.0`.

If we don't tell when it will be dropped, this would be harder for them.

BTW, I think a PR rescheduled to an another major would rare comparing with a reschedule to an another minor.

**Comment by greg0ire** [comment]
> BTW, I think a PR rescheduled to an another major would rare comparing with a reschedule to an another minor.

It will happen on every freeze.

**Comment by Th3Mouk** [comment]
@Soullivaneuh agree with first comment, i'm doing this way seems clearer.

**Comment by Soullivaneuh** [comment]
@Th3Mouk with which one ? `@deprecated since 3.x, will be removed on 4.0` or `@deprecated will be removed on 4.0`?

**Comment by Soullivaneuh** [comment]
@greg0ire Another solution can be to keep `since 3.x` part and when I'll prepare the new release, I could replace all `3.x` by the next minor. :+1:

**Comment by greg0ire** [comment]
`since {{ next_minor }}` :laughing:

**Comment by Soullivaneuh** [comment]
@greg0ire On `UPGRADE-3.x.md.twig`? :trollface:

**Comment by Soullivaneuh** [comment]
Ok so let's lock to this:

A `UPGRADE-3.x.md` file with that kind of content:

```markdown
UPGRADE 4.x
===========

Deprecated stuff documentation...

UPGRADE 3.x
===========

Deprecated stuff documentation...

UPGRADE FROM 3.1 to 3.2
=======================

Deprecated stuff documentation...

UPGRADE FROM 3.0 to 3.1
=======================

Deprecated stuff documentation...
```

And deprecation message should looks like this:

```
/**
 * @deprecated since 3.x, will be removed on 4.0
 */
```

And the `3.x` should be replaced by the next minor just before release.

I keep this issue open waiting for a PR on the contributing doc for both admin and user.

**Comment by core23** [comment]
Can we close this @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
@core23 Not now.

> I keep this issue open waiting for a PR on the contributing doc for both admin and user.

AFAIK, it's not done yet. :wink:

**Comment by jordisala1991** [comment]
Deprecations are already documented on the contributing guide: https://github.com/sonata-project/dev-kit/pull/312

Closing, if you think this is not solved yet, please reopen.
