### ISSUE TITLE
Status of SonataDoctrinePhpcrAdminBundle

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#659]
What are the status of SonataDoctrineMongoDBAdminBundle and SonataDoctrinePhpcrAdminBundle for you @sonata-project/contributors ?

When I look at the code, a lot of new feature/bugfix added in SonataDoctrineORMAdminBundle are missing in them. 

There is some direct copy-paste from SonataDoctrineORMAdminBundle which is not working without doubt.
For example: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/2.x/src/Model/ModelManager.php#L194 ; a copy paste from the DoctrineORMAdminBundle, this would return an error since the property associationMappings does not exist in Phpcr.

And there is couple of function throwing an exception “Not implemented”.
For example: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/2.x/src/Model/ModelManager.php#L527 ; which means that at least the export does not work.

Both bundle has less than 200 download per month when the doctrineORMAdminBundle has 5k per month. I don’t know who is using this but it seems like it misses a lot of feature/bugfix.

IMHO we should take a decision if we want to keep maintaining these bundles or not. If we do, we should add the same feature that we have in DoctrineORMAdminBundle and we’ll have a lot of work for the Sonata 4.0 compatibility.

I tried to start something here https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/585 just for the Phpcr filters, and this PR is already leading to a lot of question/decision to make.

**Comment by greg0ire** [comment]
@dbu maybe you can chime in about the phpcr bundle… I don't know that part of the ecosystem well.

**Comment by franmomu** [comment]
I use `SonataDoctrineMongoDBAdminBundle`, in fact it was one of the reasons a chose to use `sonata` and it's updated to use the last version of `doctrine/mongodb-odm`.

**Comment by VincentLanglet** [comment]
I may have made the mistake of putting in the same bag `SonataDoctrineMongoDBAdminBundle` and `SonataDoctrinePhpcrAdminBundle`.

`SonataDoctrineMongoDBAdminBundle` seems more up to date than `SonataDoctrinePhpcrAdminBundle`. Adding the last bugfix/new feature, and making Sonata 4.0 compatible will be easier.

**Comment by core23** [comment]
IMHO we should deprecate / abandon the `SonataDoctrinePhpcrAdminBundle` bundle and update the README for this repo.

**Comment by dbu** [comment]
yeah i am afraid that makes sense. it is not a priority of mine to invest time into it as i currently don't need it in any projects. there are some users, but not that many: https://packagist.org/packages/sonata-project/doctrine-phpcr-admin-bundle/stats

if abandonning it brings forth new maintainers, we can still see with them and resurrect the project, i guess.

**Comment by VincentLanglet** [comment]
Instead of deprecated the project, we could add that there is no active support and that we're looking for maintainer then.

**Comment by dbu** [comment]
if you don't mind updating the build system and other such maintenance things on it, that is fine too. but i can understand if the sonata team wants to abandon it and just leave it there for people who use it. 

i would not deprecate it, but marking as abandoned is honestly telling people that they can't expect any support or even expect it to work on newest symfony / php versions.

**Comment by core23** [comment]
> [... ] marking as abandoned is honestly telling people that they can't expect any support or even expect it to work on newest symfony / php versions.

👍 That would be the best solution. If someone will pick it up later, we can unabandoned it

**Comment by VincentLanglet** [comment]
WDYT of 
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/600
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/601
