### ISSUE TITLE
?object $object = null VS object $object = null

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#660]
Can we make a decision for the `nullable_type_declaration_for_default_null_value` rule of phpcs-fixer ?

@sonata-project/contributors  Do you prefer 
```
function foo(?object $object = null)
```
Or
```
function foo(object $object = null)
```

I personally prefer the first object, this way changing the default value doesn't change the allowed types. But I you prefer the second one, I'll go with it !

**Comment by core23** [comment]
👍 for the first one. So you can activly set a null value

**Comment by greg0ire** [comment]
I prefer the first one too, it's more explicit.

**Comment by phansys** [comment]
I tend to follow this convention:
* Nullable type declaration where the argument is nullable but explicitly required:
```php
function foo(?object $requiredObject)
```
* `null` as default value where the argument is nullable and optional:
```php
function foo(bool $requiredArg, object $optionalObject = null)
```
I'd avoid this form, since it will always make the argument optional:
```php
function foo(?object $requiredObject = null)
```

**Comment by VincentLanglet** [comment]
> I'd avoid this form, since it will always make the argument optional:
> 
> ```
> function foo(?object $object = null)
> ```

I don't understand, because when you write
```
function foo(object $object = null)
```
the argument is also **always** optional.

IMO, the default value should not have impact on the allowed value. Changing
```
final function foo(?bool $bool = null)
```
To
```
final function foo(bool $bool = false)
```
would be a BC-break when changing 
```
final function foo(?bool $bool = null)
```
To
```
final function foo(?bool $bool = false)
```
is not always one.

Since there is 9 contributors, I'll wait for 5 vote in favor of one of the two forms.

**Comment by phansys** [comment]
>I don't understand

Let's use a more realistic example:
```php
function isGranted(?object $object, bool $optionalArg = null)
{
    if (null === $object) {
        throw MyCustomDomainException();
    }

    if (null === $optionalArg) {
        // do something ...
    }
}
```
Based on this, we can make the following assumptions about the argument 1:
* Accepts an object or a null value;
* Is required;
* Calling the method without arguments will fail (`ArgumentCountError: Too few arguments to function isGranted()`).

If we force the codebase to always use the nullable type declaration (`?`) for every argument that uses `null` as default value, we'll lose the ability to distinguish between required and optional nullable arguments:
```php
function isGranted(?object $object = null, bool ?$optionalArg = null)
```

**Comment by VincentLanglet** [comment]
> If we force the codebase to always use the nullable type declaration (`?`) for every argument that uses `null` as default value, we'll lose the ability to distinguish between required and optional nullable arguments:
> 
> ```
> function isGranted(?object $object = null, ?bool $optionalArg = null)
> ```

I don't ask to write
```
function isGranted(?object $object = null, ?bool $optionalArg = null)
```
Instead of 
```
function isGranted(?object $object, bool $optionalArg = null)
```
But just
```
function isGranted(?object $object, ?bool $optionalArg = null)
```

That's totally different !
In you example, the first argument of `isGranted` didn't have a `null` default value.

**Comment by phansys** [comment]
Oh, that's great!
I agree with the proposal then :+1:

**Comment by VincentLanglet** [comment]
Need one more yes then ! 😀

**Comment by VincentLanglet** [comment]
@OskarStark @rande @soullivaneuh @nicolasricci @jordisala1991 

If you have time to vote :)

**Comment by OskarStark** [comment]
Let’s go with option 1 👍🏻
