### ISSUE TITLE
[RFC] Honor IETF's RFC 2119 in exception and deprecation messages

### ISSUE THREAD

**Issue by phansys** [sonata-project/dev-kit#679]
Even if this could seem excessively pedantic, I think we **SHOULD** honor and promote [IETF's RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) to Indicate requirement levels in our exception and deprecation messages.

IE:
* >Passing a string as argument 1 for someMethod() is deprecated since sonata-project/some-package 3.x and will be removed at 4.x. You MUST use otherMethod() instead.

* >You MUST call setFoo() before calling getFoo().

**Comment by greg0ire** [comment]
Also in upgrade guides 👍

**Comment by VincentLanglet** [comment]
I feel like it's utopian.
- Nobody will update every existing deprecated message.
- We certainly will forget this sometimes when reviewing PR.

So unless there is some kind of automatic linter, I would say 👎

**Comment by VincentLanglet** [comment]
This was added to the Contributing.md and new errors are respecting the RFC.
Since I don't think we will take time to rewrite all the existing exception messages, I think we can close this.
Exception messages will be updated as things progress
