### ISSUE TITLE
Support for pdo_sqlsrv

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#689]
I'm trying to run sandbox on MSSQL server. I got some errors like:
### FOREIGN KEY
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'FK_6CB28F47727ACA70' on table 'product__product' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or   
  ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.     
```
#### Resolve
We should avoid using `onDelete="CASCADE"`. `cascade={"remove"}` should be used. Additional option to switch to onDelete option will be nice (onDelete is quicker)
[More info about it.](https://stackoverflow.com/questions/27472538/cascade-remove-vs-orphanremoval-true-vs-ondelete-cascade)

#### or
Fix `onDelete="CASCADE"`to break cycles or multiple cascade paths.

### Params error and LIMIT
```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT count(cnt.product_id) AS "cntId"
FROM (
SELECT DISTINCT pc.product_id
FROM product__product_category pc
LEFT JOIN product__product p ON pc.product_id = p.id
LEFT JOIN classification__category c ON pc.category_id = c.id
LEFT JOIN product__product p2 ON p.id = p2.parent_id
WHERE p.enabled = :enabled
AND (p2.enabled = :enabled OR p2.enabled IS NULL)
AND (c.enabled = :enabled OR c.enabled IS NULL)
AND p.parent_id IS NULL
AND pc.category_id = :categoryId
LIMIT 500
) AS cnt' with params [1, 22]:

SQLSTATE[07002]: [Microsoft][ODBC Driver 17 for SQL Server]COUNT field incorrect or syntax error").
```

#### Resolve
Param should not be use twice or more. enabled2 and enabled3 should be add to fix parameters bug. [More info here](https://stackoverflow.com/questions/34089614/count-field-incorrect-or-syntax-error)
Limit should not be set in SQL code. 

## TODO - remove cascade cycles
- [x] ProductBundle
    - parent product -> product
- [x] PageBundle
    - parent_id block -> block
    - site_id page -> site
    - parent_id page -> page
    - target_id page -> page
- [x] ClassicicationBundle
    - parent_id category category

## TODO - fix sql query
- [ ] ProductBundle
    - fix sql 
- [x] NewsBundle
    - fix comment count command

**Comment by wbloszyk** [comment]
To reopen. I should write Part od instead closed. Sorry.

**Comment by VincentLanglet** [comment]
Hi @wbloszyk What the current situation of this issue ? :)

**Comment by wbloszyk** [comment]
Holidays 😄. I will describe it in Monday.

**Comment by VincentLanglet** [comment]
Closing as ecommerce is abandoned
