### ISSUE TITLE
Labels for issues

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#72]
We don't have enough label for issue. AFAIK, only "Bug", "Critical" and "Easy Pick" are relevant.

I was thinking about:

* feature
* enhancement (for performance, code refactor...)
* confirmed (to be used with "Bug")

Any idea?

cc @sonata-project/contributors

**Comment by core23** [comment]
Maybe "waiting for PR"?

**Comment by Soullivaneuh** [comment]
> Maybe "waiting for PR"?

Well, this label would be used on most of the issue list IMO...

**Comment by core23** [comment]
Don't agree with that. Some issues are questions. This label would help to filter issues that have waiting PRs.

**Comment by Soullivaneuh** [comment]
> This label would help to filter issues that have waiting PRs.

You have "Feature" and "Enhancement" for that.

> Some issues are questions.

Otherwise, adding a "Questions" label make more sense. But we have to determine what is a "Question" under issues. Help questions place is on StackOverflow, not GitHub.

**Comment by Soullivaneuh** [comment]
I'll start with:

* `feature`
* `enhancement`
* `unconfirmed` like SF does: https://github.com/symfony/symfony/labels/Unconfirmed

**Comment by greg0ire** [comment]
I'd say replace "bug" with "confirmed bug"

**Comment by OskarStark** [comment]
> I'd say replace "bug" with "confirmed bug"

sounds good to me

**Comment by Soullivaneuh** [comment]
Too late, sorry guys. :-/

BTW, the "Bug" label means the issue is talking about a bug.

"Unconfirmed" label should be add to complement the information and telling the bug is not yet confirmed by maintainers.

**Comment by OskarStark** [comment]
👍

**Comment by Soullivaneuh** [comment]
I close this issue but the debate itself is not closed.

I just want to add basic label to make the work easier.

If someone think another labels should be added, he can make a PR or an issue for discussion. :+1:
