### ISSUE TITLE
Drop SonataEasyExtends in Sonata bundles

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#750]
Same issue like SonataCoreBundle for SonataEasyExtends.
The bundle is deprecated since Symfony flex provides and easier path to install our bundles. The usages are on every bundle that defines Entities because it has a Doctrine Compiler pass to create the linking for the entities (associations, etc..)

The same code is on the https://github.com/sonata-project/sonata-doctrine-extensions
The SonataEasyExtends is used by: https://github.com/sonata-project/SonataEasyExtendsBundle/network/dependents?dependent_type=PACKAGE&package_id=UGFja2FnZS01NDMwMzc3MjY%3D

The process is:

- [x] **STEP 1:** Make sonata doctrine extensions work: https://github.com/sonata-project/sonata-doctrine-extensions/pull/184
- [x] **STEP 2:** Make EasyExtends optional on Sonata 3
    - [x] [sonata-project/comment-bundle](https://github.com/sonata-project/SonataCommentBundle/pull/190)
    - [x] [sonata-project/article-bundle](https://github.com/sonata-project/SonataArticleBundle/pull/171)
    - [x] [sonata-project/user-bundle](https://github.com/sonata-project/SonataUserBundle/pull/1183)
    - [x] [sonata-project/timeline-bundle](https://github.com/sonata-project/SonataTimelineBundle/pull/260)
    - [x] [sonata-project/page-bundle](https://github.com/sonata-project/SonataPageBundle/pull/1162)
    - [x] [sonata-project/notification-bundle](https://github.com/sonata-project/SonataNotificationBundle/pull/452)
    - [x] [sonata-project/news-bundle](https://github.com/sonata-project/SonataNewsBundle/pull/601)
    - [x] [sonata-project/media-bundle](https://github.com/sonata-project/SonataMediaBundle/pull/1753)
    - [x] [sonata-project/dashboard-bundle](https://github.com/sonata-project/SonataDashboardBundle/pull/225)
    - [x] [sonata-project/classification-bundle](https://github.com/sonata-project/SonataClassificationBundle/pull/536)
    - [x] sonata-project/ecommerce
    - [x] sonata-project/sandbox
- [ ] **STEP 3:** Remove EasyExtends BC code on Sonata 4
    - [ ] sonata-project/comment-bundle
    - [ ] sonata-project/article-bundle
    - [ ] sonata-project/user-bundle
    - [ ] sonata-project/timeline-bundle
    - [ ] sonata-project/page-bundle
    - [ ] sonata-project/notification-bundle
    - [ ] sonata-project/news-bundle
    - [ ] sonata-project/media-bundle
    - [ ] sonata-project/dashboard-bundle
    - [ ] sonata-project/classification-bundle
    - [ ] sonata-project/ecommerce

**Comment by jordisala1991** [comment]
There are 2 bundles that were already started:

- ClassificationBundle have an [open PR](https://github.com/sonata-project/SonataClassificationBundle/pull/502) from @franmomu . Since it is open from february I opened a new one. Do you mind if I continue you work? I would like to pick the documentation part of the PR.

- NotificationBundle have a [PR merged](https://github.com/sonata-project/SonataNotificationBundle/pull/414) already. IMO it could be considered a BC break because you might now have DoctrineExtensions enabled, we should throw a deprecation and use EasyExtendsCollector, I can create a new PR and add the compatibility layer necessary. WDYT @sonata-project/contributors .

**Comment by jordisala1991** [comment]
From now , all PRs are created and the changes on the code are applied, but I marked all draft because it is missing the docs change.

**Comment by jordisala1991** [comment]
@phansys @core23 can you check any of the PR with and without this fix? https://github.com/sonata-project/SonataClassificationBundle/pull/502

**Comment by jordisala1991** [comment]
All the bundles got the first iteration of the PR ready. There is still the problem with this PR, sonata-project/sonata-doctrine-extensions#184

There are 2 bundles that suffer directly from this problem in their PRs, because have functional tests: https://github.com/sonata-project/SonataPageBundle/pull/1162 and https://github.com/sonata-project/SonataMediaBundle/pull/1753

ping @core23 @phansys

**Comment by jordisala1991** [comment]
Step 1 ready and released.
Step 2 all PR ready to review.

**Comment by VincentLanglet** [comment]
I think we can close this issue @jordisala1991.

Since the SonataEasyExtends-related code is marked as deprecated it will be removed for sure in 4.0

**Comment by jordisala1991** [comment]
Agree
