### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#752]
There are some projects that try to remove oppresive terms from their code (e.g. master / slave, blacklist / whitelist, ...). I would like to discuss if we should follow and rename all `master` branches to `main`.

See https://tools.ietf.org/id/draft-knodel-terminology-00.html, https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

**Comment by greg0ire** [comment]
Fully on board with the rename!

Not sure we want to use `main` though, since it will certainly not be the default. Let's take this as an occasion to convey the fact that this branch is the one where people should commit if they have bc-breaks to make? Or let's convey that it will be the next major?

- `backwards-incompatible`
- `bc-breaking`
- `next-major`
- `unstable`
- `4.x` if the current stable is `3.x`?

**Comment by core23** [comment]
👍 Would prefer the next major version e.g. `4.x`

**Comment by greg0ire** [comment]
As a bonus it means we can get rid of the branch alias :)

**Comment by greg0ire** [comment]
Let's try to think of everything. Here is what this could look like

1. Prepare a PR on dev-kit with renames of the branches in the config, changes to the contributing guide, and more things found at https://github.com/sonata-project/dev-kit/search?q=master&unscoped_q=master
2. Create the new branches on all repos. We don't need to protect them: https://github.com/sonata-project/dev-kit/blob/1803938be9df93648d2ad41c09a543b55df2484e/src/Command/DispatchCommand.php#L296-L330 Maybe we even don't need to create them, I'm not sure. We can add a commit that drops the branch alias on those branches
3. Merge the PR on dev-kit and deploy
4. Remove the `master` branch on all repos and celebrate
5. Take care of the `master` branch of dev-kit itself?

Tell me if I'm missing some steps.

**Comment by OskarStark** [comment]
> Remove the master branch on all repos and celebrate

We need to change all PR's to the new base branch. IIRC there was a tweet on how to achieve that.

**Comment by greg0ire** [comment]
Oh good point! I think we might not have that many, but still!

**Comment by core23** [comment]
> 3. Merge the PR on dev-kit and deploy

3.1. Change the default branch on all repos, ohterwise we can't delete the master branch

**Comment by greg0ire** [comment]
`master` is never the default branch on our repos, is it?

**Comment by core23** [comment]
> `master` is never the default branch on our repos, is it?

At least the https://github.com/sonata-project/SonataDashboardBundle/branches project does not have any version branch.

**Comment by greg0ire** [comment]
Here is a TODO list for later use

- [ ] GoogleAuthenticator
- [ ] SonataAdminBundle
- [ ] SonataAdminSearchBundle
- [ ] SonataArticleBundle
- [ ] SonataBlockBundle
- [ ] SonataCacheBundle
- [ ] SonataClassificationBundle
- [ ] SonataClassificationMediaBundle
- [ ] SonataCommentBundle
- [ ] SonataDashboardBundle
- [ ] SonataDatagridBundle
- [ ] SonataDoctrineMongoDBAdminBundle
- [ ] SonataDoctrineORMAdminBundle
- [ ] SonataDoctrinePhpcrAdminBundle
- [ ] SonataEasyExtendsBundle
- [ ] SonataFormatterBundle
- [ ] SonataIntlBundle
- [ ] SonataMediaBundle
- [ ] SonataNewsBundle
- [ ] SonataNotificationBundle
- [ ] SonataPageBundle
- [ ] SonataSeoBundle
- [ ] SonataTimelineBundle
- [ ] SonataTranslationBundle
- [ ] SonataUserBundle
- [ ] cache
- [ ] ecommerce
- [ ] exporter
- [ ] sandbox
- [ ] twig-extensions

**Comment by greg0ire** [comment]
Apparently a renaming feature is planned: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories- If we are in a hurry we can use https://www.npmjs.com/package/retarget_prs

**Comment by VincentLanglet** [comment]
The feature is available now.

**Comment by OskarStark** [comment]
We need to rework dev-kit in this case

**Comment by VincentLanglet** [comment]
> We need to rework dev-kit in this case

Yes, I never said that would be easy 😅

**Comment by VincentLanglet** [comment]
Solved by https://github.com/sonata-project/dev-kit/issues/1622
