### ISSUE TITLE
Consider running builds with composer v2

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#776]
It would be nice to switch to composer v2, even if it is still in alpha it is working better than the v1 in terms of performance.

I will try a PR to show the performance benefits on the adminBundle

Edit: As a bonus, it will allow to not have infinite builds on prefer lowest, because it handles well the lower package resolution

**Comment by OskarStark** [comment]
Sounds great 👍🏻 

Maybe have it as an additional build until it’s stable?

**Comment by jordisala1991** [comment]
This is done
