### ISSUE TITLE
Webpack encore and templates upgrade 

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#779]
ATM we have the problem, that we use hard copies of all external assets. 

## Resolve
1. Support for old external assets
    - move current external assets to seperate place
    - remove it from bundles
    - download it when people use old assets system (someting like phpunit)
1. New assets system - webpack
    - create new sandbox branch for it
    - add webpack for current bootstrap3 templates 
    - upgrade templates to bootstrap4  

Closes #433, #398. 

### SonataAdminBundle
- [ ] dependencies
    - [ ] Move [jquery.confirmExit.js](https://github.com/dunglas/jquery.confirmExit/blob/master/jquery.confirmExit.js) to own files
    - [ ] ? jqueryui
    - [ ] ? eonasdan-bootstrap-datetimepicker (in its current version)
    - [ ] Remove ionicons
    - [ ] Remove x-editable (or make it compatible with boostrap 4 or implement own solution)
    - [ ] Upgrade admin lte to v3 (check sandbox branch and older prs on sonata admin)
    - [ ] Integrate / Remove missing dependencies
    - [ ] Upgrade some dependencies (and stop fixing versions on package.json)
- [ ] webpack
    - [ ]  Integrate our code with the webpack encore process
    - [ ] Consider integration with webpack encore bundle
- [ ] tools
    - [ ] Add ESLint 
    - [ ] Add stylelint 
- [ ] other
    - [ ] Documentation about the frontend assets for contributors
    - [ ] Documentation about the frontend assets for users of the bundle
    - [ ] Generate the dist files only on release (maybe not necessary)

**Comment by wbloszyk** [comment]
@core23 @jordisala1991 @greg0ire @VincentLanglet Can you create new sandbox branch 'webpack' from master? I will prepare structure for some build like `sonata_admin_v3`, `sonata_shop_v3`, `sonata_admin_v4` ... and templates `bootstrap3`, bootstrap4`.

**Comment by greg0ire** [comment]
Sure, done.

**Comment by jordisala1991** [comment]
The work for SonataAdmin is done. Maybe we could use an issue to track what other packages are needed.
