### ISSUE TITLE
Prepare bundles to major release

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#780]
SonataCoreBundle was dropped and last conflict was resolve. It mean we can use master branches (sonata4) with sonata3. :tada: 

Of course this will be so beautiful to be true. Anyway after some easy change it is possible. 

### Problem
As you know `AbstractAdmin` and `AbstractBlockService` are used in Sonata3 bundles without return type hints and we can't use it with Admin/BlockBundle v4 with return type hints. 

### Solutions
1. Add return type hints in Sonata3 - BC-break
1. Release AdminBundle as last bundle in Sonata4 and for people to upgrade it as last too - :-1: 
1. Drop return type hints in Admin/BlockBundle where this is needed and revert it in Sonata5 - :+1: :1st_place_medal: 
    - add return type hints in other Sonata4 bundles will allow do revert it in Sonata5 

### prepare Admin/BlockBundle v4
- remove comflict return type hints

### Prepare 3.x branches
- (optional) drop support for symfony < 4.4 and php < 7.2
- (optional) add support for `nelmio/api-doc-bundle` v3 (will be nice remove v2 in Sonata4 - BC-break)

### Prepare master branches
- add support for BlockBundle v4 (it is mean v3 will be supported too)
- add support for KnpMenuBundle v3 (and keep support for v2 too)

I will split it to TODO PRs list after approve this idea.

**Comment by VincentLanglet** [comment]
I'm not convinced by the fact to use a v3 bundle with a v4 bundle.
In the same way Symfony 5 is not always compatible with Symfony 4 bundles.

IMO
SonataAdmin v4 should support Block v4, and SonataAdmin v3 should support Block v3
In the same way SonataDoctrineORMAdmin v4 should support SonataAdmin v4, and SonataDoctrineORMAdmin v3 should support SonataAdmin v3

**Comment by core23** [comment]
> I'm not convinced by the fact to use a v3 bundle with a v4 bundle.
> In the same way Symfony 5 is not always compatible with Symfony 4 bundles.

First, we are not symfony. Symfony supports at least two versions, e.g the latest LTS version and the current major version for the [framework itself](https://packagist.org/packages/symfony/framework-bundle#v4.4.8)

> IMO
> SonataAdmin v4 should support Block v4, and SonataAdmin v3 should support Block v3
> In the same way SonataDoctrineORMAdmin v4 should support SonataAdmin v4, and SonataDoctrineORMAdmin v3 should support SonataAdmin v3

This version strategy caused a lot of trouble for us in the last 2-3 years where we started working on new major versions. This will even cause a lot of more trouble for the end users.

I agree, that we should enforce same major versions for the admin components, but not the rest of our bundles (block, seo, datagrid, ...).

**Comment by VincentLanglet** [comment]
> This version strategy caused a lot of trouble for us in the last 2-3 years where we started working on new major versions. This will even cause a lot of more trouble for the end users.
> 
> I agree, that we should enforce same major versions for the admin components, but not the rest of our bundles (block, seo, datagrid, ...).

If I understand correctly, you mean that
SonataAdmin v4 should support Block v4 and Block v3
SonataDoctrineORMAdmin v4 is allowed to only support SonataAdmin v4

**Comment by wbloszyk** [comment]
@VincentLanglet 
We don't have support two version but we can support in in first release (4.0.0). and remove it in next minor(4.1.0). This allow people to upgrage one bundle, check it and upgrade another. I don't want to force people to upgrade all bundles at once and 
praying that it would work.

For example after this change using Admin v4 is possible with Sonata3. 
https://github.com/sonata-project/SonataAdminBundle/pull/6197/files

**Comment by VincentLanglet** [comment]
> For example after this change using Admin v4 is possible with Sonata3.
> https://github.com/sonata-project/SonataAdminBundle/pull/6197/files

There is no `Sonata3` project. Which one do you talk about ?
There is `SonataBlock`, `SonataCore`, `SonataAdmin`, `SonataDoctrineORMAdmin`, ...

We may add support for both V3 and V4 BlockBundle for SonataAdmin and storages bundle.
But SonataAdmin and storages bundles are IMHO meant to be updated together. 
So we don't need to remove typehint, and we should instead finish to add them every where.

**Comment by wbloszyk** [comment]
Allow use master with Sonata v3 bundles 

> > For example after this change using Admin v4 is possible with Sonata3.
> > https://github.com/sonata-project/SonataAdminBundle/pull/6197/files
> 
> There is no `Sonata3` project. Which one do you talk about ?
> There is `SonataBlock`, `SonataCore`, `SonataAdmin`, `SonataDoctrineORMAdmin`, ...

Allow use master with Sonata v3 bundles 

> We may add support for both V3 and V4 BlockBundle for SonataAdmin and storages bundle.
> But SonataAdmin and storages bundles are IMHO meant to be updated together.
> So we don't need to remove typehint, and we should instead finish to add them every where.
> 
> > I don't want to force people to upgrade all bundles at once and
> > praying that it would work.
> 
> Almost every changes required to use the V4 are currently triggering a deprecation.
> If you fix every deprecations, you'll update to v4 smoothly.

**Comment by core23** [comment]
> We don't have support two version but we can support in in first release (4.0.0). and remove it in next minor(4.1.0). This allow people to upgrage one bundle, check it and upgrade another. I don't want to force people to upgrade all bundles at once and
> praying that it would work.

👍 This is the symfony way. They support the latest LTS and latest stable version. 

This will also save a lot of time for us. Otherwise we have to release nearly all bundles in a very short time period, which is impossible for our small team. We are working on the next major version for years... 

> If I understand correctly, you mean that
> SonataAdmin v4 should support Block v4 and Block v3
> SonataDoctrineORMAdmin v4 is allowed to only support SonataAdmin v4

👍 The admin bundles are strictly coupled, so there is no easy way in supporting two stable SonataORMAdmin/SonataMongoAdmin versions in one SonataAdmin stable version.

**Comment by VincentLanglet** [comment]
Closing since Sonata 4 is released.
