### ISSUE TITLE
Add github-action for phpunit on dev-kit

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#798]
This PR https://github.com/sonata-project/dev-kit/pull/797 add the first test of the dev-kit project.

We could add more tests, for exemple to check the template generation result. 
Currently it's not easy to know if a PR like this https://github.com/sonata-project/dev-kit/pull/792 is working properly or not.

But first of all, we should add a github action to run the tests.

**Comment by OskarStark** [comment]
We could build a GitHub action which dispatches the command against the current repositories and outputs the result as diff in a comment in the PR itself. Maybe @localheinz can support us here 🤗🙃

**Comment by jordisala1991** [comment]
The github action running phpunit tests is already setup
