### ISSUE TITLE
Doc: Changelog format

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#8]
We have to get a clear position about how to feed changelog.

@sonata-project/contributors I'll create a PR for this but you can start a discussion with ideas here.

**Comment by Soullivaneuh** [comment]
[Gush](https://github.com/gushphp/gush) might by useful for that.

**Comment by greg0ire** [comment]
Might be a useful reference : http://keepachangelog.com/

**Comment by Soullivaneuh** [comment]
> Might be a useful reference : http://keepachangelog.com/

I like the "Unreleased" concept. In any case all the PR list should be reviewed and compare but it will reduce time to prepare.

**Comment by Soullivaneuh** [comment]
See also: https://github.com/stevewest/changelog

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors Are we OK to follow http://keepachangelog.com/ ?

:+1: for yes.
:-1: for no, with a comment of why below.

This **must** be decided before starting new tagging.
