### ISSUE TITLE
Add dev installation documentation

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/dev-kit#818]
The dev-kit readme is kinda short.

There is no information about how to
- Install locally the project
- Run tests
- Run commands
- Find the value to change the `.env` file.

And I discovered that, there is no installation help in the others bundles too !
We should help contributors.

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/dev-kit/pull/816 will introduce the first Installation explanations 🥳

**Comment by VincentLanglet** [comment]
@OskarStark You work a lot on the devkit, do you think you could write some doc about it ?

**Comment by OskarStark** [comment]
Yes but currently to much work on my desk 😞
