### ISSUE TITLE
Add type coverage report

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#867]
We're adding more and more (generics) type hints and try to remove all `mixed` attributes. We should add psalm type coverage report to visualize our progress. 

You can show type coverage when calling 

```bash
psalm --stats
```

Shepherd is an online service where you can store the coverage result.

Something like this:

[![Type Coverage](https://shepherd.dev/github/ergebnis/composer-normalize/coverage.svg)](https://shepherd.dev/github/ergebnis/composer-normalize)

**Comment by core23** [comment]
We got the first coverage report 🥳 

https://shepherd.dev/github/sonata-project/SonataAdminBundle

Next step: Add this to the README

**Comment by OskarStark** [comment]
Done in #1140
