### ISSUE TITLE
Move private repos to GitHub

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#879]
We are using GitLab for our private repos (website, doc-builder), because GitHub did not provide free private repos in the past. 

Now it's time we should move all our repos to one place.

- [ ] Move repos
- [ ] Refactor code
- [ ] Create github actions
- [ ] Deploy

**Comment by OskarStark** [comment]
Makes sense 👍

**Comment by VincentLanglet** [comment]
I heard about https://gitlab.com/sonataproject/sonata-project.org
What are the others ?

And why are we using private repository ?
If we use a public repository for the sonata website, contributors could help us.

I think this issue is important since
- Some deprecated bundle are still in the website
- Some bundle are not https://github.com/sonata-project/form-extensions/issues/84

**Comment by core23** [comment]
> I heard about https://gitlab.com/sonataproject/sonata-project.org
> What are the others ?

There is only one other for the docs: https://gitlab.com/sonataproject/doc-builder

> And why are we using private repository ?
> If we use a public repository for the sonata website, contributors could help us.

IMHO there is nothing secret inside the repo, so we could make it public 👍 

> I think this issue is important since
> 
>     * Some deprecated bundle are still in the website
> 
>     * Some bundle are not [sonata-project/form-extensions#84](https://github.com/sonata-project/form-extensions/issues/84)
> 
> 
> Is @rande the only one with the rights to create a repository ?

Don't know. 


The whole page should have a redesign, e.g. using the GitHub API to grab all repos on the fly.

**Comment by wbloszyk** [comment]
> > And why are we using private repository ?
> > If we use a public repository for the sonata website, contributors could help us.
> 
> IMHO there is nothing secret inside the repo, so we could make it public 

I'm not sure about nothing secret inside. Look at doc and deploy:
https://github.com/sonata-project/sonata-project.org/blob/master/Makefile

**Comment by core23** [comment]
> I'm not sure about nothing secret inside. Look at doc and deploy:
> https://github.com/sonata-project/sonata-project.org/blob/master/Makefile

Did we import the website to GitHub? I don't have permissions :(

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/sonata-project.org is moved to github.

Does https://gitlab.com/sonataproject/doc-builder has been moved too ?

**Comment by OskarStark** [comment]
Friendly ping @rande

**Comment by VincentLanglet** [comment]
Not sure we need it anymore since we've moved the docs
