### ISSUE TITLE
`make cs-fix` fixes cache files....

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#883]
![Bildschirmfoto 2020-09-02 um 09 01 51](https://user-images.githubusercontent.com/995707/91942301-000cb280-ecfb-11ea-991e-1743a30b0b17.png)

**Comment by VincentLanglet** [comment]
@OskarStark Does the bug still occur to you ? I never encounter this issue.

**Comment by wbloszyk** [comment]
I have the same issue. IMO we should exclude `var` directory for using project like sandbox.

**Comment by VincentLanglet** [comment]
Oh, I see, it's because I never work with a project like this.

Do you want to make the PR @wbloszyk ?

**Comment by wbloszyk** [comment]
Sure.
