### ISSUE TITLE
Composer: Circular dependencies version target issue

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#95]
Travis job: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/131844587#L222

In a nutshell, block-bundle 4.x can't be tested with stable version of admin-bundle because this one require block-bundle 3.x stable.

We can't bump version constraint on a stable version of admin-bundle, we have to found a trick to force the test.

What is your suggestions @sonata-project/contributors?

**Comment by jordisala1991** [comment]
SonataBlockBundle requires SonataAdminBundle just for 2 things:

- Sonata\AdminBundle\Form\FormMapper is used on the code to do a type hinting in 8 classes.
- Sonata\AdminBundle\Admin\AdminInterface is used on TextBlockService to check a variable type.

It is a bit weird to have a circular dependency. I think there are ways to break this circular dependency like:

- Move those classes to CoreBundle
- Move a interface to CoreBundle
- In the case of the AdminInterface find a better way to do the checkings.
- Move part of the code to AdminBundle

I don't really know how to do it or which one is the best solution, but it's strange depending on some bundle that already depends on you.

**Comment by Soullivaneuh** [comment]
@jordisala1991 Indeed we have to work on things like that. :+1: 

But this is a discussion that have to be done on concerned bundles for next minor on a BC way.

Maybe this will solve Travis itself, but for know, we have to found a trick to test code already here and stable.

**Comment by VincentLanglet** [comment]
There is no sonata-admin dependency in https://github.com/sonata-project/SonataBlockBundle/blob/4.x/composer.json
