### ISSUE TITLE
Branch merging automation

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#96]
Since we have a homogeneous branch management, maybe we can introduce branch auto merging.

A cron task could run every night to merge all stable branches of each repo into the master one.

Of course, branches with conflicts will be ignored.

This will avoid long branch difference if we forgot to merge them from a while...

In addition, a web page could be added later, showing branches that need manual merge.

@sonata-project/contributors What do you think?

**Comment by core23** [comment]
Maybe we could use slack for merging conflicts?

**Comment by Soullivaneuh** [comment]
@core23 Can you elaborate? How Slack could help us?

**Comment by core23** [comment]
Instead of using a web page to show conflicts while merging into master, we could use slack to print a conflict error into a channel.

**Comment by Soullivaneuh** [comment]
Oh yes, it could be an another nice addition! :+1: 

Plus, contributors could comment on it if they know why this is on under conflicts, to help the merger.

**Comment by OskarStark** [comment]
This automerging would help a lot

Am Sonntag, 22. Mai 2016 schrieb Sullivan SENECHAL :

**Comment by greg0ire** [comment]
:+1: on this

**Comment by OskarStark** [comment]
Should we do this by creating a PR on github or a direct push?

**Comment by Soullivaneuh** [comment]
> Should we do this by creating a PR on github or a direct push?

Direct push.
