### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/dev-kit#98]
In sonata, we have a lot of project translations to maintain.

Some people can be good translator and give us a real additions to our packages but are probably not coder and don't know anything about git.

This is why it would be great to have a translation platform for community.

Transiflex, could be a solution, but we have to contact us to ask a free open-source plan.

The another solution will-be to have a self-hosted translation platform.

I'll list here the available tools for that:
- Pootle: http://pootle.translatehouse.org/index.html
- Weblate: https://weblate.org/en/

If you know some, please tell me! I would update the list.

**Comment by greg0ire** [comment]
@sagikazarmark suggested [Crowdin](https://crowdin.com/page/open-source-project-setup-request)

**Comment by jordisala1991** [comment]
Closing in favour of #1614
